### ISSUE TITLE
Test BPF complexity on newer kernels

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#10798]
We currently test the complexity (from verifier) of our BPF programs using `./test/bpf/check-complexity.sh` and the `MAX_*_OPTIONS` in `bpf/Makefile`. However, these run as part of the `Runtime*` tests (i.e., `RuntimeVerifier`) and therefore only on Linux 4.9. Thus, all NodePort-related options are excluded from `MAX_*_OPTIONS`.

To run this on newer kernels, we can move the test to `K8sVerifier` and define new targets in the Makefile specifically for newer kernels. We would then choose the Makefile target based on the underlying kernel version.

Moving `RuntimeVerifier` to `K8sVerifier` requires the addition of test helpers to stop, clean, and restart Cilium. Similar code is already present in `K8sUpdates`.

- [x] Move the test to `k8sT/`. #12658
    - Terminate Cilium pods
    - Clean BPF objects from bpffs.
    - Compile BPF datapath.
    - Load in kernel.
- [x] Fix test-verifier.sh for 4.19 and net-next kernels.
    - [x] Fix loading on net-next (bpf_xdp). #13927
    - [x] Fix loading on 4.19 (bpf_sockops). #13953
- [x] Add a make target for 4.19 and net-next kernels. #14451

Related: #5058
Related: #10712.

**Comment by joestringer** [comment]
Related: [CI: Nightly tests for verifier complexity](https://github.com/cilium/cilium/issues/5058)

**Comment by pchaigno** [comment]
With #14451 merged, this issue can now be closed :tada: 

Next step: testing more than one combination of options (cf. https://github.com/cilium/cilium/issues/5058) :rocket:
