### ISSUE TITLE
Agent memory optimization (Season 2)

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#11726]
## Summary

The memory consumption of the agent has not been fully optimized yet. Optimization of the memory footprint has been a frequent user ask.

This is a follow-on of Season 1: https://github.com/cilium/cilium/issues/10056

## Details

The memory consumption consists of:
 - Direct memory consumption of the cilium-agent
 - Peak memory allocation of the agent with delayed release of the Go runtime
 - Maximum memory usage of all components running inside the Cilium pod at once, potentially exceeding the configured memory limit of the pod. (agent + health endpoints + Envoy + client invocations)
 - eBPF map usage

## Tasks

 - [ ] Identify memory peaks where memory is allocated in a loop and then released again to avoid idling heap memory that is not released again.
 - [x] Consider introducing dynamic sizing of maps based on available memory for conntrack table or other large maps
 - [ ] Investigate peak memory usage (which could lead to `cilium-agent` getting OOMkilled) during sysdump (e.g. during `cilium endpoint list`?)

**Comment by tklauser** [comment]
FWIW, dynamic sizing of maps was already introduced for CT, NAT and policy maps as part of #10056 by #10780, but it seems I forgot to tick it off on the list of items.

Unless of course there are other possible optimizations regarding dynamic sizing which that PR didn't yet consider.
