### ISSUE TITLE
Followups for host endpoint and firewall

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#11799]
**Most items are not blocking. Please check the lists below. I'll remove the `priority/release-blocker` label once the blocking items have been backported.**

## Host endpoint

- [x] Move direct routing configs to `node_config.h`. #11594
- [ ] Add unit tests for `patchHostNetdevDatapath()` and `nullifyStringSubstitution()`.
- [x] Move last bit of `bpf_host` loading from `init.sh` to Golang. #11598 #11856
- [ ] ~~Generate one `ep_config.h` header file per interface for easier debugging. #12657~~
- [ ] Skip devices for which we fail to attach BPF programs instead of skipping all.
- [ ] Skip warnings on symbols instead of using `nullifyStringSubstitutions()`.
- [x] Ignore errors on [tc filter delete for egress](https://github.com/cilium/cilium/blob/1256a13bed02ada24ebf693bf2edd5af3bdba7fa/pkg/datapath/loader/loader.go#L248). #13591

## Host policies

- [x] Fix and add example of CCNP. #11638
- [x] Mark host policies as not enforced if option disabled. #11759 #11856
- [x] Fix identity resolution after SNAT on to-netdev path. #12345 #12600
- [x] Fix host policies when using encapsulation. #11795 #11893
- [x] Fix missing case for ARP on `from-{host,netdev}` paths. #11795 #11893
- [x] Fix policy enforcement in case of BPF-based NodePort SNAT. ~~#12011~~ #12345 #12600
- [x] Fix handling of ICMPv6 NeighborSolicitation messages. #12049 #12345 #12600
- [x] Expose as Helm variable. #11795 #11893
- [x] Enable host firewall in kube-proxy-free CI. #11795 #11893
- [x] Enable host firewall in kube-proxy CIs. #11969 #12173
- [ ] ~~Error/warn more loudly if loading policy while host firewall is disabled.~~
- [x] Rework `Node.MarshalJSON()`. #11651
- [x] Fix aggregation of packet events from host firewall. Superseded by #12561
- [x] Double check that verifier hints are still needed. #11977
- [x] Fix `Enforcement` reported as `Enabled` when `PolicyEnforcement=always`. #12497 #12536
- [x] Create issues for `externalTrafficPolicy=Local` and portmap incompatibilities. #12541 #12542
- [x] Error/warn on `per-endpoint-routes` with host firewall. #12495 #12536

Documentation:
- [x] Mark as beta in documentation and option. #11799 #12203
- [x] Write getting started guide. #12537 #12600
- [x] Write requirements and limitations in documentation. #11799 #12203
- [x] Move examples to better location. #11799 #12203

Tests:
- [x] Disable host firewall in CI unless label is set. #12621
- [ ] ~~Load default host policy in CIs.~~
- [x] Test fromCIDR+toPorts host policies. #12621
- [ ] Test host policies with proxy path.
- [x] Test egress host policies with BPF-based SNAT #12621

## Node labels

- [x] Reuse `retrieveNodeInformation()` to get node labels. #11659

**Comment by tgraf** [comment]
Given that the host firewall is introduced as a beta feature, we don't have to treat this as a release blocker. We can list the known limitations in the guide of the host firewall feature and backport the relevant fixes over time if appropriate.

**Comment by pchaigno** [comment]
Closing as everything here has been addresses already or is tracked elsewhere.
