### ISSUE TITLE
Validate guides for 1.8 release

### ISSUE THREAD

**Issue by b3a-dev** [cilium/cilium#11903]
- **Managed k8s**
  - [x] [EKS](https://docs.cilium.io/en/latest/gettingstarted/k8s-install-eks/) (@tklauser ) ~#12078~ / #12098
  - [x] [GKE](https://docs.cilium.io/en/latest/gettingstarted/k8s-install-gke/) (@Rolinh ) ~#11960~ / ~#12087~
  - [x] [AKS](https://docs.cilium.io/en/latest/gettingstarted/k8s-install-aks/) (@gandro ) ~#12070~ 
    - ~Azure IPAM (@tgraf )~ (this is part of Azure Cloud below)

- **Self-managed**
  - [x] [Quick-install](https://docs.cilium.io/en/latest/gettingstarted/k8s-install-default/) (@tklauser )
  - [x] [w/ external etcd](https://docs.cilium.io/en/latest/gettingstarted/k8s-install-external-etcd/) (@nebril ) ~#11922~
  - [x] [Azure Cloud](https://docs.cilium.io/en/latest/gettingstarted/k8s-install-azure/#) (@errordeveloper ) ~#11978~ ~#12108~ #12113 (marked as beta)

- **Guides**
  - [x] [Kubernetes without kube-proxy](https://docs.cilium.io/en/latest/gettingstarted/kubeproxy-free/) (@gandro ) ~#12095~
    - [x] Test and write-up small getting started section in docs for:
      - [x] XDP on GKE (@brb ) -- cannot be enabled, see ~#12105~ 
      - [x] XDP on AKS (@gandro ) ~#12150~ 
      - [x] XDP on EKS (@tklauser @borkmann ) ~#12138~  ~#12156~ 
  - [x] Using Cilium with BGP ~#12092~
    - [x] [kube-router](https://docs.cilium.io/en/latest/gettingstarted/kube-router/) (@joestringer )
    - [x] [BIRD](https://docs.cilium.io/en/latest/gettingstarted/bird/) (@joestringer )
  - [x] [Clustermesh on GKE](https://docs.cilium.io/en/latest/gettingstarted/clustermesh/) (@aanm / @joestringer) ~#12101~ 
  - [x] [Transparent encryption](https://docs.cilium.io/en/latest/gettingstarted/encryption/) (@christarazi ) ~#12088~ 
  - [x] [Kata](https://docs.cilium.io/en/latest/gettingstarted/kata-gce/) (@Rolinh  ) ~#12144~ 

- **Monitoring**
  - [x] [Metrics/Grafana](https://docs.cilium.io/en/latest/configuration/metrics/) (@gandro )
  - [x] Troubleshooting with [Hubble](https://docs.cilium.io/en/latest/troubleshooting/#observing-flows-with-hubble)/[HubbleRelay](https://docs.cilium.io/en/latest/troubleshooting/#observing-flows-with-hubble-relay) (@errordeveloper)

- **Other Orchestrators**
  - [x] [Docker](https://docs.cilium.io/en/latest/gettingstarted/docker/) (@tklauser )

**Comment by Rolinh** [comment]
Discussed offline with @b3a-dev :
- added Hubble/Hubble Relay (doc is not yet ready however) and assigned  to @errordeveloper
- unassigned @errordeveloper from Kata and assigned it to myself

**Comment by nebril** [comment]
PSA: all the links point to `latest` docs, to make sure that you are validating 1.8 docs, checkout `v1.8` branch locally and run `make live-preview` in `Documentation` dir.

**Comment by nebril** [comment]
Found one small issue in external etcd, fix here: https://github.com/cilium/cilium/pull/11922

**Comment by Rolinh** [comment]
Encountered some issues with the GKE guide, fixes in #11960.

**Comment by gandro** [comment]
Hit #11428 while testing AKS as well. Does not look like a regression though, i.e. I can also see it in 1.7.5, therefore not a release blocker. I'm focusing on for now #12070

**Comment by tklauser** [comment]
Hit #12078 while testing the EKS GSG. Looks like another fallout from the `--devices` change?

**Comment by christarazi** [comment]
Transparent Encryption updates here: https://github.com/cilium/cilium/pull/12088

**Comment by joestringer** [comment]
For the BGP guides, my main focus was whether the guides fail to configure the relevant routing daemons to propagate routes because modulo the route propagation it's mostly just direct-routing which we're testing elsewhere regularly:

* Kube-router worked (configuration correct; peered successfully with a BIRD 1.x instance I ran in a network namespace; configured routes when in overlay mode).
  * Didn't actually validate via routes installed via BGP just because the suggested configuration uses the ipip tunnels and I didn't see a way for BIRD to autoconfigure these in the same way that kube-router does.
  * Instead I turned off the overlay mode and relied on direct routing; I didn't see kube-router install routes in that case but the connectivity worked as expected.
* BIRD guide: I installed bird2 and configured it using the specified config, following the instructions to substitute some peers. I peered it with an adjacent kube-router instance and observed peering / route export from bird and import into the kube-router.
  * Given that the guide is mostly about BIRD configuration, I mainly focused on that.
  * If there is any connectivity issue with this path, I would assume we pick it up in any of our direct-routing configurations.

PR to improve demonstrating that BIRD works:
https://github.com/cilium/cilium/pull/12092

**Comment by gandro** [comment]
kube-proxy free kubeadm only required one small note: #12095

**Comment by errordeveloper** [comment]
So for it looks like 1.8.0-rc3 is broken in Azure, the main symptom is that CoreDNS sees a CNI error `empty cidrs`. The issue was already fixed in https://github.com/cilium/cilium/pull/11978, but it was merged after rc3 and still carries `needs-backport/1.8` label.

**Comment by aanm** [comment]
Unable to deploy Cilium on GKE for clustermesh setup (which requires etcd):
```
helm install cilium ./cilium \
  --namespace cilium \
  --set global.cluster.name=cluster1 \
  --set global.cluster.id=1 \
  --set global.etcd.enabled=true \
  --set global.etcd.managed=true \
  --set agent.image=quay.io/aanm/cilium:v1.8.0-rc3-with-allocator-panic \
  --set global.nodeinit.enabled=true \
  --set nodeinit.reconfigureKubelet=true \
  --set nodeinit.removeCbrBridge=true \
  --set global.cni.binPath=/home/kubernetes/bin \
  --set global.gke.enabled=true \
  --set config.ipam=kubernetes \
  --set global.native-routing-cidr=$NATIVE_CIDR
```

(The image is build on top of 1.8.0 with the fix from https://github.com/cilium/cilium/pull/12101)

**Comment by errordeveloper** [comment]
I can confirm that overall Azure guide is working, I've opened https://github.com/cilium/cilium/pull/12108 with a few cosmetic improvements.
One thing I'm still debugging is Hubble UI, will report back once I conclude what's going on.

**Comment by errordeveloper** [comment]
Looks like I've encountered https://github.com/cilium/hubble/issues/180.

**Comment by errordeveloper** [comment]
I've just looked back at connectivity test, and looks like it's actually broken:
```
echo-a-558b9b6dc4-pmsh8                                  1/1     Running            0          5h23m
echo-b-59d5ff8b98-r4hx8                                  1/1     Running            0          5h23m
echo-b-host-f4bd98474-rbpgz                              1/1     Running            0          5h23m
host-to-b-multi-node-clusterip-7bb8b4f964-qgsf6          1/1     Running            48         5h23m
host-to-b-multi-node-headless-5c5676647b-56xbt           1/1     Running            48         5h23m
pod-to-a-646cccc5df-t8blr                                0/1     CrashLoopBackOff   95         5h23m
pod-to-a-allowed-cnp-56f4cfd999-fnppn                    0/1     CrashLoopBackOff   93         5h23m
pod-to-a-external-1111-7c5c99c6d9-gnmfk                  1/1     Running            0          5h23m
pod-to-a-l3-denied-cnp-5dc8d69b7f-q4nvb                  1/1     Running            0          5h23m
pod-to-b-intra-node-b9454c7c6-sc9lq                      0/1     CrashLoopBackOff   93         5h23m
pod-to-b-intra-node-nodeport-6cc56666dc-tmqt9            0/1     CrashLoopBackOff   94         5h23m
pod-to-b-multi-node-clusterip-754d5ff9d-9gzwg            0/1     CrashLoopBackOff   93         5h23m
pod-to-b-multi-node-headless-7876749b84-sz4zz            1/1     Running            44         5h23m
pod-to-b-multi-node-nodeport-6d8fc65c99-ld8hv            0/1     Running            94         5h23m
pod-to-external-fqdn-allow-google-cnp-6478db9cd9-d74xk   0/1     Running            94         5h23m
```
I notice some of the pods didn't come up initially, but was looking into #12070 at the time. As @gandro pointed out, this #11428 is a thing.

**Comment by errordeveloper** [comment]
What's interesting is that in AKS `KUBERNETES_SERVICE_HOST` is set to a service IP in `default` namespace, but in `kube-system` the `.azmk8s.io` domain name is used. I create `test` namespace, and notice that there service IP was used also. I assume AKS does this as a way to get around bootstrap issues for system components, namely this way `kube-proxy` doesn't need to run in order for pods to access the API server. Clever, yet a bit confusing.

**Comment by errordeveloper** [comment]
Moving Azure discussion to https://github.com/cilium/cilium/issues/12113.

**Comment by errordeveloper** [comment]
I've testing Hubble on GKE, and it appears to work overall, but here a few issues I've identified:
- https://github.com/cilium/cilium/issues/12152
- https://github.com/cilium/cilium/issues/12154
