### ISSUE TITLE
Port DNS proxy bootstrap optimizations to master and v1.8

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#12794]
DNS proxy bootstrap optimizations were developed on v1.7 to streamline [v1.7.7 release](https://github.com/cilium/cilium/releases/tag/v1.7.7) process. Port these first to master and then backport to v1.8:

- [x] DNS Proxy is started earlier in the Cilium agent bootstrap to make it available to running endpoints sooner. ([#12718](https://github.com/cilium/cilium/pull/12718))
- [x] fqdn/dnsproxy: set SO_REUSEPORT on listening socket ([#12728](https://github.com/cilium/cilium/pull/12728))
- [x] dnsproxy: Use restored Endpoints before Endpoints are available ([#12731](https://github.com/cilium/cilium/pull/12731))
- [ ] Extend FQDN test to validate DNS proxy during restart ([#12739](https://github.com/cilium/cilium/pull/12739))

**NOTE: [v1.7.7 release](https://github.com/cilium/cilium/releases/tag/v1.7.7) has also some other PRs that were not backported, maybe some of these need to be forward-ported as well:**

- [ ] install/kubernetes: re-add removed permissions from clusterrole ([#12720](https://github.com/cilium/cilium/pull/12720))
- [ ] ipcache: Fix unit test flake ([#12734](https://github.com/cilium/cilium/pull/12734))
- [ ] etcd: Disable heartbeat quorum check by default ([#12755](https://github.com/cilium/cilium/pull/12755))
- [x] test/bpf: use nproc --all instead of nproc -all ([#12401](https://github.com/cilium/cilium/pull/12401))

**Comment by tklauser** [comment]
> * [ ]  fqdn/dnsproxy: set SO_REUSEPORT on listening socket (#12728)

Sent #12801

> * [ ]  test/bpf: use nproc --all instead of nproc -all (#12401)

This one was fixing an issue that existed only on `v1.7` and crept in when #12121 was backported in #12363 (see https://github.com/cilium/cilium/pull/12363#pullrequestreview-442283315). Thus, no need to forward-port, it's already correct on `master`:

https://github.com/cilium/cilium/blob/fecd5bcca8f688fadab576a243b24bb5fe2cbfbf/test/bpf/Makefile#L6

and on `v1.8`:

https://github.com/cilium/cilium/blob/f033c9056948897b111cdfae5e85da3e339490a3/test/bpf/Makefile#L6

**Comment by joestringer** [comment]
@jrajahalme Given the unchecked boxes, I'm unclear as to whether we have forward-ported all of the relevant logic. Are there remaining items for v1.9 ?

**Comment by joestringer** [comment]
@jrajahalme are there still followup items here?
