### ISSUE TITLE
Remove iptables / netfilter dependency

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12879]
The vast majority of functionality in Cilium is already eBPF-native, with just a few corner cases still depending upon iptables per the references below. Note that even when Cilium no longer requires to install rules to implement functionality for itself, it is possible that in certain integration scenarios, some rules may still be necessary to ensure that other software does not interfere with Cilium's management of traffic.

This is a tracking issue for the remaining items for removing netfilter usage entirely from Cilium when running on a new enough kernel. See the links below for more details.

* [ ] Identify host traffic:  https://github.com/cilium/cilium/issues/8911
* [ ] Implement `xt_socket` in eBPF: https://github.com/cilium/cilium/issues/9921
* [ ] Ensure correct routing in multi-home environments like when handling inbound traffic to an EKS cluster.
   * Related PR for equivalent iptables rules: https://github.com/cilium/cilium/pull/12770#issue-462862976
* [ ] ztunnel

**Comment by aditighag** [comment]
What about the Encryption use case where we use skb mark to decide if a packet needs to be encrypted/decrypted?

**Comment by joestringer** [comment]
> What about the Encryption use case where we use skb mark to decide if a packet needs to be encrypted/decrypted?

We aren't using iptables rules specifically to apply such logic, rather the iptables rules which relate to encryption are there to avoid other iptables logic from running:

```
$ git grep -i encrypt pkg/datapath/iptables/
pkg/datapath/iptables/iptables.go:      matchFromIPSecEncrypt := fmt.Sprintf("%#08x/%#08x", linux_defaults.RouteMarkDecrypt, linux_defaults.RouteMarkMask)
pkg/datapath/iptables/iptables.go:      matchFromIPSecDecrypt := fmt.Sprintf("%#08x/%#08x", linux_defaults.RouteMarkEncrypt, linux_defaults.RouteMarkMask)
pkg/datapath/iptables/iptables.go:              "-m", "mark", "!", "--mark", matchFromIPSecEncrypt, // Don't match ipsec traffic
pkg/datapath/iptables/iptables.go:      matchFromIPSecEncrypt := fmt.Sprintf("%#08x/%#08x", linux_defaults.RouteMarkDecrypt, linux_defaults.RouteMarkMask)
pkg/datapath/iptables/iptables.go:      matchFromIPSecDecrypt := fmt.Sprintf("%#08x/%#08x", linux_defaults.RouteMarkEncrypt, linux_defaults.RouteMarkMask)
pkg/datapath/iptables/iptables.go:      for _, match := range []string{matchFromIPSecDecrypt, matchFromIPSecEncrypt} {
pkg/datapath/iptables/iptables.go:// This avoids encryption bits and keyID, 0x*d00 for decryption
pkg/datapath/iptables/iptables.go:// and 0x*e00 for encryption, colliding with existing rules. Needed
pkg/datapath/iptables/iptables.go:              matchFromIPSecEncrypt := fmt.Sprintf("%#08x/%#08x", linux_defaults.RouteMarkDecrypt, linux_defaults.RouteMarkMask)
pkg/datapath/iptables/iptables.go:              matchFromIPSecDecrypt := fmt.Sprintf("%#08x/%#08x", linux_defaults.RouteMarkEncrypt, linux_defaults.RouteMarkMask)
pkg/datapath/iptables/iptables.go:                      "-m", "mark", "--mark", matchFromIPSecEncrypt,
```

First few cases are item 1 in the description, rules to identify host traffic. The remaining ones are NOTRACK/ACCEPT rules to hide the encryption traffic from other rules (such as masquerade logic).

If we were to compile netfilter entirely out of the node, then these rules could go away and I believe encryption should still work using the combination of BPF logic and routing table configuration.

**Comment by aditighag** [comment]
You are right. These rules are added using policy based routing.

```
1:	from all fwmark 0xd00/0xf00 lookup 200
1:	from all fwmark 0xe00/0xf00 lookup 200
```

**Comment by ammarzuberi** [comment]
Is this still a valid ticket or can this be closed now? Looks like iptables modules were removed from default builds in most recent distro versions which causes somewhat older versions of Cilium to fail to start. I think the code loading the ip_tables module has been removed in newer versions of Cilium but I'm not sure if there's still a hidden dependency here.

**Comment by joestringer** [comment]
What removal are you referring to? As far as I know the ticket is valid and items listed in the issue description are still pending.

**Comment by HadrienPatte** [comment]
Note: The ztunnel implementation seems to currently require iptables: https://github.com/cilium/cilium/blob/main/pkg/ztunnel/iptables/inpod.go

**Comment by chattytak** [comment]
On RHEL10 and Enterprise Linux family (Alma Linux/Rocky Linux) with Minimal Install, the iptables kernel module is not installed by default.
Therefore, I encountered various issues mentioned in this issue.
Since it's still a while before cilium no longer depends on iptables, if you're using RHEL10, you can avoid issues by installing the iptables kernel module with the following command and then rebooting.

```
sudo dnf install -y kernel-modules-extra
sudo reboot
```
