### ISSUE TITLE
follow-up todos for maglev

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#13138]
**RELEASE BLOCKERS**

@brb 
- [x] Add benchmarking test for `maglev.GetLookupTable()` and optimize the function.
- [x] Simplify `maglev.GetLookupTable()` as per https://github.com/cilium/cilium/pull/13131#discussion_r486194807.
- [x] Preallocate UpsertService buffer (https://github.com/cilium/cilium/pull/13131#discussion_r495756883).
- [x] perf & implementation quality of hash for agent
  - compare against siphash 2-4 wrt performance
  - have native implementation of hash alg and remove vendoring
- [x] Add `cilium bpf lb maglev get $SVC_ID`.
- [x] #13224

@borkmann 

- [x] Alias all `--node-port-*` agent flags to a better name if they are not strictly tied to node-port only (https://github.com/cilium/cilium/pull/13131#discussion_r485921007)
- [x] Remove old k8s srv disable flag https://github.com/cilium/cilium/blob/28d9889795e41026bf5ecd29c069f7b73bdd20f5/daemon/cmd/daemon_main.go#L334-L336
- [x] Rename Helm options for LB
- [x]  openapi capital spelling on nodeport options in general (cilium/cilium#13131 (comment)).

**1.10 or 1.9 best-effort**

@brb:
- [x] OpenOrCreateUnpinned -> CreateUnpinned (https://github.com/cilium/cilium/pull/13131#discussion_r486705953).
- [x] Add struct for args of `pkg/maps/lbmap.go:UpsertService()`.
- [ ] Potentially missing bits from https://github.com/cilium/cilium/pull/13189
- [ ] Extend `test_maglev()`: ~1) remove a non-selected pod and check that the same backend is selected~ (EDIT: 1) is flaky due the possible 1% changes in the backends configuration) 2) remove the selected backend and check that different backend is selected. 

@borkmann:
- [x] Kernel: implement flexible max_elems for arraymap so htab can have flexible sized inner map (this can then be realised via Cilium-specific service annotations)
- [x] Maglev nodeport test also for XDP layer (https://github.com/cilium/cilium/pull/13847)

@brb / @borkmann:
- [ ] migrate from single slot / u16*N value size to 4 backends per slot with max_elems of N/4
- [ ] Implement annotations for defining M: https://github.com/cilium/cilium/issues/14396
- [x] #13261
- [x] https://github.com/cilium/cilium/issues/13839
- [ ] pretty print maglev map
- [ ] Doc update to state testing on little-endian nodes
- [x] Strategy for draining old backends (https://github.com/cilium/cilium/issues/10217, also check upstream k8s)
- [ ] Reduce nodeport from warn to info when kernel not newest
- [x] annotation for snat/dsr for specific services

**Comment by joestringer** [comment]
@brb to follow up to determine which of these items should block the v1.9 release vs. which ones should not.

**Comment by borkmann** [comment]
Unmarked from release-blocker given https://github.com/cilium/cilium/pull/13821 is out and the rest in here are best-effort and can land in later 1.9 or 1.10.

**Comment by gaffneyd4** [comment]
Can the task `Strategy for draining old backends` be marked as complete by [this PR](https://github.com/cilium/cilium/pull/17716)?

If so to clarify, does this mean that for those using `bpf-lb-algorithm: maglev`, these issues ([10217](https://github.com/cilium/cilium/issues/10217)), ([14844](https://github.com/cilium/cilium/issues/14844)) are solved as of v1.11?

**Comment by brb** [comment]
> Can the task Strategy for draining old backends be marked as complete by https://github.com/cilium/cilium/pull/17716?

cc @aditighag
