### ISSUE TITLE
Native redirect follow-ups 

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#13294]
This is a placeholder bug for all the pending issues/TODOs -

v1.9:
Items with linked PRs are currently in review.

- [X] Add feature flag and warn when sk_lookup_* are not available (#13671)
- [X] Disable clusterwide LRP related processing (#13671)
- [X] Service translation caused loops in kiam like use cases (#13287)
- [X] Monitor health status of backend pods and update service entries (#13168) 
- [X] End-to-end CI tests (#13360)
- [X] Unit tests for LRP manager (#13362)
- [X] K8s service sync (#13274, #13362)
- [X] Update GSG with motivations, run-time behavior (#13362 , #13543)
- [X] Leftover nits from #12831 (#13362)

Nice to have in v1.9 (but not a blocker):
- [X] CLI to dump entries (#13156)

Future release:
- [ ] Backend update handling (#12859)
- [ ] LRP updates and status
- [ ] Asynchronous watcher callbacks
- [ ] Race conditions in getting pod from the pod store
- [ ] Extend BPF loop fix for IPv6
- [ ] Extend CI test

**Comment by aditighag** [comment]
Reopening the placeholder bug. Please don't close it.

**Comment by brb** [comment]
@aditighag I assume this issue is still relevant?

**Comment by aditighag** [comment]
@brb Yes, thank you. It's mainly a placeholder bug.

**Comment by pchaigno** [comment]
@aditighag I've removed the `priority/release-blocker` label since AFAICS the release-blocking items have been addressed. Please `release-blocker/v1.x` label if I'm wrong.

**Comment by joestringer** [comment]
Hi @aditighag , @Weil0ng are there any active plans to address any of the "future release" checkboxes at this point?

I seem to recall a conversation with @aditighag around Clusterwide LRP where I came to the conclusion that it's not necessary (since the nice thing about clusterwide is it crosses namespaces, but LRP is 1:1 with a pod that it is targeting).

There's actually still some remaining references to clusterwide LRP though which we should ideally also remove if we're not planning on adding it:
```
$ git grep -i clusterwide pkg/redirectpolicy/
pkg/redirectpolicy/redirectpolicy.go:// The namespace check isn't applicable for clusterwide LRPs.
```

**Comment by joestringer** [comment]
Maybe a different take on the same question: This feature is [marked beta](https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/). Which of those checkboxes do you think are necessary to mark it stable (along with community confirmation that it is good to run in production)?

**Comment by aditighag** [comment]
> Maybe a different take on the same question: This feature is [marked beta](https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/). Which of those checkboxes do you think are necessary to mark it stable (along with community confirmation that it is good to run in production)?

I'm planning to fix the following in v1.10 - 

>Asynchronous watcher callbacks
 Race conditions in getting pod from the pod store
