### ISSUE TITLE
RFE: egress nat gateway

### ISSUE THREAD

**Issue by anfernee** [cilium/cilium#13575]
# Proposal / RFE

The proposal is the support egress nat gateway so the egress traffic could have a reliable source IP address. 

The detailed proposal is captured in this doc: https://docs.google.com/document/d/1O0xJLy43KnBBOdjLEM-Xu6KHaRK6lb4kchnJ5nIrPmE/edit#

# PRs
- [x] Add ebpf map cilium_egress_v4 for egress gateway (#14712)
- [x] Support Mixed Mode (tunnel, and direct-routing) (#14723)
  - [ ] Handle MTU adjustment for mixed mode
- [x] Add ebpf datapath for egress gateway (#14830)
- [x] Add CRD for egress gateway (#14998)
- [x] Add watchers and reconcilers for CRD and write them to ebpf map (#15134)
- [x] Add Options (agent options and helm options) and make it visible to users (#15777)
- [x] Add e2e test (#15444)
- [x] Update documentation (TODO)
- [ ] Add cilium bpf egress delete all (TODO)

**Comment by joestringer** [comment]
FWIW, other previous related issues:
* https://github.com/cilium/cilium/issues/9589
* https://github.com/cilium/cilium/issues/13269

**Comment by pchaigno** [comment]
Thanks for adding the list of PRs @anfernee! This will be great to track the high-level overview as we review and merge the PRs :rocket: 

> Add ebpf datapath for egress gateway

I would recommend to send this piece as soon as possible. If we ever run into complexity issues, it will take some time to resolve.

> Support Mixed Mode (tunnel, and direct-routing)

For that item, I suspect it will be as easy as just setting up the `cilium_vxlan` device if tunneling OR egress gateway are enabled.

> Add VIP to gateway mapping

What is this referring to? I assumed the VIP to gateway mapping was already stored in the BPF map.

Is there any of the above PRs which you don't know yet how to approach? We're happy to provide additional pointers into the code if that helps.

**Comment by anfernee** [comment]
> Thanks for adding the list of PRs @anfernee! This will be great to track the high-level overview as we review and merge the PRs 🚀
> 
> > Add ebpf datapath for egress gateway
> 
> I would recommend to send this piece as soon as possible. If we ever run into complexity issues, it will take some time to resolve.
This will come soon. Probably over the weekend. 

> 
> > Support Mixed Mode (tunnel, and direct-routing)
> 
> For that item, I suspect it will be as easy as just setting up the `cilium_vxlan` device if tunneling OR egress gateway are enabled.
Yes, it is. #14723 is a preparation to the change. 

> 
> > Add VIP to gateway mapping
> 
> What is this referring to? I assumed the VIP to gateway mapping was already stored in the BPF map.
Yes, it is. Besides that, on the gateway side, the VIP needs to be programmed on external NIC, so the return traffic knows how to get back. 

> 
> Is there any of the above PRs which you don't know yet how to approach? We're happy to provide additional pointers into the code if that helps.
@MasterZ40 and I have gone through the code base. I think we have a good idea. If we need help, we'll ping you on slack. Thanks for the offer.

**Comment by pchaigno** [comment]
I think we'll also need a Helm flag for the EnableEgressGateway agent flag introduced in https://github.com/cilium/cilium/pull/14723. It's lower priority though.

**Comment by nathanjsweet** [comment]
Have we thought at all about the fact that different cloud providers have built-in egress gateways for their services?

**Comment by oskapt** [comment]
> Have we thought at all about the fact that different cloud providers have built-in egress gateways for their services?

I've thought about it. Some have this, most don't, and it's not available at all in a bare metal or private cloud environment. If you're running services in a cloud provider that has this support (AWS VPC with a NAT gateway, for example), then cool. Same if you're running Istio. But if you're not in that environment and you need this feature, then you still need the feature. It does nothing to say that it's available in a location where your systems are not located.

Even if you are in that environment, it doesn't preclude the need to control where in the _Kubernetes_ cluster the traffic exits to the LAN in general. It's a perfect use case for the CNI to handle.

**Comment by MasterZ40** [comment]
Originating  from https://github.com/cilium/cilium/pull/15134#issuecomment-806281492

Here are the list of items we are planning to improve on the egress nat control plane post v1.10:

- [ ] Collate lower level error cases and log msgs to give user a clearer messaging. (addressed)
- [ ] Combine similar logic and data structure for EgressNATPolicy and LocalRedirectPolicy
- [ ] Add unit tests for egresspolicymanager callbacks
- [ ] Investigate and possibly switch to endpoint watcher callbacks to avoid watching for pod data globally and improve on scaling performance.

**Comment by pchaigno** [comment]
We're still missing the end-to-end tests, so not stale.

**Comment by jibi** [comment]
Since we now have e2e tests, maybe worth closing this and tracking individual remaining tasks? (Also not sure we really need `bpf egress delete all`)
