### ISSUE TITLE
Validate guides for 1.9 release

### ISSUE THREAD

**Issue by b3a-dev** [cilium/cilium#13627]
- **Managed k8s**
  - [x] [EKS](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/k8s-install-eks/) (@nathanjsweet )
  - [x] [GKE](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/k8s-install-gke/) (@ti-mo ) ~#13645~
  - [x] [AKS](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/k8s-install-aks/) (@twpayne ) ~#13632~

- **Self-managed**
  - [x] [Quick-install](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/k8s-install-default/) (@Rolinh )
  - [x] [w/ external etcd](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/k8s-install-external-etcd/) (@fristonio ) ~#13651~ 
  - [x] [Azure Cloud](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/k8s-install-azure/#) (@jrajahalme ) #13714 keep in beta
  - [x] [Openshift](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/k8s-install-openshift-okd/#k8s-install-openshift-okd) (@michi-covalent )  ~#13713~ 

- **Guides**
  - [x] [Kubernetes without kube-proxy](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/kubeproxy-free/) (@pchaigno ) ~#13692~
  - [x] ~XDP on GKE~ (@gandro ) - Still not supported ~#13665~
  - [x] [XDP on Azure](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/kubeproxy-free/#nodeport-xdp-on-azure) (@tklauser )  ~#13674~, ~#13685~
  - [x] [Clustermesh on GKE](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/clustermesh/) (@nathanjsweet   / @aanm ) #13740 
  - [x] [Transparent encryption](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/encryption/) (@kkourt )  ~#13662~  #13663 
  - [x] [Host Firewall](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/host-firewall/) (@qmonnet )  ~#13673~
  - [x] [Bandwidth Manager](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/bandwidth-manager/) (@jrfastab )
  - [x] [Local Redirect Policy](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/local-redirect-policy/) (@nebril ) ~#13737~ ~#13741~ 
  - [x] [Istio guide](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/istio/) (@nebril )
  - [x] [CNI chaining - Calico](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/cni-chaining-calico/#calico) (@tklauser )

- **Monitoring**
  - [x] [Metrics/Grafana](https://docs.cilium.io/en/v1.9.0-rc2/operations/metrics/) (@twpayne ) ~#13668~
  - [x] Troubleshooting with [Hubble](https://docs.cilium.io/en/stable/troubleshooting/#observing-flows-with-hubble)/[HubbleRelay](https://docs.cilium.io/en/stable/troubleshooting/#observing-flows-with-hubble-relay) (@tklauser )
    - Only minor issues found: ~#13644~

- **Other Orchestrators**
  - [x] [Docker](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/docker/) (@jibi  ) ~#13695~

**Comment by joestringer** [comment]
FYI I have disabled the "v1.9" branch docs for now in favor of the "v1.9.0-rc2" docs. Please follow the docs from here:

https://docs.cilium.io/en/v1.9.0-rc2/

**Comment by ti-mo** [comment]
GKE instructions seem solid, everything works as expected. Addresses some nits in https://github.com/cilium/cilium/pull/13645.

(I can't update the issue description..)

**Comment by michi-covalent** [comment]
having trouble running `openshift-install`:
```
% ./openshift-install create install-config --dir "${CLUSTER_NAME}" --log-level debug
DEBUG OpenShift Installer 4.5.0-0.okd-2020-10-15-235428
DEBUG Built from commit 63200c80c431b8dbaa06c0cc13282d819bd7e5f8
DEBUG Fetching Install Config...
DEBUG Loading Install Config...
DEBUG   Loading SSH Key...
DEBUG   Loading Base Domain...
DEBUG     Loading Platform...
DEBUG   Loading Cluster Name...
DEBUG     Loading Base Domain...
DEBUG     Loading Platform...
DEBUG   Loading Pull Secret...
DEBUG   Loading Platform...
DEBUG   Fetching SSH Key...
DEBUG   Generating SSH Key...
? SSH Public Key /path/to/id_rsa.pub
DEBUG   Fetching Base Domain...
DEBUG     Fetching Platform...
DEBUG     Generating Platform...
? Platform gcp
INFO Credentials loaded from environment variable "GOOGLE_CREDENTIALS", file "/path/to/key.json"
? Region us-central1
DEBUG   Generating Base Domain...
FATAL failed to fetch Install Config: failed to fetch dependency of "Install Config": failed to generate asset "Base Domain": could not retrieve base domains: googleapi: Error 400: Invalid resource field value in the request., invalidParameter
```
- i found https://github.com/openshift/installer/issues/4232 from @errordeveloper , which kind of seems related, but not sure what the fix was. 
- also https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/k8s-install-openshift-okd/#k8s-install-openshift-okd  uses `GOOGLE_APPLICATION_CREDENTIALS` instead of `GOOGLE_CREDENTIALS`. are they both supposed to work?

**Comment by aditighag** [comment]
@nebril Please hold off on testing the Local Redirect Policy guide until #13543 is merged.

**Comment by nathanjsweet** [comment]
EKS is looking good.

**Comment by kkourt** [comment]
Some issues with transparent encryption:

### Failure to autodetect interface

Using:
```
$ helm install cilium cilium/cilium --version 1.9.0-rc2 --namespace kube-system --set encryption.enabled=true --set encryption.nodeEncryption=false
```

Failed. 

The problem seemed to be with cilium guess the interface wrong:
```
...
level=info msg="  --encrypt-interface='eth0'" subsys=daemon
...
level=warning msg="Device \"eth0\" does not exist." subsys=datapath-loader
```

There was no `eth0` interface on the machine, and specifying the interface  `--set encryption.interface=ens4` seems to solve the issue.

The guide states the following:

> If direct routing is being used, an additional argument can be used to identify
> the network-facing interface. If no interface is specified, the default route
> link is chosen by inspecting the routing tables.

Which might be interpreted so that it means that the interface can only be set when using direct routing. 

An attempt to clarify this can be found in: https://github.com/cilium/cilium/pull/13660

Long term, we might want to improve the interface detection.

### nodeEncryption=true does not seem to work

Specifying ``--set encryption.nodeEncryption=true`` results in k8s nodes being unreachable (Unable to ping them) which causes issues (e.g., pods cannot terminate). Not clear what is wrong in this case. No relevant errors/warnings in cilium logs.

Some info that might be useful:
```
kkourt@t1:~$ ip r
default via 10.172.0.1 dev ens4 proto dhcp src 10.172.15.198 metric 100 
10.0.0.0/24 via 10.0.0.26 dev cilium_host src 10.0.0.26 mtu 1333 
10.0.0.26 dev cilium_host scope link 
10.0.1.0/24 via 10.0.0.26 dev cilium_host src 10.0.0.26 mtu 1333 
10.172.0.1 dev ens4 proto dhcp scope link src 10.172.15.198 metric 100 
10.172.15.199 dev cilium_host proto eigrp mtu 1333 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
kkourt@t1:~$ ip route get 10.172.15.199
10.172.15.199 dev cilium_host src 10.172.15.198 uid 1001 
    cache mtu 1333 
kkourt@t1:~$ ping 10.172.15.199
PING 10.172.15.199 (10.172.15.199) 56(84) bytes of data.
^C
--- 10.172.15.199 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1036ms
````

**Comment by pchaigno** [comment]
@kkourt Could you open dedicated issues for:

> There was no eth0 interface on the machine, and specifying the interface --set encryption.interface=ens4 seems to solve the issue.

and 

> Specifying --set encryption.nodeEncryption=true results in k8s nodes being unreachable (e.g., unable to ping them, rendered unavailable). Not clear what is wrong in this case. No relevant errors/warnings in cilium logs.

**Comment by kkourt** [comment]
> @kkourt Could you open dedicated issues for:

Sure.

> 
> > There was no eth0 interface on the machine, and specifying the interface --set encryption.interface=ens4 seems to solve the issue.

https://github.com/cilium/cilium/issues/13662

> 
> and
> 
> > Specifying --set encryption.nodeEncryption=true results in k8s nodes being unreachable (e.g., unable to ping them, rendered unavailable). Not clear what is wrong in this case. No relevant errors/warnings in cilium logs.

https://github.com/cilium/cilium/issues/13663

**Comment by Rolinh** [comment]
The quick install guide is fine. While validating it, I noticed that we sometimes refer to slack by using `Slack channel`, which leads to [the glossary page](https://docs.cilium.io/en/v1.9.0-rc2/glossary/#term-slack-channel) when clicked (note: it's not really obvious that the element is clickable) and sometimes by providing a link with anchor to [the help page](https://docs.cilium.io/en/v1.9.0-rc2/gettinghelp/#slack). We should probably strive for more consistency.

**Comment by nebril** [comment]
Got some CRD and Ingress api version deprecation  warnings when running `./cilium-istioctl manifest apply -y` , looks like istio deployed correctly, but process exited with an error:
```
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition (repeated 1 times)

Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress (repeated 1 times)
```

I think this is fine, but wanted to put this out there.

As a side note, `minikube start` uses `docker` backend by default, do we want to add `virtualbox` backend option to the docs? I had some issues with image downloads from within the docker node, not sure if that's just my setup though.

Small nitpick - "Copy All" button copies brackets with preceding backslash, which causes the script to fail - this happens on zsh only, not in bash, or when pasting into vim.

```
for service in ratings-v1 reviews-v2; do \
      kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.9.0-rc2/examples/kubernetes-istio/bookinfo-${service}.yaml ; done
```

Last one is this error message an expected one at the end of step 5?
```
[2020-10-21 13:09:03,955] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$)
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'responses': Error reading field 'partition_responses': Error reading field 'record_set': Bytes size -1 cannot be negative
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:73)
        at org.apache.kafka.clients.NetworkClient.parseResponse(NetworkClient.java:380)
        at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:449)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:269)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:232)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1031)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:979)
        at kafka.consumer.NewShinyConsumer.receive(BaseConsumer.scala:100)
        at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:120)
        at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:75)
        at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:50)
        at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
```

**Comment by pchaigno** [comment]
I was able to validate the kube-proxy-free guide until the advanced section works as expected. I'm planning to send a PR with a couple nits and a few bigger changes as RFC. I'll try to go over the advanced sections before the end of the week.

**Comment by tklauser** [comment]
XDP NodePort successfully validated on Azure AKS using the changes in #13685:

<details>

  ```
$ kubectl -n kube-system exec -it cilium-79pkp -- cilium status --verbose
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.18 (v1.18.8) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumLocalRedirectPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [eth0 (Direct Routing)]
Cilium:                 Ok       OK
NodeMonitor:            Listening for events on 4 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 3/31 allocated, 
Allocated addresses:
  10.240.0.38 (health)
  10.240.0.59 (router)
  10.240.0.63 (kube-system/coredns-8bbb65c89-pl99p)
BandwidthManager:    Disabled
Masquerading:        Disabled
Controller Status:   21/21 healthy
  Name                                  Last success   Last error   Count   Message
  cilium-health-ep                      32s ago        never        0       no error   
  dns-garbage-collector-job             38s ago        never        0       no error   
  endpoint-1931-regeneration-recovery   never          never        0       no error   
  endpoint-2455-regeneration-recovery   never          never        0       no error   
  endpoint-2716-regeneration-recovery   never          never        0       no error   
  k8s-heartbeat                         8s ago         never        0       no error   
  mark-k8s-node-as-available            3m33s ago      never        0       no error   
  metricsmap-bpf-prom-sync              3s ago         never        0       no error   
  resolve-identity-1931                 3m30s ago      never        0       no error   
  resolve-identity-2455                 3m32s ago      never        0       no error   
  resolve-identity-2716                 3m33s ago      never        0       no error   
  sync-endpoints-and-host-ips           33s ago        never        0       no error   
  sync-lb-maps-with-k8s-services        3m33s ago      never        0       no error   
  sync-policymap-1931                   28s ago        never        0       no error   
  sync-policymap-2455                   30s ago        never        0       no error   
  sync-policymap-2716                   31s ago        never        0       no error   
  sync-to-k8s-ciliumendpoint (1931)     10s ago        never        0       no error   
  sync-to-k8s-ciliumendpoint (2455)     12s ago        never        0       no error   
  sync-to-k8s-ciliumendpoint (2716)     3s ago         never        0       no error   
  template-dir-watcher                  never          never        0       no error   
  update-k8s-node-annotations           3m37s ago      never        0       no error   
Proxy Status:   OK, ip 10.240.0.59, 0 redirects active on ports 10000-20000
Hubble:         Ok   Current/Max Flows: 442/4096 (10.79%), Flows/s: 2.11   Metrics: Disabled
KubeProxyReplacement Details:
  Status:              Strict
  Protocols:           TCP, UDP
  Devices:             eth0 (Direct Routing)
  Mode:                Hybrid
  Backend Selection:   Random
  Session Affinity:    Enabled
  XDP Acceleration:    Native
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767) 
  - LoadBalancer:   Enabled 
  - externalIPs:    Enabled 
  - HostPort:       Enabled
BPF Maps:   dynamic sizing: on (ratio: 0.002500)
  Name                          Size
  Non-TCP connection tracking   73648
  TCP connection tracking       147297
  Endpoint policy               65535
  Events                        4
  IP cache                      512000
  IP masquerading agent         16384
  IPv4 fragmentation            8192
  IPv4 service                  65536
  IPv6 service                  65536
  IPv4 service backend          65536
  IPv6 service backend          65536
  IPv4 service reverse NAT      65536
  IPv6 service reverse NAT      65536
  Metrics                       1024
  NAT                           147297
  Neighbor table                147297
  Global policy                 16384
  Per endpoint policy           65536
  Session affinity              65536
  Signal                        4
  Sockmap                       65535
  Sock reverse NAT              73648
  Tunnel                        65536
Cluster health:                                   2/2 reachable   (2020-10-21T22:07:37Z)
  Name                                            IP              Node        Endpoints
  aks-nodepool1-37024845-vmss000001 (localhost)   10.240.0.35     reachable   reachable
  aks-nodepool1-37024845-vmss000000               10.240.0.4      reachable   reachable
```
</details>

**Comment by jibi** [comment]
Docker guide successfully validated :heavy_check_mark: (I don't seem to be able to update the issue)
Just a couple of small nits addressed here https://github.com/cilium/cilium/pull/13695

**Comment by errordeveloper** [comment]
@michi-covalent I'll follow-up with you on slack

**Comment by michi-covalent** [comment]
@errordeveloper thanks for your help, i managed to create an openshift cluster 💯 . a couple of notes:

- probably better to use `GOOGLE_CREDENTIALS` instead of `GOOGLE_APPLICATION_CREDENTIALS`. with `GOOGLE_CREDENTIALS`, i see an info log like this:
  ```
  INFO Credentials loaded from environment variable "GOOGLE_CREDENTIALS", file ...
  ```
it doesn't show up if i use `GOOGLE_APPLICATION_CREDENTIALS`.
- another link i found useful for configuring gcp service account is https://github.com/openshift/installer/blob/master/docs/user/gcp/iam.md initially i didn't assign any roles and wasn't sure what this error meant:
  ```
   FATAL failed to fetch Install Config: failed to fetch dependency of "Install Config": failed to generate asset "Base Domain": could not retrieve base domains: googleapi: Error 400: Invalid resource field value in the request., invalidParameter
   ```

**Comment by michi-covalent** [comment]
opened https://github.com/cilium/cilium/pull/13713 for some minor modifications for openshift gsg. well done @errordeveloper i don't know how you figured out all these steps 💯 🚀

**Comment by nathanjsweet** [comment]
I did a multi-regional deployment in GKE to test cluster-mesh. One of the things that I ran into is that I needed to turn "global access" on manually for the internal loadbalancers for etcd ala [this guide](https://cloud.google.com/load-balancing/docs/internal/setting-up-internal#ilb-global-access). I filed [this issue](https://github.com/cilium/cilium/issues/13740) for us to fix it.
