### ISSUE TITLE
v1.9.0 release tracker

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13712]
* [x] Feature freeze
* [x] Merge feature freeze exceptions
* [x] Evaluate which [release blockers] we intend to address in release timeframe
* [x] Branch for release
* [x] Tag a release candidate and provide docs branch for GSG testing ([v1.9.0-rc2])
* [x] Validate the getting started guides (#13627)
* [x] Complete all [release blockers]
* [x] Ensure that [v1.9 CI jobs] are stable
* [x] Prepare release blog

[release blockers]: https://github.com/cilium/cilium/labels/priority%2Frelease-blocker
[v1.9 CI jobs]: https://jenkins.cilium.io/view/Cilium-v1.9/
[v1.9.0-rc2]: https://docs.cilium.io/en/v1.9.0-rc2/
