### ISSUE TITLE
Kubernetes integration

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#14239]
- [x] **Update libraries, docs and code to 1.20**. assignee @aanm PR https://github.com/cilium/cilium/pull/14248
- [x] **Increment minimal supported version to 1.16**. assignee @aanm PR https://github.com/cilium/cilium/pull/15502

List of features not currently implemented:

- [x] **Pod-startup liveness-probe hold-off (stable)**: https://github.com/cilium/cilium/issues/14342
- [ ] **Add support for podCIDR in k8s netpol**:
  - Cilium [GH-9209](https://github.com/cilium/cilium/issues/9209)
  - Requires datapath support first.

- [ ] **Dual stack support (alpha)**:
  - Add support for multiple clusterIPs (it's currently part of the service spec in 1.20). The clusterIPs could be v4 or v6, and a "ipFamilies" field specifies the preference. [
  - Related https://github.com/cilium/cilium/issues/13074
  - Assignee @fristonio

- [x] **Endpoint slices (beta - enabled by default):**
  - Deprecated the usage of `sub.Topology["kubernetes.io/hostname"]` with `sub.NodeName` on our side.
  - Affects scalability. Would we benefit in policies from this?

- [ ] **Endpoint slices (alpha)**  [requires triage]:
  - Implement `serving` and `terminating` behaviors. TL;DR an endpoint will have `terminating` set to true which requires that "new" connections won't be loadbalanced to it but existing connections still need to be redirected to that endpoint. [Full KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1672-tracking-terminating-endpoints)
  - Related https://github.com/cilium/cilium/pull/13943

- [x] **Optionally disable NodePorts for Service Type=LoadBalancer (alpha feature)**: https://github.com/cilium/cilium/issues/14343

- [ ] **Priority and fairness for API server requests (beta - enabled by default)** (low priority):
  - Priority and fairness for API server requests made by the pod. 
  - [Full KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1040-priority-and-fairness), [GH-issue](https://github.com/kubernetes/enhancements/issues/1040)
  - Allows us to prioritize any kind of request to the apiserver. We should look to see if we would need this feature in Cilium.

- [ ] **Support of mixed protocols in Services with type=LoadBalancer (stable)** (low priority):
  - Self-explanatory, [KEP](https://github.com/kubernetes/enhancements/issues/1435)
  - Depends on https://github.com/cilium/cilium/pull/13980. 
    - Issue with above PR: LB keys change which are used in the NodePort lookup, existing connections may drop. Mitigation is to have a fallback legacy mode. 

- [ ] **Add default values in CRDs (stable)** [requires triage if we need it] (low priority):  
  - [KEP](https://github.com/kubernetes/enhancements/issues/1929)
  - We currently don't have a requirement for default values, but it may be helpful in some cases.

- [ ] **SCTP support (stable)** (low priority):
  - Cilium [GH-5719](https://github.com/cilium/cilium/issues/5719)
  - [KEP](https://github.com/kubernetes/enhancements/issues/614)

- [ ] **Clean ups / enhancements**:  (good-first-issue)
  - Remove InitContainers usage from the slim pod; go through the slim API structs to ensure we don't have unused structs.

- [ ] **Kubernetes service finalizer**
  - This feature ensures the Service resource is not fully deleted until the correlating load balancer resources are deleted.
[https://github.com/kubernetes/kubernetes/pull/78262]
  - We may not need to implement this.

- [ ] **Port Ranges**: https://github.com/cilium/cilium/issues/16622

**Comment by christarazi** [comment]
> Kubernetes service finalizer
> This feature ensures the Service resource is not fully deleted until the correlating load balancer resources are deleted.
> [https://github.com/kubernetes/kubernetes/pull/78262]

@aditighag Are you planning to look into this?

**Comment by aditighag** [comment]
> > Kubernetes service finalizer
> > This feature ensures the Service resource is not fully deleted until the correlating load balancer resources are deleted.
> > [https://github.com/[kubernetes/kubernetes/pull/78262](https://github.com/kubernetes/kubernetes/pull/78262)]
> 
> @aditighag Are you planning to look into this?

I'm not sure we need it at the moment.

**Comment by acim** [comment]
Is the latest Cilium functional on 1.20 at all?

**Comment by olemarkus** [comment]
for what it is worth, the kOps e2e tests pass with Cilium.

**Comment by pchaigno** [comment]
> Is the latest Cilium functional on 1.20 at all?

Master (`:latest`) works with 1.20, but not the latest stable (`:1.9.4`). The latest stable [only supports Kubernetes 1.12 to 1.19](https://docs.cilium.io/en/stable/concepts/kubernetes/compatibility/#k8scompatibility).

**Comment by acim** [comment]
> > Is the latest Cilium functional on 1.20 at all?
> 
> Master (`:latest`) works with 1.20, but not the latest stable (`:1.9.4`). The latest stable [only supports Kubernetes 1.12 to 1.19](https://docs.cilium.io/en/stable/concepts/kubernetes/compatibility/#k8scompatibility).

But as far I can see, there are no images of the master branch on quay.io/cilium. Neither for operator nor for cilium. It would be nice to have latest or some testing or whatever tag for the master branch based image.

**Comment by olemarkus** [comment]
"Supported" and "functional" are two different things, I guess. As mentioned, it does pass conformance, but there may be 1.20 features not supported by cilium. I can imagine especially things related to the kube-proxy replacement.

Would be good to have an idea of what is actually failing.

**Comment by aanm** [comment]
All `:latest` tags were transferred to `quay.io/cilium/*-ci:latest` to make it explicit the `*-ci` repositories are not meant to use by any production systems. We only use them for testing in our CI.
