### ISSUE TITLE
k8s: Add support for Egress PodSelector / label-based egress

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1488]
With the addition of `EgressRule`. The `EgressRule` can specify `NetworkPolicyPeer`s.

Parent: https://github.com/cilium/cilium/issues/1489

Currently, Cilium only supports ingress label-based policy. This is because the source endpoint writes its security identity into the packets that it sends to its destination. Since the security identity is an encoding of the set of labels of an endpoint, upon ingress, all the datapath has to do when it receives a packet from an endpoint is check the security identity in the packet against the set of security identities from which traffic is allowed to the destination endpoint. However, upon egress, the cilium-agent on the host sending out packets does not know the set of labels corresponding to the destination endpoint. Consequently, we need a way to determine whether the endpoint to which traffic is being sent from one endpoint is allowed from within the agent based on available metadata in the packet, data from the key-value store, etc. 
 
This ticket requires changes in multiple areas of Cilium, specifically:

- [x] #2552 : Synchronization of endpoint data across the cluster using the key-value store
- [x] #2553 : Changes to the BPF datapath to account for this
- [x] #2556 : Documentation of this functionality
- [x] #2722 : Plumbing of label-based egress policy throughout Cilium
- [x] Add new CRD validation for label-based egress
- [x] CI integration (we test basic datapath functionality, still need nightly tests)
- [x] #3099:  Label-dependent L4 for Egress

**Comment by ianvernon** [comment]
Note - we need to figure out how this works with L3-dependent-L4 as well / associated code-paths. can be done after initial L3-only work is done by restricting L3-dependent L4 egress rules in the API at first.

**Comment by ianvernon** [comment]
Question from discussion with @joestringer  - do we want to have one map in the datapath of IP to allow decision per endpoint, or two maps - IP to security ID, which is global to the daemon, and then a table of egress security IDs per endpoint. The second solution is more memory-efficient, as we only have to contain IP to security ID mappings in one global table, vs. having a list of IPs per endpoint, which could be huge dependent on the number of endpoints in the cluster. The first solution is likely quicker in the datapath as there would only be one table lookup comparing the destination IPs.

**Comment by ianvernon** [comment]
Note: make size of first (global) map configurable (IP to security ID). Cache that is synchronized in the BPF datapath.
On policy generation, for each identity need to list other identities that can be talked to (Consumable). 
Two phase approach is preferable, especially in case of L3-dependent L4. For ingress, key for lookup contains src identity + destination port (L3-dependent L4). If we do the same for egress, this means that the key needs to contain the destination addressing (identity / IP, L4 port). 

Before datapath implementation, addition to the Cilium monitor. Listen to key-value store, build up local cache, transfer IP to identity; allows us to have value from day one.

**Comment by ianvernon** [comment]
Removing best-effort and test-week labels as I think we have sufficient test coverage in C for this, and all of the datapath + agent-based components for egress have been merged and tested. 

I am leaving #2555 and https://github.com/cilium/cilium/issues/3754 open, and am closing this issue accordingly :)
