### ISSUE TITLE
k8s: Add support for new k8s NetworkPolicy EgressRule

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1489]
The following changes have merged beta support for `EgressRules`:
https://github.com/kubernetes/kubernetes/pull/51351/commits/b03302f9055aa9f1b7870e6bc4d8440dc3c4e62c

Tasks:
- [x] Sync k8s vendor to retrieve new beta field definitions
- [x] Parse & validate `EgressRule`

Sub Tickets:
 - [x] Egress CIDR support: https://github.com/cilium/cilium/issues/1487
 - [x] Egress PodSelector https://github.com/cilium/cilium/issues/1488

**Comment by ianvernon** [comment]
`client-go` hasn't merged in these new types yet - latest release is 4.0.0: https://github.com/kubernetes/client-go/releases

We use `client-go` code in `pkg/k8s/network_policy.go` to extract information about network policy - does this mean we have to wait for `client-go` to be updated to make this change?

Also, I noticed in `vendor.conf` that we are using `k8s.io/kubernetes` v1.5.1 - should this be upgraded?
cc: @aanm

**Comment by aanm** [comment]
@ianvernon You can still make the PoC locally with latest of client-go and push it into a `wip` PR. Once there's a stable release of client-go then we can upgrade it.

>Also, I noticed in `vendor.conf` that we are using `k8s.io/kubernetes` v1.5.1 - should this be upgraded?

We can upgrade `k8s.io/kubernetes` to 1.8.0 once it lands but we can start doing a test with 1.8.0.beta1 to see if it breaks anything.

**Comment by ianvernon** [comment]
OK sounds good, I'll do that then. Thanks!

**Comment by ianvernon** [comment]
Per discussion with @tgraf  - we need a more robust dependency management system for Cilium; ref: #1514. I'll get this done first so I can actually get the K8s egress policy changes to compile :)

**Comment by ianvernon** [comment]
@tgraf support for this is merged; other remaining work in #1488 consists of things on the Cilium side like policy trace, CT changes. We support the K8s EgressRule spec now. Can this be closed?

**Comment by ianvernon** [comment]
I am going to close this; we support egress policy at parity with ingress policy; all other issues are tracked separately (policy trace, etc.).
