### ISSUE TITLE
GitHub action CI/CD follow ups

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#14928]
- [x] Use images from quay.io in smoke tests and jenkins @Skymirrh @nebril 
- [x] Clean up images created in the `*-ci` repositories after 1 week. @aanm 
- [ ] Make sure it is possible to restart redo a release in case one of the images fail to build. @aanm 
  - [ ] This can easily be achieved by re-triggering a run on the building process.
- [x] Backport to older branches. @aanm 
- [x] Merge all "operator" dockerfiles into a single one (https://github.com/cilium/cilium/pull/15849)
- [ ] Use github caches to make the builds faster.

**Comment by nebril** [comment]
after #14937 getting merged the only job that uses quay images seems to be upstream tests, the images are being built inside vms. Do we want to touch them @aanm ?

**Comment by aanm** [comment]
> after #14937 getting merged the only job that uses quay images seems to be upstream tests, the images are being built inside vms. Do we want to touch them @aanm ?

@nebril yeah, let's make everything use the images build by GH actions
