### ISSUE TITLE
Enable per-endpoint routes by default

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14955]
Per-endpoint routes (`enable-endpoint-routes`) are currently disabled by default. We want to enable them by default for 1.10, mostly as a workaround for https://github.com/cilium/cilium/issues/10645. This is a meta issue to track progress on that work item.

- [x] Fix VXLAN + per-endpoint routes bug, https://github.com/cilium/cilium/issues/14646 - https://github.com/cilium/cilium/pull/14675
- [x] Fix VXLAN + per-endpoint routes bug v2, https://github.com/cilium/cilium/issues/14657.
- [x] Fix SNAT bypass in IPv6 - https://github.com/cilium/cilium/pull/14913
- [ ] Fix fragment tracking, https://github.com/cilium/cilium/issues/15958.
- [x] Fix reverse DNAT with tunneling and kube-proxy, https://github.com/cilium/cilium/issues/16446.
- [x] Support host firewall with per-endpoint routes, https://github.com/cilium/cilium/issues/13121 - https://github.com/cilium/cilium/pull/15217
- [x] Support BPF host routing with per-endpoint routes, https://github.com/cilium/cilium/issues/14240.
- [ ] Fix ICMPv6 NS drops, https://github.com/cilium/cilium/issues/23852.
- [ ] CI run with per-endpoint routes enabled - https://github.com/cilium/cilium/pull/15057
- [ ] Evaluate performance impact of per-endpoint routes with large number of endpoints on node.
- [ ] Enable by default.
- [ ] Clean up/revert CI code that handles endpoint-routes reconfiguration - See comment in commit in #16767.

**Comment by joestringer** [comment]
Just linking in issue https://github.com/cilium/cilium/issues/16717 here, seemed like a case where if we had a mix of endpoints with endpoint-routes enabled + endpoint-routes disabled, it could cause forwarding issues between the endpoints. One longer-term approach to solving that issue is to support endpoints in different modes concurrently. An alternative approach would be to support endpoint routes with all other configurations and switch to this by default.

**Comment by m-yosefpor** [comment]
are there any plans to have this in 1.13 milestone?

**Comment by pchaigno** [comment]
Hi @m-yosefpor :wave: You should already be able to enable endpoint routes in your cluster if you need it. Or is there a reason you need it to be enabled by default?

**Comment by m-yosefpor** [comment]
Hi @pchaigno . Actually the problem is endpoint routes cannot be enabled together with BPF host routing. Having endpoint routes enabled by default is not our requirement, but one of the items listed here in the check list (https://github.com/cilium/cilium/issues/14240) is essential for us.

**Comment by pchaigno** [comment]
Ok :+1: As far as I know, there are no plans to address https://github.com/cilium/cilium/issues/14240 for v1.12 or v1.13. It's something we'd like to address but it's not prioritized right now.

**Comment by gandro** [comment]
Another discrepancy: https://github.com/cilium/cilium/issues/28812

**Comment by joestringer** [comment]
Just 2c: I think that developers maintaining and reasoning about both `endpoint-routes=true` and `endpoint-routes=false` modes causes an increase in cognitive load when trying to develop changes, which could be reduced if we pick just one option. There are environments that have a hard requirement for `endpoint-routes=true` in order to correctly forward traffic within the node, so we can't remove that option. So that leaves me with the question, can we force all other environments that don't use `endpoint-routes=true` to use this mode and ensure all the paths work correctly for this mode in all circumstances, then eventually remove `endpoint-routes=false`?
