### ISSUE TITLE
Complete packet traces for cilium monitor

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14988]
We have a number of packet traces in our datapath, to be able to track packets as they move between the containers, the outside network, the tunnel, etc. These traces consist of perf events sent to userspace via a ring buffer. They are usually placed on the entry and exit of each BPF programs, to trace e.g. packets leaving for the tunnel or entering the container, or packets coming from the network or the IPSec tunnel.

Unfortunately, because the existing packet traces are neither well documented (https://github.com/cilium/cilium/issues/14885) nor well tested (https://github.com/cilium/cilium/issues/5622), they have started to rot away. Some datapath configurations are missing packet traces (https://github.com/cilium/cilium/issues/14625, https://github.com/cilium/cilium/pull/14696), some traces are misplaced (https://github.com/cilium/cilium/issues/12562), and information (security identities, conntrack state) is missing from many traces.

We have many issues open to track these problems; the present issue serves as a high-level tracker. We should:
- [ ] Define exactly what traces are expected.
- [ ] Add missing traces.
- [ ] Add security identities and conntrack state to existing traces whenever possible.
- [ ] Find a way to test the presence of expected traces (e2e test, Coccinelle check, some sort of BPF unit test?).
