### ISSUE TITLE
Wireguard integration follow-up

### ISSUE THREAD

**Issue by brb** [cilium/cilium#15462]
## v1.10 Must Have

- [x] Add support for managed k8s (requires the Wireguard agent to subscribe to IPCache events). #15674
- [x] CI testing
  - [x] Check that pod2pod is encrypted (run tcpdump in bg) #15573
  - [x] ~Check that KPR fwd path is encrypted (same with tcpdump)~
  - [x] Check that pod2host, host2pod is not interfered.
  - [x] Test with different datapath configuration (per-endpoint routes).
- [x] Add probes for Wireguard.
- [x] MTU detection #16020 
- [x] Documentation
  - [x] GSG #15787
  - [x] Kernel requirements #15787
  - [x] Mention about tunneling asymmetry
  - [x] Architecture

## v1.10 Best Effort

- [x] Extend `cilium status` to show whether Wireguard is enabled. #15833
- [x] Support tunneling mode (motivation: we currently encrypt only pod2pod traffic, so host2pod and pod2host might get dropped by an underlying network).
- [x] Friendlier error message when kernel level support is not available. Currently it prints `level=fatal msg="Failed to initialize wireguard agent" error="operation not supported" subsys=daemon` #15825
- [x] ~Clustermesh support~ Already works in 1.10

## v1.11

- [x] Wireguard in user-mode on < 5.4 kernels.

## v1.14

- [x] host2pod, pod2host, host2host encryption (incl. KPR). (https://github.com/cilium/cilium/pull/19401)
- [x] Attach BPF program to direct routing device egress which checks that we don't leak unencrypted pod2pod traffic.
- [x] Support BPF host routing with Wireguard and KPR (https://github.com/cilium/cilium/issues/15075).
- [x] Reject duplicate pub keys in agent code to avoid misconfiguration https://github.com/cilium/cilium/pull/19344
- [x] Support L7 proxy. (https://github.com/cilium/cilium/pull/19401)
- [x] Annotation to allow nodes to opt-out of encryption (https://github.com/cilium/cilium/pull/19401)

**Comment by SHarrySeldon** [comment]
Hey! Any chances that it would be possible to implement Site-to-Site configuration(i.e. other side is on premise VM)? 
It would be useful when running in hybrid configurations.

**Comment by brb** [comment]
@SHarrySeldon Currently, we rely on CiliumNode object to propagate WireGuard endpoint info to other nodes. Cilium already supports external workloads (aka non-cluster hosts): https://docs.cilium.io/en/v1.10/gettingstarted/external-workloads/. The missing bit for your use case is to extend `CiliumExternalWorkload` to support WireGuard metadata and to handle it from the agent. We would accept such a contribution.

**Comment by KyleSanderson** [comment]
hi! any chance at a wireguard gateway for this? what I mean by the request is to send traffic to a non-user hosted gateway, and accept traffic back into the cluster. Mullvad and a couple other providers being the use-case.

**Comment by brb** [comment]
@KyleSanderson That's basically the same as https://github.com/cilium/cilium/issues/15462#issuecomment-947784572. We would consider accepting such a contribution.

**Comment by Rid** [comment]
Is there plans for WireGuard support when using the kube-proxy replacement? or is that referred to as the L7 proxy?

**Comment by v1ctorrhs** [comment]
@brb in which version can we expect #19401  ? Thanks

**Comment by brb** [comment]
@v1ctorrhs v1.13

**Comment by ReillyBrogan** [comment]
So I'm already using KPR with Wireguard on 1.11. As far as I can tell everything is working, is that not supposed to be the case (such as pod2pod traffic not being encrypted)? I'm not using L7 features though.

```
# cilium status
KVStore:                Ok   etcd: 1/1 connected, lease-ID=REMOVED, lock lease-ID=REMOVED, has-quorum=true: https://api.internal.k8s.our.domain:4003 - 3.5.3
Kubernetes:             Ok   1.23 (v1.23.7) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [ens5 10.152.7.27 (Direct Routing)]
Host firewall:          Disabled
Cilium:                 Ok   1.11.4 (v1.11.4-9d25463)
NodeMonitor:            Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 8/254 allocated from 100.96.4.0/24, 
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           BPF   [ens5]   100.96.4.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:      58/58 healthy
Proxy Status:           No managed proxy redirect
Hubble:                 Ok                Current/Max Flows: 4095/4095 (100.00%), Flows/s: 35.46   Metrics: Disabled
Encryption:             Wireguard         [cilium_wg0 (Pubkey: REMOVED, Port: 51871, Peers: 10)]
Cluster health:         11/11 reachable   (2022-06-07T16:41:28Z)
```

**Comment by brb** [comment]
> is that not supposed to be the case (such as pod2pod traffic not being encrypted)?

pod2pod should work. The #19401 brings the encryption for host2host, pod2host and host2pod traffic.

**Comment by carnerito** [comment]
Is it planned for v1.13 to have L7 observability with Wireguard encryption enabled? I couldn't find a GH issue for this.

**Comment by arpagon** [comment]
For now, we are using Cilium + [kilo](https://github.com/squat/kilo/blob/a9d5883a3af2284c30793fe884c676a11df7e1fd/manifests/kilo-k3s-cilium.yaml)

**Comment by brb** [comment]
> Is it planned for v1.13 to have L7 observability with Wireguard encryption enabled

@carnerito Yep, it is.

**Comment by brb** [comment]
Closing, as only one item is left which has an issue (datapath: Support L2-less with fast redirect #15075). cc @gandro

**Comment by ravilr** [comment]
@brb  the issue description needs update to tick mark 
Support BPF host routing with Wireguard and KPR (https://github.com/cilium/cilium/issues/15075) ?  now that it is merged and going to land in v1.14 release ?

Thanks. 🎆 for full feature parity with wireguard encryption.
