### ISSUE TITLE
BGP followups

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#15611]
- [x] Update CODEOWNERS now that we have new packages: https://github.com/cilium/cilium/pull/15663
- [x] Use https://pkg.go.dev/k8s.io/code-generator/cmd/conversion-gen instead of handmade conversion functions
- [x] Refactor consumers from agent K8s watchers by using https://github.com/cilium/cilium/pull/15295: https://github.com/christarazi/cilium/blob/8297e05e22977872eddc5b8ba4f9eac1b2679f6e/pkg/k8s/watchers/service.go#L96
- [x] How can we provide deeper visibility into the state of BGP in Cilium? How can we best allow a user to introspect the state? It can also be helpful for debugging. Context: https://github.com/cilium/cilium/pull/15340#discussion_r605885639
- [x] Add unit / integration tests for BGP manager and speaker: https://github.com/cilium/cilium/pull/15340#discussion_r607226228
- [x] https://github.com/cilium/cilium/pull/15340#discussion_r607247514
  - Considered a requirement to reach "stable" status
- [x] https://github.com/cilium/cilium/pull/15340#discussion_r607290033
- [x] Make PR to cilium-cli: https://github.com/cilium/cilium-cli/pull/159
  - [x] clusterrole changes in Operator
  - [x] BGP configmap
 - [ ] Add concepts docs describing how this feature works overall

**Comment by ldelossa** [comment]
One outstanding item is concept docs. Seeing how the longer-term plan is to move this feature to GoBGP we may want to wait until this migration to cement in the conceptual overview of the feature. Going to close for now, but feel free to open back up if anyone feels my assessment is wrong.
