### ISSUE TITLE
Extend review process and codeowners to satellite repositories

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#15690]
On cilium/cilium we have a well defined process for reviews, based on [the code owners](https://github.com/cilium/cilium/blob/master/CODEOWNERS) and associated GitHub teams. This review process is however currently limited to this repository and doesn't apply to our satellite repositories (e.g., cilium-cli, packer-ci-build, image-tools, etc.). As a consequence, pull requests in satellite repositories tend to be forgotten more easily, with longer periods of time before they are reviewed and merged.

We can easily extend our review process to all repositories by creating a CODEOWNERS file and enabling GitHub load balancing of review requests: 
- [x] [cilium-cli](https://github.com/cilium/cilium-cli) -- https://github.com/cilium/cilium-cli/pull/234
- [x] [packer-ci-build](https://github.com/cilium/packer-ci-build) -- https://github.com/cilium/packer-ci-build/pull/270
- [x] [image-tools](https://github.com/cilium/image-tools) -- https://github.com/cilium/image-tools/pull/120
- [x] [iproute2 fork](https://github.com/cilium/iproute2) -- https://github.com/cilium/iproute2/pull/10
- [x] ~[cilium-sysdump](https://github.com/cilium/cilium-sysdump)~ -- Now part of cilium-cli
- [x] [Hubble](https://github.com/cilium/hubble) -- https://github.com/cilium/hubble/pull/576

I'm unsure if this is needed for Hubble as well, which may already have its own review process? /cc @cilium/hubble 

Please add the list above if you think there are other repositories we should include.

**Comment by gandro** [comment]
My 2 cents: I think it might make sense to have same load-balacning mechanism we have for `cilium/hubble` as well. Right now we have not done it, because overall traffic is low on `cilium/hubble` (it's only a client CLI these days), but if we start doing it for all other sattelite repositories, then I think we should to the same, even if we end up only defining a single `CODEOWNER` for all of `cilium/hubble`.

**Comment by kaworu** [comment]
Added the PR link for Hubble and checked the box as it has been merged. Only cilium-sysdump remaining it seems.

**Comment by joestringer** [comment]
I think we can close this?
