### ISSUE TITLE
expose VXLAN and health ports as a flags

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#15956]
## Proposal / RFE

**Is your feature request related to a problem?**

When deploying Cilium on OpenShift user has to run custom script to modify security groups and enable Cilium ports. This step in the guide is quite error-prone.

OpenShift installer does make the IANA VXLAN port 4789 open, albeit Cilium uses default Linux VXLAN port 8472.

Additionally, having the ability to use a different port would make OpenShift CI setup work out of the box for all providers, presently (https://github.com/openshift/release/pull/17380) Cilium job  is enabled only in Azure (where the NSG rules are more permissive).

Also, the health port 4240 is not settable either, but OpenShift installations usually have ports 9900-9999 open and one of those can should be useable instead of 4240.

**Describe the solution you'd like**

Add a daemon flags and Helm chart values to set VXLAN and health ports, keep the default as is.

**Comment by errordeveloper** [comment]
I am looking into this now, and have a few questions about setup logic.

Having looked at this line here:

https://github.com/cilium/cilium/blob/887659418c56cf9fb5da393c67a50703fd992f55/bpf/init.sh#L431-L434

I am wondering if I have to pass `dstport` parameter as part of `ip link add` invocation, or I can use `ip link set`?

According to [`ip-link(8)`](https://man7.org/linux/man-pages/man8/ip-link.8.html), it seems like `dstport` is only settable in `ip link add` invocation?

**Comment by errordeveloper** [comment]
> According to [`ip-link(8)`](https://man7.org/linux/man-pages/man8/ip-link.8.html), it seems like `dstport` is only settable in an `ip link add` invocation?

Having looked at the source code briefly, it appears that it should be possible to use `up link set`.

**Comment by errordeveloper** [comment]
### TODOs

- [ ] add a flag for VXLAN port (https://github.com/cilium/cilium/pull/16874)
- [ ] add a flag for health port
- [ ] update OKD guide & OLM manifests
- [ ] update OpenShift CI pipeline, add new jobs

**Comment by brb** [comment]
@errordeveloper Do you want to get this into v1.11? If not, then please remove the v1.11 related labels which I've added.

**Comment by errordeveloper** [comment]
@brb I very much would like to get this into 1.11, both PRs are just blocked by CI flakes...

**Comment by borkmann** [comment]
> ### TODOs
> * [x]  add a flag for VXLAN port ([datapath: Add a flag to set VXLAN and Geneve ports #16874](https://github.com/cilium/cilium/pull/16874))
> * [x]  add a flag for health port ([health: Add flag to set HTTP port #16926](https://github.com/cilium/cilium/pull/16926))
> * [x]  update OKD guide & OLM manifests ([docs: Remove firewall hack for OKD GSG #17924](https://github.com/cilium/cilium/pull/17924) & [cilium/cilium-olm@5fa5c16](https://github.com/cilium/cilium-olm/commit/5fa5c16))
> * [ ]  update OpenShift CI pipeline, add new jobs
> * [ ]  document that it's not recommended to change `--tunnel-port` in existing clusters due disruption in connectivity

@errordeveloper Did you follow-up with the small doc change? Just wondering if we can close this blocker issue here.

**Comment by errordeveloper** [comment]
> > ### TODOs
> > * [x]  add a flag for VXLAN port ([datapath: Add a flag to set VXLAN and Geneve ports #16874](https://github.com/cilium/cilium/pull/16874))
> > * [x]  add a flag for health port ([health: Add flag to set HTTP port #16926](https://github.com/cilium/cilium/pull/16926))
> > * [x]  update OKD guide & OLM manifests ([docs: Remove firewall hack for OKD GSG #17924](https://github.com/cilium/cilium/pull/17924) & [cilium/cilium-olm@5fa5c16](https://github.com/cilium/cilium-olm/commit/5fa5c16))
> > * [ ]  update OpenShift CI pipeline, add new jobs
> > * [ ]  document that it's not recommended to change `--tunnel-port` in existing clusters due disruption in connectivity
> 
> @errordeveloper Did you follow-up with the small doc change? Just wondering if we can close this blocker issue here.

@borkmann no, I haven't yet updated the docs regarding downtime on flag change... Maybe blocking label can be removed now?

**Comment by borkmann** [comment]
[...]
> @borkmann no, I haven't yet updated the docs regarding downtime on flag change... Maybe blocking label can be removed now?

Ok, given it's just a small paragraph, do you have a chance to send the doc PR? Would be great if we could close/finalize this one here.

**Comment by errordeveloper** [comment]
> [...]
> > @borkmann no, I haven't yet updated the docs regarding downtime on flag change... Maybe blocking label can be removed now?
> 
> Ok, given it's just a small paragraph, do you have a chance to send the doc PR? Would be great if we could close/finalize this one here.

Yeah, will try to do it in the next few days!

**Comment by borkmann** [comment]
> Yeah, will try to do it in the next few days!

Awesome, thanks Ilya!
