### ISSUE TITLE
cilium: next xdp improvements, tracker ticket

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#1690]
- [ ] Trace events to perf RB for sampling (would probably require faster exporter?)
- [ ] Tunnel secctx extraction and lookup
- [ ] Prog regeneration on the fly -> compile in/out LPM
- [ ] Enable LPM when duming prefixes works form kernel
- [ ] Plugin framework
- [ ] Probe whether prefix is blocked or not via http api (aka ip route get test ;))?
- [ ] Add host IP from `--prefilter-device` to EP map if not already done.
