### ISSUE TITLE
Implementation of eBPF Unit Testing Framework & Tests

### ISSUE THREAD

**Issue by xinyuanzzz** [cilium/cilium#16951]
Using this issue to track Implementing eBPF Unit Testing Framework. It is planned in the following PRs.

- [x] The base infrastructure [ebpf unit testing #16862](https://github.com/cilium/cilium/pull/16862)
- [x] Handles tailcalls and supports user-space map emulation [ebpf unit testing -- handle tailcalls and support user-space map emulation #17114](https://github.com/cilium/cilium/pull/17114)
- [ ] snat_v4_process test [ebpf unit testing -- snat_v4_process test #17147](https://github.com/cilium/cilium/pull/17147) 
- [ ] sock tests [ebpf unit testing -- sock tests #17227](https://github.com/cilium/cilium/pull/17227)
- [ ] lxc tests [ebpf unit testing -- lxc tests #17245](https://github.com/cilium/cilium/pull/17245)

**Comment by brb** [comment]
Are you folks still planning to work on these issues? JFYI during the v1.13 dev cycle we are going to invest into https://github.com/cilium/cilium/issues/14990, so maybe we could close this issue?

**Comment by Weil0ng** [comment]
I think this is of a low priority from our side now, let's close this and see if #14990 provides better coverage.
