### ISSUE TITLE
Fix issues found during review of policy resolution

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#1706]
- [x] Merging of L7 rules not working as intended: #1705 
- [x] `allowsL4Egress()`, `allowsL4Ingress()` are eating errors passed up from mergeL4Port() (Also #1705)
- [x] mergeL4Port() will skip merging L4 policies with L7 Kafka rules if the existing policy allows traffic from any endpoints (see `len(r.Rules.HTTP)`): #1719 
- [x] If an ingress rule is added with L4-only policy first, then with L3-dependent L4 policy, it fails (nil dereference)
- [x] Improve unit test coverage of the above

From slack:
```
@tgraf:
So I think we have 3 L4 rule types:
1. l4 rule with no l7 rules (all l7 is allowed)
2. l4 rule with empty l7 rules (no l7 is allowed)
3. l4 rule with some l7 rules (set of l7 is allowed)
```

For the last item above of improving unit test coverage, we should try different combinations of the above and check that the combinations work as expected.
