### ISSUE TITLE
Use one Cilium CA instead of two different CAs for Hubble and ClusterMesh

### ISSUE THREAD

**Issue by kaworu** [cilium/cilium#18278]
## Problem

Until now, when using the "auto" method for certificate generation, both the helm and certgen methods would generate different CAs for Hubble and ClusterMesh (stored in the `hubble-ca-secret` and `clustermesh-apiserver-ca-cert` secrets, respectively), see [here](https://github.com/cilium/cilium/blob/386029bb42155b37b425edd20f2e02f5ba0be749/install/kubernetes/cilium/templates/hubble/tls-helm/_helpers.tpl) and [here](https://github.com/cilium/cilium/blob/386029bb42155b37b425edd20f2e02f5ba0be749/install/kubernetes/cilium/templates/clustermesh-apiserver/tls-helm/_helpers.tpl) for the helm method. This was done so because one can be enabled without the other.

On the other hand, the [cilium-cli](https://github.com/cilium/cilium-cli) has from the start used a single unique CA for both Hubble and ClusterMesh (stored in the `cilium-ca` secret).

This difference make the cilium-cli slightly incompatible with helm installations and although mixing helm with the cilium-cli is not supported users have been hit by the issue, see https://github.com/cilium/cilium-cli/issues/300 for example.

## Proposal
 Since having different CAs for Hubble and ClusterMesh has not proved useful in practice so far, and that it is still possible to manage certificates in other ways (e.g. manually or through cert-manager), using a single CA for Helm installation seems to be the best approach to solve the problem.

https://github.com/cilium/certgen/pull/41 has more context and bring this change to certgen (thanks to @soggiest!). Here are outlined the steps needed to complete the migration:

- [x] tag a certgen release including https://github.com/cilium/certgen/pull/41 (@gandro)
- [x] patch the helm charts in cilium/cilium for the certgen method using the newly released certgen version and adapting flag usages (since they have changed) https://github.com/cilium/cilium/pull/18607
- [x] patch the helm charts in cilium/cilium for the helm method https://github.com/cilium/cilium/pull/18607
- [x] test that both method work in a way that is compatible with the cilium-cli (e.g. installing via Helm and enable Hubble via the cilium-cli should work) https://github.com/cilium/cilium/pull/18607

**Comment by gandro** [comment]
New certgen release is out https://github.com/cilium/certgen/releases/tag/v0.1.7

**Comment by soggiest** [comment]
Any thoughts on what the Helm chart version should be? Should it stay in 1.11 or go to 1.12?

**Comment by gandro** [comment]
> Any thoughts on what the Helm chart version should be? Should it stay in 1.11 or go to 1.12?

Let's target master (i.e. 1.12) for now. We can always decide to backport later, if needed. https://docs.cilium.io/en/v1.11/contributing/release/backports/#backport-process

**Comment by soggiest** [comment]
Looks like the charts are still 1.11 in master:
https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/Chart.yaml#L5-L6

I'll go ahead and use 1.12.1 for this update.

**Comment by kaworu** [comment]
@soggiest please leave the Chart version as-is, they are updated as part of the release process. The current version in master (i.e. `1.11.90`) is conceptually "pre v1.12".

**Comment by sayboras** [comment]
Seems like no one is actively working on this, I can give it a crack.

**Comment by soggiest** [comment]
Thanks for picking this up.I hadn't had a chance to work on this since the new year. I had ran into an issue trying to get the Helm tls generation code to match how the clilium-cli now generates the CA. Specifically, it was challenging to determine if the user had already specified a CA file to import, if not then it would need to be generated, after which it would need to be used for both Hubble and ClusterMesh. I'll be interested to see what solution you come up with.

**Comment by sayboras** [comment]
:wave:

There is a preview PR here https://github.com/cilium/cilium/pull/18607. While there are a few things I need to tidy/tackly, this PR shows the general approach and direction I am taking. Please feel free to take a look and review, much appreciated.
