### ISSUE TITLE
Migrate over to new Ginkgo CI framework

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1839]
#1733 merges in the base for a new test framework for Cilium. To ensure that the migration to this new framework runs smoothly, there are a variety of tasks to accomplish:

- [x] [Install new dependencies onto Cilium Jenkins slaves](https://github.com/cilium/cilium/issues/1768) 
- [x] [Set up Jenkins job that runs the new tests on a reserved build slave while we are still running with the old bash script framework](https://github.com/cilium/cilium/issues/1840)
- [x] [Validate that existing tests are properly migrated over to have equivalent test coverage](https://github.com/cilium/cilium/issues/1841)
    - [x] Deprecate Runtime bash-script test stage
    - [x] Deprecate Kubernetes bash-script test stage
- [x] [Add test/ directory to be owned by cilium/CI in CODEOWNERS](https://github.com/cilium/cilium/issues/1842)
- [x] Validate log gathering functionality for each test and ensure that logs are available in Jenkins. There should be parity with what exists currently in the Cilium tests
    - [x] #2062 
    - [x] #2026 
- [x] [Update developer documentation that illustrates how to use this new framework](https://github.com/cilium/cilium/issues/1843)
- [x] [Add more logs to each test that illustrate what is going on in (like how `log` function is used in the current bash scripts).](https://github.com/cilium/cilium/issues/1841)
- [x] [Move Vagrant image to a Cilium-managed repository](https://github.com/cilium/cilium/issues/1844)
- [x] [Migrate image `eloycoto/cilium_dependencies:latest` to a Cilium-managed repository](https://github.com/cilium/cilium/issues/2536)
- [x] [Coalesce VM images from existing build / Ginkgo build](https://github.com/cilium/cilium/issues/1956)
- [x] [Add Envoy runtime test stage](https://github.com/cilium/cilium/issues/2252)
- [x] Add GitHub Organization for Cilium that uses ginkgo Jenkinsfile

Discovered issues:
- [x] #1907 
- [x] #2067
- [x] #2066 
- [x] #2065
- [x] #2068
- [x] #2075
- [x] #2077

After migration is complete:

- [ ] Remove Cilium-Ginkgo-Tests-All job
- [x] Update ginkgo.Jenkinsfile to run all Runtime* and K8s* tests and change `Describe` of each test to remove 'Validated' string.
- [x] Remove Cilium-Bash-Tests job and change GitHub settings to not make it a 'Required' job. This is only doable by an administrator of the Cilium GitHub Organization
- [x] [Update documentation to remove old bash-script framework references](https://github.com/cilium/cilium/issues/2546)

**Comment by ianvernon** [comment]
Note: look into whether a single PR can trigger two separate builds (one for bash scripts, one for Ginkgo) - would make migration easier.

**Comment by ianvernon** [comment]
CI has been running exclusively with Ginkgo for some time. Closing.
