### ISSUE TITLE
Ginkgo CI: validate that test coverage is equivalent to old framework and deprecate old bash tests

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1841]
Parent: #1839 

Validate that existing tests are properly migrated over to have equivalent test coverage. 

***Deprecating bash test***:
Once tests have been validated, deprecate the old bash tests by adding a line to the top of the bash test like the following:

```
log "${TEST_NAME} has been deprecated and replaced by test/runtime/connectivity.go"
exit 0
```

***Mark corresponding Ginkgo test as validated***:
Change `Describe` in Ginkgo test corresponding to deprecated Bash test to contain `Validated` string after test type:

```Describe(<test type>Validated<test name>```

for example:
```
Describe("RuntimeValidatedPolicyEnforcement", func() {
```

and

```
 Describe("K8sValidatedPolicyTest", func() {
```

***Tests to migrate over and validate***:

- [x] [run miscellaneous shell-script checker scripts](https://github.com/cilium/cilium/issues/2535)
    - Covered-by: https://github.com/cilium/cilium/pull/2940

Runtime tests:

- [x] 01-ct.sh
    - Validated as having full coverage by: https://github.com/cilium/cilium/issues/2533
    - Deprecated-by: https://github.com/cilium/cilium/pull/2774
- [x] 02-perf.sh
    - This doesn't need to be done as part of this migration. Covered by #2100 for migrating to nightly tests.
- [x] 03-docker.sh
    - Validated as having full coverage by: https://github.com/cilium/cilium/pull/2102
    - Deprecated-by: https://github.com/cilium/cilium/pull/2774
- [x] 05-cni.sh
    - Validated as having full coverage by: https://github.com/cilium/cilium/pull/2618
    - Deprecated-by: https://github.com/cilium/cilium/pull/2618
- [x] 06-lb.sh
    - Validated as having full coverage by: #2059 
    - Deprecated-by: https://github.com/cilium/cilium/pull/2775
- [x] 07-kafka.sh
    - Validated as having full coverage by: #2132 
    - Dreprecated-by: https://github.com/cilium/cilium/pull/2778
- [x] 08-nat46.sh
    - Validated as having full coverage in `test/runtime/Policies.go:It("Test NAT46 connectivity between containers"...` 
    - Deprecated-by: https://github.com/cilium/cilium/pull/2774
- [x] 09-perf-gce.sh
    - per conversation with @aanm , we can keep this as a bash script - does not need to be ported
- [x] [10-proxy.sh](https://github.com/cilium/cilium/issues/2524)
    - Validated as having full coverage by: https://github.com/cilium/cilium/pull/2914
    - Deprecated by: https://github.com/cilium/cilium/pull/2914
- [x] 11-getting-started.sh
    - Validated as having full coverage by: https://github.com/cilium/cilium/issues/2525
    - Deprecated-by: https://github.com/cilium/cilium/pull/2782
- [x] [12-policy-import.sh](https://github.com/cilium/cilium/issues/2526)
    - Validated as having full coverage by: https://github.com/cilium/cilium/pull/2898
    - Deprecated-by: https://github.com/cilium/cilium/pull/2898
- [x] 13-fd-open.sh
    - Validated as having full coverage by: https://github.com/cilium/cilium/pull/2473
    - Deprecated-by: https://github.com/cilium/cilium/pull/2777
- [x] 13-monitor-filtering.sh
    - Validated as having full coverage by: @scanf 
    - Deprecated-by: #2779
- [x] 14-policy-enforcement-docker.sh
    - Validated as having full coverage by: @ianvernon - all 17 test cases in the bash script are covered in `test/runtime/Policies.go`
    - Deprecated-by: https://github.com/cilium/cilium/pull/2776
- [x] [15-check-container-id.sh](https://github.com/cilium/cilium/issues/2527)
    - Validated as having full coverage by: https://github.com/cilium/cilium/pull/2610
    - Deprecated-by: https://github.com/cilium/cilium/pull/2610
- [x] [16-cidr-ingress-policy.sh](https://github.com/cilium/cilium/issues/2528)
    - Validated as having full coverage by: https://github.com/cilium/cilium/pull/2909
    - Deprecated by: https://github.com/cilium/cilium/pull/2909
- [x] 17-cilium_policy-id-remove.sh
    - Validated as having full coverage by: https://github.com/cilium/cilium/pull/2783
    - Deprecated-by: https://github.com/cilium/cilium/pull/2783
- [x] 17-multiple-monitors.sh
    - Validated as having full coverage by: @scanf 
    - Deprecated-by: #2779
- [x] [18-kvstore-fail.sh](https://github.com/cilium/cilium/issues/2530)
    - Deprecated-by: https://github.com/cilium/cilium/pull/2791
- [x] 19-identity-get.sh
    - Validated as having full coverage by: #2474
    - Deprecated-by: https://github.com/cilium/cilium/pull/2474
- [x] [20-cidr-limit.sh](https://github.com/cilium/cilium/issues/2531)
    - Validated as having full coverage by: https://github.com/cilium/cilium/pull/2786
    - Deprecated-by: https://github.com/cilium/cilium/pull/2786
- [x] 21-ct-clean-up.sh
    - Validated as having full coverage by: #2410 
    - Deprecated-by: https://github.com/cilium/cilium/pull/2684
- [x] [20-identity-list.sh](https://github.com/cilium/cilium/issues/2532)
    - Validated as having full coverage by: https://github.com/cilium/cilium/pull/2790
    - Deprecated-by: https://github.com/cilium/cilium/pull/2790
- [x] 96-restore-endpoints.sh
    - Validated as having full coverage by : #2448 
    - Deprecated-by:  #2560 
- [x] 97-clean-leftovers.sh
    - Validated as having full coverage by: initial merge.
    - Deprecated by: #2560 

K8s tests (all have been deprecated):
- [x] 00-gsg-test.sh
    - Validated as having full coverage by: Covered by `test/k8sT/Policies.go:It("Policies"...`
    -  Deprecated-by: https://github.com/cilium/cilium/pull/2723
- [x] [00-setup-kubedns.sh](https://github.com/cilium/cilium/issues/2522)
    - Validated as having full coverage by: #2572 
    - Deprecated-by: https://github.com/cilium/cilium/pull/2723
- [x] [01-guestbook-test.sh](https://github.com/cilium/cilium/issues/2534)
    - Validated as having full coverage by: https://github.com/cilium/cilium/pull/2723
    -  Deprecated-by: https://github.com/cilium/cilium/pull/2723
- [x] 02-cnp-specs.sh
    - Validated as having full coverage by: #2461 
    - Deprecated-by: #2551 
- [x] 03-l7-stresstest.sh
    - Validated as having full coverage by: #2493 
    - Deprecated by: #2551
- [x] 04-toservices-test.sh
    - Fixed by: #2380
    - Deprecated-by: https://github.com/cilium/cilium/pull/2766
- [x] 04-bad-cnp-import.sh
    - Validated as having full coverage by:`test/runtime/Policies.go: It("Handles missing required fields",...`
    - Deprecated-by: https://github.com/cilium/cilium/pull/2766
- [x] 99-restore-state.sh
    - Validated as having fully coverage by: initial merge in `test/runtime/chaos.go` 
    - Deprecated-by: https://github.com/cilium/cilium/pull/2766

**Comment by aalemayhu** [comment]
Went through the monitor test LGTM.

**Comment by ianvernon** [comment]
I have tagged the people whose names appear in `git blame` for each test. This is not a direct assignment for each tagged person to migrate each test. The person(s) tagged should go through the Ginkgo tests and see if the test has been migrated correctly / appropriately or not. If it hasn't, create a GitHub issue. We can then distribute load accordingly. I'm open to other ideas about how to approach this as well.

**Comment by aalemayhu** [comment]
If we move the pull docker images script into the packer script, does that mean it is not fetching the latest images for every full test run? I think it makes more sense to have it in the provision script so we use the latest images.

**Comment by ianvernon** [comment]
@scanf - I'm open to having the script to pull the images as part of the provisioning step. We can periodically update the VMs on Vagrant Cloud to have the latest version of the images if they have changed to increase the throughput of the build as well.

**Comment by ianvernon** [comment]
The merging of https://github.com/cilium/cilium/pull/2940 means that this can be closed :-)
