### ISSUE TITLE
Dynamic Cluster Pool Follow-ups

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#18987]
Tracking issue for the Dynamic Cluster Pool feature

## v1.12 Must Have https://github.com/cilium/cilium/pull/19777

- [x] Address review feedback from https://github.com/cilium/cilium/pull/18887
- [x] Add support for https://github.com/cilium/cilium/pull/18505
- [x] Documentation
- [x] Finalize CRD/API design

## v1.12 Best Effort

- [ ] Support for tunneling mode (requires tunnel map deprecation)
- [ ] Support for IPSec
- [ ] Additional test cases (especially around agent restart)
- [ ] (requires the above) Deprecate cluster-pool-v1
- [ ] Add metrics to track pod IP pressure e.g. via prometheus

## Backlog / Future Milestones

- [ ] Ability to extend global clusterpool via CRDs (instead of static Helm configuration via `ipam.operator.clusterPoolIPv4PodCIDRList`)
- [ ] Ability to configure pod CIDR pool and pod CIDR mask size per node, either via CRD (similar to [KEP-2593](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2593-multiple-cluster-cidrs)) or via node annotation

**Comment by gandro** [comment]
The release blocker label applies only to the "Must Have" items

**Comment by akhilles** [comment]
> Ability to extend global clusterpool via CRDs (instead of static Helm configuration via ipam.operator.clusterPoolIPv4PodCIDRList)

Maybe consider using [`ClusterCIDRConfig`](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2593-multiple-cluster-cidrs#new-resource) objects instead? The KEP was approved and there's a PR to merge the APIs: https://github.com/kubernetes/kubernetes/pull/111123.

**Comment by abasitt** [comment]
"Ability to extend global clusterpool via CRDs", does this item in the backlog means after this is available, I will be able to create additional clusterpool ? e.g. default pool is named default and I can create another pool custom ?. 
What I am looking for is to have the flexibility creating completely different ippool with different names. The IPs from different pool can be controlled via annotations and this will be really important for future policies addons that can be implemented on pool levels. e.g. I want to the pool-A in NAT but pool-B excluded from NAT. I am happy to create a complete feature request for it if it's there yet.

**Comment by gandro** [comment]
Yes, that is the plan. The exact mechanism with how IPs get assigned is yet to be defined (annotations are probably the mechanism we do this initially), but the basic infrastructure to support multiple pools is something I'm currently working on.

**Comment by abasitt** [comment]
Great, thank you.

**Comment by Garagoth** [comment]
Will it be possible to allocate blocks from pools selected via nodeSelector? (see also #13227).
If this mechanism will allow multiple pools to be selected, then nice, we could have both topology based allocation and for example by size. It is fine if node will be able to allocate IPs from multiple pools if necessary, however some kind of limitation/priority or just pool usage balancing would be needed as well I guess so one node will not saturate first pool completely starving other nodes while still having other pools empty...

**Comment by AmourLinux** [comment]
Is this feature still being updated? This feature seems to be deprecated in version 1.14.

**Comment by gandro** [comment]
The feature has been superseeded by multi-pool IPAM, which is a superset of dynamic cluster pool https://docs.cilium.io/en/v1.14/network/concepts/ipam/multi-pool/ It already supports some of the discussed features such as a CRD to define pools. It also allows assigning workload-specific pools.

You can use multi-pool with just a single `default` pool and you will get all the same features that dynamic cluster pool has.

It does not yet support per-node configuration, but that's something were contributions are welcome, c.f. https://github.com/cilium/cilium/issues/27131 for further discussions.

I'm closing this issue as "not planned". For our follow-ups on multi-pool, c.f. https://github.com/cilium/cilium/issues/25470
