### ISSUE TITLE
CI: Conformance testing for Ingress controller

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#19306]
## Description

As mentioned in https://github.com/cilium/cilium/pull/18867, we should address all failure in conformance testing

- features/default_backend.feature  (all passed) :heavy_check_mark: 
- features/host_rules.feature :spinning-gopher: (29 passed, 3 failed, 5 skipped) :negative_squared_cross_mark: 
- features/path_rules.feature (70 passed, 3 failed, 1 skipped) :negative_squared_cross_mark: 
- features/ingress_class.feature (all passed) :heavy_check_mark: 
- features/load_balancing.feature (all passed) :heavy_check_mark: 

<details> 
<summary>host rule failure</summary>

```

Failed steps:

  Scenario: An Ingress with a host rule should not route traffic when hostname does not match # features/host_rules.feature:64
    When I send a "GET" request to "http://subdomain.bar.com" # features/host_rules.feature:67
      Error: Get "http://10.98.35.160/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

  Scenario: An Ingress with a wildcard host rule should send traffic to the matching backend service # features/host_rules.feature:70
    When I send a "GET" request to "http://bar.foo.com" # features/host_rules.feature:73
      Error: Get "http://10.103.158.100/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

  Scenario: An Ingress with a wildcard host rule should not route traffic matching no dns label # features/host_rules.feature:84
    When I send a "GET" request to "http://foo.com" # features/host_rules.feature:87
      Error: Get "http://10.103.107.12/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)


5 scenarios (2 passed, 3 failed)
37 steps (29 passed, 3 failed, 5 skipped)
1m45.93343714s
```

</details>

<details>
<summary>path rule failure</summary>

```
Failed steps:

  Scenario: An Ingress with prefix path rules should match each labels string prefix # features/path_rules.feature:161
    Then the response status-code must be 404 # features/path_rules.feature:165
      Error: expected status code 404 but 200 was returned

  Scenario: An Ingress with mixed path rules should send traffic to the matching backend service where Exact is preferred # features/path_rules.feature:174
    And the response must be served by the "foo-exact" service # features/path_rules.feature:179
      Error: expected the request to be served by foo-exact but it was served by foo-prefix

  Scenario: An Ingress with a trailing slashes in a prefix path rule should ignore the trailing slash and send traffic to the matching backend service # features/path_rules.feature:181
    Then the response status-code must be 200 # features/path_rules.feature:185
      Error: expected status code 200 but 404 was returned


16 scenarios (13 passed, 3 failed)
74 steps (70 passed, 3 failed, 1 skipped)
10m16.97361674s

```

</details>

### TODO

- [x] Address all failure for host rules https://github.com/cilium/cilium/pull/19321
- [x] Address all failure for path rules https://github.com/cilium/cilium/pull/19321
- [x] Enable conformance test as part CI (either via github action or jenkins) done as part of https://github.com/cilium/cilium/pull/19742

**Comment by sayboras** [comment]
### Status

After the PR https://github.com/cilium/cilium/pull/19321, we only have below 2 failures

- features/default_backend.feature (all passed) heavy_check_mark
- features/host_rules.feature 43 steps (42 passed, 1 failed) negative_squared_cross_mark
- features/path_rules.feature :spinning-gopher: 74 steps (73 passed, 1 failed) negative_squared_cross_mark
- features/ingress_class.feature (all passed) heavy_check_mark
- features/load_balancing.feature (all passed) heavy_check_mark

Host Rule test

```
--- Failed steps:

  Scenario: An Ingress with a wildcard host rule should not route traffic matching on more than a single dns label # features/host_rules.feature:78
    Then the response status-code must be 404 # features/host_rules.feature:82
      Error: expected status code 404 but 200 was returned


6 scenarios (5 passed, 1 failed)
43 steps (42 passed, 1 failed)
1m30.9371297s
--- FAIL: TestSuite (90.94s)
    conformance_test.go:136: at least one step/scenario failed

```

Path Rule test
```
--- Failed steps:

  Scenario: An Ingress with mixed path rules should send traffic to the matching backend service where Exact is preferred # features/path_rules.feature:174
    And the response must be served by the "foo-exact" service # features/path_rules.feature:179
      Error: expected the request to be served by foo-exact but it was served by foo-prefix


16 scenarios (15 passed, 1 failed)
74 steps (73 passed, 1 failed)
10m22.185528168s

```

**Comment by sayboras** [comment]
All tests are passing in https://github.com/cilium/cilium/pull/19321

**Comment by sayboras** [comment]
Closed as all items are completed.
