### ISSUE TITLE
Service Mesh follow-ups for release 1.12

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#19312]
- [x] Rebase/merge #18867
- [ ] Write a proper description to #18894, including but not limited to:
  - [ ] limitations, current things that are implemented, envoy resources that can be configured, resources that can't be configured, how this fits into the broader service mesh picture
  - [ ] which components (cilium-agent, cilium-operator, cilium-proxy) are expected to interact with these resources
  - [ ] RBAC
  - [ ] flow of data
- [x] Make sure Helm charts are properly updated so that config overrides are not needed in installation. Done as part of https://github.com/cilium/cilium/pull/18867
- [X] Change CEC and CCEC to be in version `v2` instead of `v2alpha1` as it is for GA in 1.12: #19688
- [x] Add unit/integration/conformance tests @sayboras. Conformance test is added as part of https://github.com/cilium/cilium/pull/19742. Unit tests + Integration tests will be added incrementally. 
- [x] Figure out if we can support CNPs for Cilium Ingress @jrajahalme: #19764
  - [x] Added `reserved:ingress` which is used as the source security ID for Ingress traffic originating from outside of the cluster. Cluster internal sources have their own identities.
- [x] Documentation / Getting Started Guide @sayboras https://github.com/cilium/cilium/pull/19760
- [x] Avoid plain text TLS secret in CEC. Related PR https://github.com/cilium/cilium/pull/19410
- [x] Check on multiple target ports, see https://github.com/cilium/cilium/pull/18867#discussion_r842089317. Related PR https://github.com/cilium/cilium/pull/19647 @sayboras 
- [x] Add requested Envoy extensions to `cilum-envoy` build @jrajahalme: #19764
  - [x] `envoy.filters.http.ext_authz` (https://github.com/cilium/proxy/pull/64)
  - [x] rate limits
  - [x] Check all pull requests on https://github.com/cilium/proxy/pulls

**Comment by sayboras** [comment]
I have moved the below item to #19698, so we can closed out this issue, and continue the work from #19698 

> Write a proper description to https://github.com/cilium/cilium/pull/18894
