### ISSUE TITLE
Expose runtime metrics for use in monitoring system

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1935]
Endpoint management:
 - [x] Number of endpoints being managed
 - [x] Number of endpoints currently being regenerated
 - [x] Total number of endpoints regenerations
 - [x] Endpoint regeneration errors

Policy:
 - [x] Number of policies loaded
 - [x] Current policy revision
 - [x] Number of policy loaded that cannot be enforced

Cluster Nodes:
 - [ ] List of all known nodes
   - [ ] Node IPs

Endpoint:
 - [ ] List of all local endpoints
 - [ ] Label on endpoint to link to security identity
 - [ ] Datapath metrics
    - [ ] Number of policy denies to this endpoint
    - [ ] Number of packets/bytes to this endpoint

Security identity:
 - [ ] List of all security identities
    - [ ] Number of endpoints that belong to identity

Datapath:
 - [ ] Total number of packets dropped
 - [ ] Total number of policy volations
   - [ ] L3
   - [ ] L4
   - [ ] L7
 - [ ] Total number of packets forwarded
 - [ ] Total number of bytes forwarded
 - [ ] Packets/Bytes from/to security identity

Proxy/L7:
 - [ ] Number of requests served
 - [ ] Histogram/summary bytes served

Kubernetes
 - [x] Timestamp of last event received
 - [ ] Total number of policies received
 - [ ] Total number of services received

Container runtime
 - [ ] Timestamp of last event received
