### ISSUE TITLE
BGP Control Plane Follow Ups

### ISSUE THREAD

**Issue by ldelossa** [cilium/cilium#19376]
Issue tracks follow-ups to the merge of #18860 

# TODO

- [ ] Server-side filtering of "Node SharedInformer" such that only the local node is cached/listed/watched. cc @aanm 
- [ ] Tune back "relist" interval for generated shared informers cc @aanm 
- [x] Support passwords for peering https://github.com/cilium/cilium/issues/19376#issuecomment-1095561850
- [x] Move to `CiliumNode` object, this was not possible due to labels cc @christarazi 
- [ ] Discuss whether to continue instantiating shared informers or fall back to K8sWatchers patterns cc @christarazi @aanm 
- [ ] Split "user facing" Sphinx docs and "developer phasing" markdown docs in such a way that maintaing both is not a burden. cc @qmonnet 
- [x] Implement graceful restart cc @YutaroHayakawa 
- [ ] Revisit conditions where a BGP server recreation is necessary https://github.com/cilium/cilium/pull/18860#discussion_r829723477 cc @YutaroHayakawa 
- [x] Better operational state visibility https://github.com/cilium/cilium/pull/18860#issuecomment-1085787248 cc @YutaroHayakawa 
- [ ] Consider auto-gen of router ID in IPv6 single stack, consider cluster-wide router-id IPAM https://github.com/cilium/cilium/pull/18860#discussion_r847265513 cc @arianvp

**Comment by YutaroHayakawa** [comment]
I think we need one more follow-up item. Making better operation visibility.

https://github.com/cilium/cilium/pull/18860#issuecomment-1085787248

**Comment by arianvp** [comment]
I'm missing an option to set an password for peering. 

Another thing that is not clear to me is if  service CIDR advertisements is implemented yet. I assume not because there is only a node-local agent implemented so far?

**Comment by ldelossa** [comment]
@arianvp Do you mean the advertisement of LoadBalancer IPs via BGP?

**Comment by camrossi** [comment]
I am also working on integration Cilium with BGP and I am having a few issues:

- Can't set a password for the peering as said by @arianvp 
- I am not sure how I advertise LoadBalancer IPs via BGP
- The documentation is contradicting itself: in https://github.com/cilium/cilium/tree/master/pkg/bgpv1 is stated:
  `Only a single CiliumBGPPeeringPolicy can apply to a Cilium node.`
and then in https://github.com/cilium/cilium/tree/master/pkg/bgpv1#virtual-router-attributes
`A CiliumBGPPeeringPolicy can apply to multiple nodes.`
- I want to peer each Cilium node to two switches for redundancy. I did it like this and is working. This is not documented specifically but I guess is fine?
```
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: rack2
  namespace: kube-system
spec:
 nodeSelector:
   matchLabels:
     rack_id: "2"
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 65003
   exportPodCIDR: true
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: "192.168.11.203/32"
      peerASN: 65002
    - peerAddress: "192.168.11.204/32"
      peerASN: 65002
```
- Only 1 node is advertising the POD CIDR and it advertising the /24 POD CIDR but not the /27 POD subnets that I allocate to the nodes:

```
kubectl  describe node | grep ipv4-pod-cidr
                    io.cilium.network.ipv4-pod-cidr: 192.168.12.160/27
                    io.cilium.network.ipv4-pod-cidr: 192.168.12.64/27
                    io.cilium.network.ipv4-pod-cidr: 192.168.12.96/27
                    io.cilium.network.ipv4-pod-cidr: 192.168.12.0/27
                    io.cilium.network.ipv4-pod-cidr: 192.168.12.128/27
                    io.cilium.network.ipv4-pod-cidr: 192.168.12.32/27
```

For example:

```
Leaf201# show ip route vrf  Cilium:Cilium 192.168.12.0
192.168.12.0/24, ubest/mbest: 1/0
    *via 192.168.11.1%Cilium:Cilium, [20/0], 00:13:05, bgp-65002, external, tag 65003
         recursive next hop: 192.168.11.1/32%Cilium:Cilium

Leaf201# show ip route vrf  Cilium:Cilium 192.168.12.0/27
Route not found
```
I was expecting to get the /27, before I tested with the "old" BGP feature (the on in beta) and it did export the /27

my Cilium config is like this:

```
# CiliumBGPPeeringPolicy CRDs.
bgpControlPlane:
  enabled: true

ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: ["192.168.12.0/24"]
    clusterPoolIPv4MaskSize: 27
```

Also more in general, if I am looking to create a configuration best practice for Cilium and BGP should I focus on this new implementation ? Seems to me this is the way forward? But I would like to be certain.

**Comment by camrossi** [comment]
> @camrossi  it's not a contradiction. Just a one to many relation
> 
> 
> 
> each node can only have one policy that applies, but one policy can be applied to many nodes (through the nodeSelector)

Oh right ! My bad misunderstood that 😊

**Comment by ldelossa** [comment]
@arianvp @camrossi 

The advertisement of LoadBalancer IPs is not implemented in this yet. This was answered answered in your review comment @arianvp on the original BGP Control Plane PR. 

Keep an eye out for this, we will be implementing it over the next few weeks. 

Password support can be patched in sooner then this.

**Comment by camrossi** [comment]
Thabk you @ldelossa ! 

What about the POD CIDR advertisement? 

Since I'm looking to write an integration guide would you recommend I wait for this feature or look into the other options (Bird/Kube-Router)? I prefer to pick the feature that will be the best one even if it takes a bit longer 😀

**Comment by camrossi** [comment]
> @camrossi PodCIDR advertisements are indeed implemented.

Yes but I'm getting only 1 node advertising the POD CIDR as a whole /24 in my case.
However each node gets a /27 allocated and that is not advertised.

I put my config and the routes I received in my first message. Let me know if you need more information

**Comment by arianvp** [comment]
My suggestion for the password would be to add a `secretKeyRef` to point to a kubernetes secret

```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: rack2
  namespace: kube-system
spec:
 nodeSelector:
   matchLabels:
     rack_id: "2"
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 65003
   exportPodCIDR: true
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: "192.168.11.203/32"
      peerASN: 65002
      peerPassword:
        secretKeyRef:
          name: bgp-password
          key: password
```

**Comment by joestringer** [comment]
per @arianvp 's suggestion, cross-linking this question I had on the watcher initialization code: https://github.com/cilium/cilium/pull/18860#discussion_r876184907

**Comment by nbusseneau** [comment]
@ldelossa Should we add #23765 to the list up top?

**Comment by YutaroHayakawa** [comment]
This issue is outdated. Most of the follow-up items are no longer relevant. Let me close this now.
