### ISSUE TITLE
bugtool - tool to capture node/system information

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1942]
A tool that users can run to capture system/node information:

- [x] Research if we can leverage one of the existing tools. A lot of distros have tools that implement a subset of what we need

- [x] Complete the existing tool or provide a new tool which gathers:
  - [x] Cilium version
  - [x] kernel version
  - [x] Cilium status
  - [x] Logs (cilium, cilium-docker)
  - [x] Dumps of:
    - [x] endpoint list
    - [x] endpoint get for each endpoint
    - [x] service list
    - [x] policy get
    - [x] bpf * list
    - [x] Copy of `/var/run/cilium/state/`
  - [x] System information
    - [x] hostname
    - [x] `ip a`
    - [x] `ip r`
    - [x] `ip link`
    - [x] `iptables-save`
    - [x] `uname`
    - [x] `uptime`
    - [x] `dmesg`
    - [x] `ethtool`
   - [x] System files:
     - [x] `/etc/resolv.conf`
     - [x] `/boot/config-xxxx` (kernel config)
  - [x] Kubernetes
     - [x] Logs
     - [x] `kubectl -n kube-system get pods`
     - [x] `kubectl get pods,svc` for all namespaces

**Comment by joestringer** [comment]
A couple of extra suggestions:
- [ ] Everything under `/var/run/cilium/state/`
* If kubectl exists:
  - [ ] kubectl -n kube-system get pods

**Comment by ianvernon** [comment]
We should dump every CLI command if possible; can't hurt to have more information. This also will reveal gaps / bugs in CLI commands.

**Comment by ianvernon** [comment]
Furthermore, this should be integrated into the CI:
- [ ] Run this tool in the CI and provide the artifact it generates as something that can be picked up as part of each Jenkins run

**Comment by manalibhutiyani** [comment]
Another addition needed here:
- [x] New Cilium API for getting debug information

**Comment by aalemayhu** [comment]
After searching found `ovs-bugtool` and `xen-bugtool` but no distribution-specific tool. Have an implementation but missing the dumps, kubernetes details and the logs. Will have an RFC on this soon.
