### ISSUE TITLE
Measure performance baselines

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1946]
- [ ] TCP_STREAM and TCP_RR
 - [ ] No policy
 - [ ] L3 policy
 - [ ] L4 policy (1, 100, 10K alllowed ports)
 - [ ] L7 policy (1, 100, 10K policy rules)
   - [ ] HTTP
     - [ ] Envoy
        - [ ] HTTP/1
        - [ ] HTTP2/
        - [ ] w/ TLS
     - [ ] Oxy
        - [ ] HTTP/1
        - [ ] HTTP/2
   - [ ] Kafka
     - [ ] Go based
     - [ ] kernel based

**Comment by tgraf** [comment]
Stale
