### ISSUE TITLE
Proposal: Network fabric connectivity debugging tool

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1947]
**Goal**
  Tool which allows to track and troubleshoot connectivity issues quickly

**Design**
* [x] New agent `cilium-health` which serves as both client and server.
  * [x] client mode: `cilium-health`
  * [x] server mode: `cilium-health --daemon [--interval=60] [--cilium-sock=...]`
    * [x] Serve on Unix socket
    * [x] Serve on HTTP socket(s)
  * [x] IPv6 Support
  * [x] Extend Cilium API to fetch required information
    * [x] Provide access to list of nodes in cluster
* [x] Offers an HTTP API:
  * [x] `GET /status`: Returns connectivity status to all other cilium health instances based on interval based probing.
     * _detailed response structure below_
  * [x] `GET /status/probe`: Runs a synchronous probe and returns the status of the probe
  * [x] `GET /healthz`: Returns current health:
     * [x] uptime
     * [x] local agent status
     * [x] current system load
  * [x] The REST API is being served on multiple ports simultaneously. Depending on the port number, the packets take different datapath routes:
   * [x] `4240`: routed with no policy applied
     * ~~`4241`: routed with L7 policy applied~~
     * ~~`4242`: routed via L4 service redirection~~
     * ~~`4243`: routed via service redirection + l7 policy applied~~
* [x] `cilium-health` agent runs on each node as:
   * [x] separate container represented as regular endpoint and thus simulating a local endpoint
   * [x] local process in the init namespace thus simulating a local non containerized process
* [x] Update documentation (troubleshooting) guide
* [x] Remove unimplemented portions of the API
* [x] Add ginkgo tests

**Response structure:**
```golang
type HealthResponse struct {
    uptime time.Duration // time.Since(startTime)
    agentStatus api.StatusResponse // https://github.com/cilium/cilium/blob/master/api/v1/models/status_response.go
    load Load // https://stackoverflow.com/questions/11356330/getting-cpu-usage-with-golang
```

```golang
type StatusResponse struct {
    Nodes map[string]NodeStatus // map indexed by node name
}

type ConnectivityStatus struct {
    Latency time.Duration // round trip time in msec
    Error string // Error string or ""
}

type NodeStatus struct {
    ICMP ConnectivityStatus // ping to NodeIP
    HostProcess ConnectivityPaths // GET /status to health ports on NodeIP
    SimulatedEndpoint ConnectivityPaths // GET /status to health endpoint IP of node
}

type ConnectivityPaths struct {
   Base ConnectivityStatus // no policy
   ViaL7Policy ConnectivityStatus // via proxy (l7 policy)
   ViaService ConnectivityStatus // via service redirect
   ViaServicePolicy ConnectivityStatus // via service redirect and proxy
}
```

Open Questions:
* Add connectivty path with and without L3/L4 policy? Likely to require running the health API on multiple IPs and not just multiple ports.

**Comment by aanm** [comment]
My only concern, and if I understood it correctly, with this is having n^n health checks where n is the number of agents running.

Can't we leverage the KVStore to store the data of each agent? Thus, whenever the user does `GET /status` in one of the nodes, the node would fetch the data from the KVStore.

**Comment by joestringer** [comment]
@aanm There are two parts to this: The node health status, and the connectivity status between that node and other nodes. Are you suggesting each node reports its health status into the KVStore?

For the connectivity status between each pair of nodes, I think the initial target is a tool you can run manually on one node to understand its connectivity to other nodes in the fabric, in which case it's a one-off n-query check. However, yes, if you wanted to build a full picture across the cluster, you would have to send probes between each pair of nodes. The point of this test is to run traffic that is fairly similar to actual traffic, and ideally running across the same codepaths and physical paths so that we get a good sense for how actual traffic is handled.

**Comment by aanm** [comment]
This is in the proposal:

> GET /status: Returns connectivity status to all other cilium health instances based on interval based probing.

>Are you suggesting each node reports its health status into the KVStore?

Yes, from the proposal it seems that each node will keep the state of every other node.

>For the connectivity status between each pair of nodes, I think the initial target is a tool you can run manually on one node to understand its connectivity to other nodes in the fabric, in which case it's a one-off n-query check

Super fine with that, just to point out an usability aspect, create a function to check between a node to `--all` or a node to other node, sometimes it's useful to check only 2 nodes :-)

**Comment by tgraf** [comment]
> Yes, from the proposal it seems that each node will keep the state of every other node.

That is correct and intentional. Storing the state in a kvstore introduces a lot of complexity. What node is responsible for collecting it? What if that node dies? The approach I'm proposing has the best chances to always provide meaningful values and introduces the least complexity.

> Super fine with that, just to point out an usability aspect, create a function to check between a node to --all or a node to other node, sometimes it's useful to check only 2 nodes :-)

We should separate the collection of metrics and the display. The tool should trigger the local health agent, retrieve the entire connectivity matrix and then display according to eventual filters provided. Down the line, it might be useful to extend `GET /status/probe` with additional filters and only probe certain connections but most users will be looking at "tell me what is not working" instead of probing "is this working?"

**Comment by eloycoto** [comment]
Happy with the approach, the things that I think that can be added are: 

- On /healthz the bpf mounted status: If it is mounted and is BPF filesystem, something that is "cilium" specific and users use to be confused about that, [error message is not clear at all.](https://github.com/cilium/cilium/blob/master/pkg/bpf/bpffs.go#L213) 

- On K8s deployments, I think that should be something that checks endpoints and pods are up to date and without errors. In this case you're sure that RBAC is correctly and you have access to the K8s instance.

**Comment by joestringer** [comment]
Dropped priority to medium, since PR #2052 lay the groundwork for this.

**Comment by joestringer** [comment]
New PR #2315 runs cilium-health in a network namespace as a reserved endpoint.

**Comment by joestringer** [comment]
I jotted down some notes on the remaining wishlist items from the original proposal in Issue #2676. PR #2674 ties up the remaining loose ends that I intend to address in the short term. Closing this issue.
