### ISSUE TITLE
Service Mesh follow-ups after 1.12 release

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#19698]
- [ ] Write a proper description to #18894, including but not limited to:
  - [ ] limitations, current things that are implemented, envoy resources that can be configured, resources that can't be configured, how this fits into the broader service mesh picture
  - [ ] which components (cilium-agent, cilium-operator, cilium-proxy) are expected to interact with these resources
  - [ ] RBAC
  - [ ] flow of data
- [x] Move Envoy specifics from `pkg/service` to `pkg/k8s/watchers`, see https://github.com/cilium/cilium/pull/18894#discussion_r840633249 @pippolo84 for v1.13.0-rc2. This is being tracked in #23182
- [x] Prepend Envoy resource names with CEC/CCEC namespace (and name?) so that operator does not need to worry about that @pippolo84 for v1.13.0-rc1. Done as part of https://github.com/cilium/cilium/pull/21500
- [x] Add Ingress test with `reserved:ingress` policy to cilium/cilium-cli connectivity test suite @pippolo84 for v1.13.0-rc2 (waiting for @sayboras to come back for more help). Tracked as part of https://github.com/cilium/cilium/issues/24536
- [x] Upstream Envoy upstream callback feature now in `cilium/proxy/patches`
- [x] Allow sharing of External Load Balancers for multiple Ingresses (with non-overlapping hosts/paths). Done as part of https://github.com/cilium/cilium/issues/21270
- [x] Support multiple TLSs in envoy downstream context, see https://github.com/cilium/cilium/pull/18867#discussion_r842070230. _Updated: done as part of https://github.com/cilium/cilium/pull/22671_
- [x] Standardize watcher/informer pattern, also address https://github.com/cilium/cilium/pull/18867#discussion_r842321517. Tracked in https://github.com/cilium/cilium/issues/24601 as we are having new Hive and Cell pattern.

**Comment by joestringer** [comment]
Is there any upgrade implications for this item? If yes, then it seems plausibly like something we may want to push into 1.12.

> Prepend Envoy resource names with CEC/CCEC namespace (and name?) so that operator does not need to worry about that

**Comment by jlandowner** [comment]
I really need the feature `Allow sharing of External Load Balancer for multiple Ingresses` to reduce the cost of cloud provider's external load balancers created by each single Ingress.
Can I have the current status or progress?

**Comment by sayboras** [comment]
> Can I have the current status or progress?

I don't think anyone is actively working on this item now. Hopefully, I will have some cycles to work on this soon.

**Comment by jlandowner** [comment]
@sayboras 
Thank you for replying. Can I have chance to contribute or help something?

**Comment by youngnick** [comment]
I've just logged #21270 to cover the work to implement shared load balancer for Ingress, @sayboras is getting started on the initial work now.

**Comment by joestringer** [comment]
#21270 made it in time for v1.13.0-rc1, but there's a bunch of unchecked boxes in the description so I'm just going to clear the milestone.

**Comment by sayboras** [comment]
Thanks, there are a bunch of items planned for v1.13.0-rc2, so I just tag this to v1.13.0-rc2, so that we don't forget.
