### ISSUE TITLE
Proposal: When to put ingress and egress of an endpoint into default deny

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2002]
***Problem:***
The current behaviour puts an endpoint into default deny at ingress whenever there is a policy rule that selects the endpoint. This behaviour can be modified by running the agent in "always" policy enforcement mode in which case all endpoints are always in default deny mode.

With the introduction of egress rules, it is unclear whether a policy rule should put an endpoint into default deny at ingress, egress, or both.

**Proposal:**

Basic rules:
 - If any rule selects an endpoint and the rule has an ingress section, the endpoint goes into default deny at ingress
 - If any rule selects an endpoint and the rule has an egress section, the endpoint goes into default deny at egress.
 - An empty endpoint label selector selects all endpoints
 - An empty CIDR block allows nothing

**Examples:**

***put app1 into ingress default deny:***
```yaml
spec:
  endpointSelector:
    matchLabels:
      id: app1
  ingress:
```

***put app1 into egress default deny:***
```yaml
spec:
  endpointSelector:
    matchLabels:
      id: app1
  egress:
```

***put app1 into egress and ingress default deny:***
```yaml
spec:
  endpointSelector:
    matchLabels:
      id: app1
  ingress:
  egress:
```

***put app1 into egress default deny and only allow to host***
```yaml
spec:
  endpointSelector:
    matchLabels:
      id: app1
  egress:
    toEntities:
    - host
```

***put app1 into ingress default deny but allow from any endpoint in the namespace that the policy belongs to:***
```yaml
spec:
  endpointSelector:
    matchLabels:
      id: app1
  ingress:
    fromEndpoints:
      matchLabels:
```

NOTE: external traffic will be disallowed

***put app1 into ingress default deny and only allow from external world***
```yaml
spec:
  endpointSelector:
    matchLabels:
      id: app1
  ingress:
    fromEntities:
    - world
```

Tasks:
- [x] Add endpoint fields to store default deny for ingress and egress (replace current logic which is policy on/off by endpoint)
- [x] Add fields to display default deny on ingress and egress
- [x] Update `cilium endpoint list` to show ingress and egress instead of just "Policy enabled"
- [x] Verify datapath and enforce correctly

**Comment by aanm** [comment]
> An empty endpoint label selector selects all endpoints

On different or same namespaces?

> An empty CIDR block allows nothing

What does "allows nothing" means? 

On all endpoints, with policy mode "always", will the traffic to the host be always allowed or not?

**Comment by tgraf** [comment]
> On different or same namespaces?

All endpoints in the namespace of the policy.

**Comment by raybejjani** [comment]
How does the "in the same namespace" restriction* affect traffic to something like kube-dns? I suppose we'd only ever need to specify namespace on egress, and we support that via services. If so, we'd expect a user to have to specify a fromEntities: ["cluster"] rule on the pods running the service, right?

 * this isn't new, right? we're just being more explicit than before?
