### ISSUE TITLE
Migrate K8sServices from Ginkgo to newer testing infrastructure

### ISSUE THREAD

**Issue by brb** [cilium/cilium#20160]
Parent issue with motivation: https://github.com/cilium/cilium/issues/37837

* [ ] `Checks E/W loadbalancing (ClusterIP, NodePort from inside cluster, etc)`
  * [x] `Checks service on same node` @brb
     Let's keep for per-packet LB and for bpf_sock (ipv4 and ipv6) as e2e
  * [x] `Checks DualStack services` @joamaki
     Move to control plane suite (in the end it's checking whether lbmap is OK)
  * [ ] `Checks in-cluster KPR`
    * [x] `Tests NodePort` @joamaki
      Move to control plane test
    * [x] `Tests NodePort with externalTrafficPolicy=Local` @joamaki
      Move to control plane test
    * [x] `Tests NodePort with sessionAffinity` @joamaki
      Move to eBPF unit test
    * [ ] `Tests HealthCheckNodePort` @brb
      Keep as e2e
    * [ ] `Tests that binding to NodePort port fails` @brb
      Keep as e2e
    * [x] `Tests HostPort` @brb @joamaki
      Move to control plane and maybe eBPF unit test
    * [ ] `with L7 policy` @brb
      * [ ] `Tests NodePort with L7 Policy`
        Keep as e2e for now
    * [x] `Checks service accessing itself (hairpin flow)` @brb @dylandreimerink
       Move to eBPF unist test
    * [x] `Checks connectivity when skipping socket lb in pod ns`
      * [x] `Checks ClusterIP connectivity` @joamaki
         Move to control-plane -- Jussi: Shouldn't this be a eBPF unit test? The bpf-lb-sock-hostns-only option affects bpf_lxc/bpf_sock so there's nothing in control-plane to test. 
    * [ ] `Tests NodePort inside cluster (kube-proxy)` @brb
      Keep it for now as e2e
      * [ ] `with IPSec and externalTrafficPolicy=Local`
      * [ ] `with the host firewall and externalTrafficPolicy=Local`
      * [ ] `with externalTrafficPolicy=Local`
      * [ ] `""`
    * [ ] `TFTP with DNS Proxy port collision` @brb
      Keep it for now as e2e
      * [ ] `Tests TFTP from DNS Proxy Port`
    * [ ] `with L4 policy` @brb
      Keep it for now as e2e
      * [ ] `Tests NodePort with L4 Policy`
    * [ ] `with L7 policy` @brb
      Keep it for now as e2e
      * [ ] `Tests NodePort with L7 Policy`
* [ ] `Checks N/S loadbalancing`
  * [ ] `Tests NodePort with sessionAffinity from outside` @brb @dylandreimerink
    To convert to an eBPF unit test
  * [x] `Tests externalIPs` @brb @dylandreimerink
    To convert to an eBPF unit test
  * [ ] `Tests GH#10983` @brb @dylandreimerink
    To convert to an eBPF unit test
  * [ ] `Tests security id propagation in N/S LB requests fwd-ed over tunnel` @brb @dylandreimerink
    To convert to an eBPF unit test
  * [ ] `Tests with secondary NodePort device` @brb
    Let's keep it as e2e, as this tests `bpf_fib_lookup()` assumptions too
  * [ ] `Tests with direct routing and DSR` @brb
    We should have at least one test for TC BPF NodePort SNAT and one for XDP NodePort DSR as e2e, the rest can be moved as eBPF unit tests
  * [ ] `Tests with XDP, direct routing, SNAT and Random` @brb
  * [ ] `Tests with XDP, direct routing, SNAT and Maglev` @brb
  * [ ] `Tests with XDP, direct routing, Hybrid and Random` @brb
  * [ ] `Tests with XDP, direct routing, Hybrid and Maglev` @brb
  * [ ] `Tests with XDP, direct routing, DSR and Random` @brb
  * [ ] `Tests with XDP, direct routing, DSR and Maglev` @brb
  * [ ] `Tests with TC, direct routing and Hybrid` @brb
  * [x] `Supports IPv4 fragments` @qmonnet
    I think this can be moved to eBPF unit test
  * [ ] `With host policy` @brb
    * [ ] `Tests NodePort`
    Let's keep as e2e test
  * [x] `ClusterIP cannot be accessed externally when access is disabled",` @joamaki
    The control plane test
  * [x] `With ClusterIP external access`
    * [x] `ClusterIP can be accessed when external access is enabled`
    The control plane test -- Jussi: The logic for this feature is contained in pkg/maps/lbmap/lbmap.go, so not testable with mock lbmap. Might need to rethink the control plane testing approach and perhaps mock things at lower level. Or we'll just add a lbmap unit test for this.
* [x] `Checks graceful termination of service endpoints` @joamaki
  All tests can be moved to the control-plane e2e tests which will mock
  kube-apiserver and lbmap.
  * [x] `Checks client terminates gracefully on service endpoint deletion`
  * [x] `Checks if terminating service endpoint doesn't serve new connections`
* [ ] `Checks device reconfiguration` @joamaki
  We could convert it to the control-plane e2e test. Not sure whether we could
  mock loading of bpf_host though (maybe pkg/datapath/linux already provides such
  mocks). Jussi: I don't quite see yet how this could be written as control-plane test given the current structure (`Daemon.ReloadOnDeviceChange` method). Similar issues apply to testing policies as control-plane tests.
  * [ ] `Detects newly added device and reloads datapath`

**Comment by joestringer** [comment]
I linked this in #44168, but it's not clear to me how up-to-date the description is at this time. Hence I'll just close this out as we don't need to track this twice.
