### ISSUE TITLE
Proposal: Nightly test plan

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2029]
Phase 1:
 - Everything is Kubernetes based

- [ ] Scale up to 200 endpoints across two VMs (#2109)
  - [x] Report time to get all endpoints up
  - [x] Run a connectivity test
- [ ] Load 10k automatically generated policy rules as a batch addition according to the distribution rules below (@eloycoto)
  - [ ] Report time to load rules
  - [ ] Report time to update all endpoints
  - [ ] Run a connectivity test
    - [ ] TCP
    - [ ] UDP
    - [ ] HTTP (wrk, ab, ...)
    - [ ] Kafka
- [x] Run load test for multiple hours (@eloycoto)
  - Report:
    - [ ] Number of failed connection attempts
    - [ ] Throughput and latency
- [ ] Bring up/down endpoints randomly in controller intervals (@nebril)
  - [ ] Report connectivity failures
- [ ] Restart agent (@nebril)
  - [ ] Report time to restore all endpoints #2166
  - [x] Run connectivity test throughout restart
    - [ ] Report number of failed connection attempts

**Policy generation details:** @eloycoto  #2258 
Combination of each member with all other members of all other groups:
L3 Policy group:
- [x] No policy
- [ ] L3 ingress rule (CIDR)
- [x] L3 ingress rule (Label)
- [ ] L3 egress rule (CIDR)

Connectivity group:
- [x] direct
- [ ] via L3 service
- [x] via L4 service
- [x] via NodePort

L4 Policy group
- [x] No policy
- [x] L4 ingress rule port only
- [ ] L4 ingress rule proto only
- [x] L4 ingress rule port + proto
- [ ] L4 egress rule port only
- [ ] L4 egress rule proto only
- [ ] L4 egress rule port + proto
- [x] L3+L4 dependant ingress rule (dependant on label)
- [ ] L3+L4 dependant ingress rule (dependant on CIDR)

L7 Policy group:
- [x] No policy
- [x] L4+L7 ingress rule
- [x] L4+L7 egress rule
- [x] L3+L4+L7 dependant ingress rule (dependant on label)
- [x] L3+L4+L7 dependant ingress rule (dependant on CIDR)
- [x] L3+L4+L7 dependant egress rule (dependant on CIDR)

**Comment by jrfastab** [comment]
How about 'wrk' benchmark tests and report out performance data as well?

**Comment by ianvernon** [comment]
Let me know how I can help get the infrastructure set up to get this running. I can set up a new Jenkins agent fairly quickly for you to use for dedicated testing. I'm happy to write tests as well.
