### ISSUE TITLE
Refactoring K8sDatapathConfig

### ISSUE THREAD

**Issue by brb** [cilium/cilium#20573]
**NB**: please defer any work if a test needs to be moved to "Datapath Conformance suite (e2e)".

- [ ] `MonitorAggregation` @aspsk
    BPF unit test
- [ ] `Encapsulation` Currently **quarantined**
    - [ ] `Check connectivity with transparent encryption and VXLAN encapsulation` @NikAleksandrov
    Datapath Conformance suite
	- [ ] `Check connectivity with VXLAN encapsulation`
    Datapath Conformance suite (e2e)
    - [ ] `Check connectivity with Geneve encapsulation`
    Datapath Conformance suite (e2e)
	- [ ] `Check vxlan connectivity with per-endpoint routes`
    Datapath Conformance suite (e2e)
	- [ ] `Check iptables masquerading with random-fully` @jibi 
    Datapath Conformance suite (e2e), same as with `Skip conntrack for pod traffic`.
    - [ ] `Check iptables masquerading without random-fully` @jibi
    Datapath Conformance suite (e2e)
- [ ] `DirectRouting` (only on GKE) @brb
    It can be removed, as it should be covered by `Conformance GKE`
- [ ] `AutoDirectNodeRoutes` **TODO** needs assignee
    - [ ] `Check connectivity with automatic direct nodes routes`
        Datapath Conformance suite (e2e)
	- [ ] `Check direct connectivity with per endpoint routes`
        Ditto, just that it should run on Cilium cluster with per endpoint
        routes being enabled
- [ ] `IPv6 masquerading` @brb
    Datapath Conformance suite
- [ ] "Check BPF masquerading with ip-masq-agent" @brb
    Datapath Conformance suite (e2e)
- [ ] `Wireguard encryption` @brb
    Datapath Conformance suite (e2e)
- [ ] `Transparent encryption DirectRouting` @NikAleksandrov
    I assume these should stay as e2e due to stack <-> bpf_host. Anyway, the encryption
    test cases are planned within the Datapath Conformance suite.
	- [ ] `Check connectivity with transparent encryption and direct routing`
	- [ ] `Check connectivity with transparent encryption and direct routing with bpf_host`
- [ ] `IPv4Only` **TODO** needs assignee
    We could run Datapath Conformance suite (e2e) on a IPv4-only Kind cluster.
- [ ] `Etcd` **TODO** needs assignee
    Datapath Conformance suite (e2e) should run on a cluster with etcd kvstore
- [ ] `Host firewall` @pchaigno
    The last four configs don't have to all be tested in e2e. I think it's enough to test only one in e2e if all are also covered in BPF unit tests. 
    - [ ] `Check connectivity with IPv6 disabled` (e2e)
    - [ ] `With VXLAN`
    - [ ] `With VXLAN and endpoint routes`
    - [ ] `With native routing`
    - [ ] `With native routing and endpoint routes`
- [ ] `Iptables Skip conntrack for pod traffic` @jibi
    For now it could be part of the Datapath Conformance suite (e2e). However,
    we should introduce an advanced datapath e2e suite which
