### ISSUE TITLE
CFP: Add support for k8s Gateway API

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#20655]
## Cilium Feature Proposal

This issue is to discuss and track for [k8s API Gateway][1] work mentioned in [roadmap][2]. Kindly note that the actual work or implementation might vary based on the discussion and requirements mentioned in this GitHub issue.

### Pre-tasks v1.13.0-rc1

While it's not strictly required, it's best to complete all follow-up items in https://github.com/cilium/cilium/issues/19698 or at least the below-related tasks:

- [x]  Allow sharing of External Load Balancer for multiple Ingresses (with non-overlapping hosts/paths)
    - The main reason is to re-use the same pattern for API gateway, as multiple HTTP routes can re-use the same APIGateway (i.e. same external load balancer) @sayboras. This is done as part of https://github.com/cilium/cilium/pull/21386
- [x]  Prepend Envoy resource names with CEC/CCEC namespace (and name?) so that operator does not need to worry about that.
    - This is to simplify the logic of constructing envoy resources. @pippolo84. Done as part of https://github.com/cilium/cilium/pull/21500

### Tasks (Mid October)

At the time of writing, the below APIs were just graduated to beta, it's making sense to start with these APIs as the first step.

- [GatewayClass](https://gateway-api.sigs.k8s.io/api-types/gatewayclass/) @sayboras 
- [Gateway](https://gateway-api.sigs.k8s.io/api-types/gateway/) @sayboras 
- [HTTPRoute](https://gateway-api.sigs.k8s.io/api-types/httproute/) @sayboras 
- [ReferenceGrant](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1alpha2.ReferenceGrant) @sayboras 

At the high level, the L7 HTTP route could be done the same way Cilium does with IngressController. Below items can be used as references or starting points:

- [x] Add new APIs into the Cilium codebase and check if slim types are required.
    - [x] If slim types are not required, direct go import should be just sufficed. 
- [x] Add required watchers for Gateway, HTTPRoute objects.
    - [x] Watch only Gateway object with class name as cilium.
- [x] Provision required envoy resources.
    - [x] no change in datapath is foreseen, but let's see how it's going.
    - [x] handle conflicts between HTTP routes. Please refer to [API Spec](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.ListenerConditionReason).
- [x] Add a feature flag like what we have with ingress controller or envoy config.
- [x] Add installation support via helm chart
    - [x] Pre-configure Cilium GatewayClass if the feature flag is enabled.
- [x] Make sure that upstream [conformance tests](https://github.com/kubernetes-sigs/gateway-api/tree/main/conformance) are successfully running as part of CI.
- [x] Add Getting Started Guide documentation. #21908 

### Optional

Below APIs are still under v1alpha2 at the time of writing. However, while implementing the above tasks, it's better to _think_ forward to avoid any potential re-work in future.

- [GRPCRoute](https://gateway-api.sigs.k8s.io/api-types/grpcroute/). _Tracked in https://github.com/cilium/cilium/issues/21928._
- [TCPRoute](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1alpha2.TCPRoute). _Tracked in https://github.com/cilium/cilium/issues/21929._
- [TLSRoute](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1alpha2.TLSRoute). _Tracked in https://github.com/cilium/cilium/issues/21927._
- [UDPRoute](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1alpha2.UDPRoute). _Tracked in https://github.com/cilium/cilium/issues/21930._

[1]: https://github.com/kubernetes-sigs/gateway-api
[2]: https://docs.cilium.io/en/latest/community/roadmap/#cilium-service-mesh
[3]: https://kubernetes.io/blog/2022/07/13/gateway-api-graduates-to-beta/#graduation-to-beta

**Comment by yuriy-yarosh** [comment]
This would be really great for CD canary deployments via [flagger](https://docs.flagger.app/tutorials/gatewayapi-progressive-delivery).

**Comment by arukiidou** [comment]
envoy gateway might be useful for this.

https://github.com/envoyproxy/gateway

**Comment by youngnick** [comment]
With the merging of #21386 and the closing of #21270, the obstacles to starting work on this are removed, so this will get started. @sayboras is going to lay the foundations, and then I will be able to round things out.

**Comment by craigbox** [comment]
@youngnick a reminder to update https://gateway-api.sigs.k8s.io/implementations/#cilium !

**Comment by youngnick** [comment]
Ah, yes, thanks!
