### ISSUE TITLE
CLI: Add JSON formatting to the cilium commands

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2083]
When extending the API, it can be easy to skip printing new fields in the cli commands, because the formatting must be custom-written for each field. Worst case, we push a version of Cilium out which exposes the API but the field cannot be read from commandline tools. To alleviate this issue, and to improve programmable access to the API, we can extend the commandline clients to accept a `-o json` flag which formats the API response as indented JSON.

This should be done by adding the following lines to each relevant CLI command:
https://github.com/cilium/cilium/blob/667fad3a17776368afdbad166a2dc98d97aff44c/cilium/cmd/endpoint_list.go#L51
https://github.com/cilium/cilium/blob/667fad3a17776368afdbad166a2dc98d97aff44c/cilium/cmd/endpoint_list.go#L105-L110

Each of the following checkboxes should be a trivial microtask. If you propose a PR to address any one of these, please check off the box or comment on this issue.

`cilium`
---
* [x] Replace `--json` with `-o` multiple output printer (#2852)
  * [x] Remove `--json` flag (#2852)
* [ ] Extend `bpf`                                                              
  * [ ] Extend `bpf ct flush`                                                   
  * [x] Extend `bpf ct list` (#2852)                                                    
  * [x] Extend `bpf endpoint list`                                              
  * [x] Extend `bpf lb list`                                                    
  * [ ] Extend `bpf policy add`                                                 
  * [ ] Extend `bpf policy delete`                                              
  * [x] Extend `bpf policy list` (#2852)                                                
  * [x] Extend `bpf tunnel list`                                                
* [x] Extend `config`                                                           
* [ ] Extend `endpoint`                                                         
  * [x] Extend `endpoint config` (#3234)                                      
  * [ ] Extend `endpoint disconnect`                                            
  * [x] Extend `endpoint get`
    * [x] Switch to `OutputPrinter()` (#2852)
  * [x] Extend `endpoint health`
    * [x] Reuse flag from root (#2852)                                                   
  * [ ] Extend `endpoint labels`                                                
  * [x] Extend `endpoint list` 
  * [x] Extend `endpoint log` (#2852)                                                
  * [ ] Extend `endpoint regenerate`                                            
* [x] Extend `identity`                                                         
  * [x] Extend `identity get`                                                   
  * [x] Extend `identity list`                                                  
* [x] Extend `monitor`                                                          
* [ ] Extend `policy`                                                           
  * [x] Extend `policy delete` (#2852)                                                  
  * [x] Extend `policy get` (#2852)                                                     
  * [x] Extend `policy import` (#2852)                                                  
  * [x] Extend `policy trace` (#2852)                                                   
  * [x] Extend `policy validate`                                                
  * [ ] Extend `policy wait`                                                    
* [ ] Extend `prefilter`                                                        
  * [ ] Extend `prefilter delete`                                               
  * [x] Extend `prefilter list` (#2852)                                                 
  * [ ] Extend `prefilter update`                                               
* [ ] Extend `service`                                                          
  * [ ] Extend `service delete`                                                 
  * [x] Extend `service get`                                                    
  * [x] Extend `service list`                                                   
  * [ ] Extend `service update`                                                 
* [x] Extend `status`
    * [x] Switch to `OutputPrinter()`                                                       
* [x] Extend `version`

`cilium-health`
---
* [x] Replace `viper.GetBool("json")` with `OutputPrinter()` (#2852)
  * [x] Drop `--json` flag (#2852)
* [x] Extend `status`
  * [x] Switch to `OutputPrinter()` (#2852)
* [x] Extend `get` (#2852)
