### ISSUE TITLE
Rework ipcache to handle metadata from multiple sources via a dedicated worker goroutine

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#21142]
This meta issue tracks a variety of enhancements being made to `pkg/ipcache` in order to make it more resilient and able to consistently merge information gathered about IPs from various sources (kvstore, k8s resources, local node, etc.).

Broadly speaking, these changes define a new "desired state" structure plus a resolution loop in order to realize that desired state. The desired state is synchronously updated by callers to define information such as a list of labels that one resource wants to associate with an IP, or an encryption key to associate with it. Then the upsert/remove call (typically from a k8s watcher) would trigger a separate goroutine to then realize the state internally. The realization of the state will combine all of the information from different sources together, potentially allocate identities to associate with the IP, trigger policy calculation for any new identities, and ensure that the datapath is consistently updated with any new policy state as well as any new bpf ipcache map state. For more details on the high level API, see #19765.

Tasks:

1. Remove static package-level variables from `pkg/ipcache`
   - [x] https://github.com/cilium/cilium/pull/19073
2. Create new asynchronous API for handling insertion of labels / metadata /auxiliary data into the IPCache
   - [x] https://github.com/cilium/cilium/pull/19765
3. Convert the existing callers of IPCache to the new API
   - CIDR policies
     - [x] https://github.com/cilium/cilium/pull/20116
     - [x] ~(optional) Optimization: Use sentinel type to represent CIDR labels to be expanded~
       - https://github.com/cilium/cilium/pull/30897
   - NodeManager
     - [x] Inject encryption state into the new API
     - [x] https://github.com/cilium/cilium/pull/21667
     - [x] ~~https://github.com/cilium/cilium/pull/20117~~
     - [x] https://github.com/cilium/cilium/pull/23208
       - [x] Ensure ingress IPs are excluded from CIDR identity resolution similar to health IPs
       - [x] Ensure the node manager uses a unique resource ID depending on the source of information (k8s or kvstore; k8s node or CiliumNode) 
   - KVStore (pkg/ipcache/kvstore.go)
     Note: KVStore path likely does not need to allocate identities.
     - [ ] pkg/ipcache/kvstore.go
       -  https://github.com/cilium/cilium/pull/31409
     - [ ] pkg/node/store/store.go
     - [ ] Define resource IDs for kvstore paths
   - Local NodeDiscovery
     - [x] Convert Daemon insert host IPs -> UpsertMetadata
       - https://github.com/cilium/cilium/pull/25749 
     - [ ] Auxiliary data, other label based information
     - [ ] Pod NamedPorts
       -  https://github.com/cilium/cilium/pull/31409
     - [ ] Introduce [`HasChanged`](https://github.com/cilium/cilium/pull/23208#discussion_r1196133754) in `InjectLabels()`
   - CIDR Identity restore on startup
     - [x] daemon/cmd/daemon.go
       - https://github.com/cilium/cilium/pull/27255
       - https://github.com/cilium/cilium/pull/28673
   - FQDN Policies (https://github.com/cilium/cilium/issues/28930)
     - [x] Introduce a synchronization mechanism to ensure ipcache is plumbed (even if async) before releasing the corresponding DNS response
   - Overlapping PodCIDRs
     - [x] Add support for encoding cluster-specific metadata (cf. https://github.com/cilium/cilium/pull/22935)
   - ToServices policy translation
     - [x] `k8sServiceHandler()` https://github.com/cilium/cilium/pull/31062
   - https://github.com/cilium/cilium/issues/30992
   - Any others?
     - [ ] Evaluate remaining callsites
4. Remove old synchronous ipcache.Upsert() APIs
   - [x] Support natively injecting security identities into the ipcache API (possibly related to NodeManager changes) https://github.com/cilium/cilium/pull/21667
   - [x] Refactor the AllocateCIDRsForIPs to use the new ipcache API
     - [x] Mitigate issues where a CIDRSet labels refer to the same IP prefix as the IP/Identity backing an FQDN
   - [ ] Re-evaluate the use of `pkg.Source` for resolving ipcache upsert conflicts
     - [ ] Re-evaluate [`KubeAPIServer`](https://github.com/cilium/cilium/pull/23208#issuecomment-1543570384) source at the least
   - [ ] Merge the main IPCache and IPCache.metadata structures together to reduce duplication? (TBD)
5. Expand testing of these features
   - [ ] https://github.com/cilium/cilium/issues/17829

Related: https://github.com/cilium/cilium/issues/17962
Related: https://github.com/cilium/cilium/issues/18301

**Comment by squeed** [comment]
@joestringer I think we can finally, really, close this. I don't foresee us changing endpoint identities to the async API.

**Comment by christarazi** [comment]
@squeed Do you mean we will always have a mix of APIs in the ipcache? 

I agree with closing this issue at the very least and if we want to track things further, they can go into a new issue.

**Comment by gandro** [comment]
I would love for us to only have the async API, even for endpoints. We don't need it for the endpoint's sake (they work perfectly fine with the sync API), but there is quite a bit of tech debt in the IPCache internals to make the two APIs work together. I think we could remove quite a bit of complicated logic there if we moved everything over to the async API.

**Comment by joestringer** [comment]
Is the goal of this original meta issue addressed? I think broadly yes. This mechanism is now in place for the vast majority of IPCache users. The internal synchronous APIs are deprecated. We haven't checked off all the boxes in this issue, and at a glance none of those remaining items appear to be clearly already resolved.. but it's fair for us to step back and review which of these are useful tasks at this point.

Endpoints does seem to be the key remaining point. I do remember endpoints being one of the big question marks from the beginning of this design. I think even from the beginning the thought was that we would likely need some kind of "override" semantics for endpoints rather than having them directly merge in with all the other "metadata" the IPCache receives. That said, we do now have an async `OverrideIdentity` API... could we use that override API for endpoints rather than the synchronous API?

I agree with @gandro that it feels like there's room to simplify some of the logic if we can avoid having the combination of the sync and async logic. I'd also love to see us get rid of the string indexing in the outer IPCache object. There's a decent chance some of those maps could also be retired in favor of storing information in the inner `metadata` structure. Admittedly though we could treat some of these as separate issues and scope them out of this issue as general follow-up tech debt.

**Comment by squeed** [comment]
I agree that the dance between the async (a.k.a "aggregated") and synchronous (a.k.a. "direct") APIs is awkward. We are in a stable state now, even if there are warts. That said, the semantics are **very** different between the two modes, so it's for good reason that they were not combined.

Specifically, the core difference is that direct IPCache writes are after external identity allocation (endpoints), whereas the asynchronous layer is before identity allocation.

In the async API, the ipcache is responsible for identity allocation and maintaining a correct reference count. Even with OverrideIdentity, there is still allocation and reference tracking - just no label aggregation. There is lots of code in `doInjectLabels()` to get the bookkeeping just right.

For endpoints , the ipcache doesn't manage identities at all. So if we were to remove the "direct" API, we would still need to have divergent logic for endpoints versus everything else. We also need to keep the logic to transition IPs between the two modes - it doesn't go away, even if the `Upsert()` function goes away.

So while there are some warts, I don't see how removing the synchronous API makes much of an improvement. We still have two "classes" of ipcache entries.

**Comment by joestringer** [comment]
> Even with OverrideIdentity, there is still allocation and reference tracking - just no label aggregation.

Ohh, I was thinking it was just an async Override with a pre-allocated security identity. I guess I'd call it `OverrideLabels()` if given the choice. Because I feel like there is a path here to actually pull a security identity override into the metadata and have that short-cut the allocation logic. But I'll admit that there may be some more nuance I'm missing here... plus we'd want to be abundantly sure with permutations & lifecycle testing to make sure the different cases and transitions work as expected.

The way I'm thinking about this is that ipcache metadata is just a fancy table of overlapping info about an IP, then we should be able to take all of that info into consideration when deciding the actual logic to apply for that IP. This can include things like "override to only set these labels" for the host IPs case, "override to only set this security identity (and corresponding labels)" for the pods/endpoints case, and "combine with this predetermined set of rules" for all the other cases. 

> There is lots of code in doInjectLabels() to get the bookkeeping just right.

And in `upsertLocked()` and `removeLocked()` too.

> For endpoints, the ipcache doesn't manage identities at all. So if we were to remove the "direct" API, we would still need to have divergent logic for endpoints versus everything else. We also need to keep the logic to transition IPs between the two modes - it doesn't go away, even if the Upsert() function goes away.

At the core the divergent logic does need to diverge at some point, sure. Inherently there's an override because the allocation strategy is different.

I'm thinking about this case where you do `UpsertMetadata(prefix, ...)`, `Upsert(prefix)`, `Delete(prefix)`.. right now this is handled by:
1. Async resolve, allocate identity, create an entry `ipc.ipToIdentityCache[prefix]`
2. Sync upsert, create an entry `ipc.ipToIdentityCache[addr]`, check for shadowing and override
3. Remove `ipc.ipToIdentityCache[addr]`, check for shadowing and restore the old identity

It's pretty quirky that we're forced to string-encode the same Prefix differently in the different paths and have this conditional checking logic in Upsert/Remove. It'd be nice if we could just have the desired state of the ipcache calculated in a table in a single reliable way, then the logic for calculating the intended entry was handled in one place consistently, and if this shadowing logic could be integrated into the core `doInjectLabels()`.
