### ISSUE TITLE
CFP: Shared Load Balancer for Ingress

### ISSUE THREAD

**Issue by youngnick** [cilium/cilium#21270]
## Summary

The current implementation of Ingress reconciliation in Cilium creates a LoadBalancer Service per Ingress resource. This is not the most efficient use of resources, and can be made much more efficient by sharing a single LoadBalancer config across all Ingress resources in the cluster.

## Goals

* Allow the creation of Ingresses to provision a single shared load balancer, rather than dedicated.
* Allow cluster admins to still select dedicated load balancer mode for compatibliity purposes.
* Ingress conformance tests should still pass.

## Proposed solution

We'll add a new annotation for Ingress resources that will allow choosing between Shared or Dedicated load balancer for that Ingress resource, along with a config item (settable using Helm as well), that will set the default (which will be `dedicated` for this release). The annotation will be `ingress.cilium.io/loadbalancer-mode:shared|dedicated`.

A new code path will translate Ingress resources into an internal representation of a generic load balancer config. This is a first step towards Gateway API support (#20655), as Gateway API also expects LB behavior like this.

## Tasks

- [x] Add a new Ingress annotation `ingress.cilium.io/loadbalancer-mode:shared|dedicated`. The default for if that annotation is _not_ present will be *shared*, since that's how most ingress controllers work.
- [x] Add a config setting for the default ingress mode, either `dedicated` or `shared`. This will default to `dedicated` for now.
- [x] Update docs with instructions on using the new annotation, or changing the default. https://github.com/cilium/cilium/pull/21493
- [x] Add a new code path that translates all shared LB Ingress resources into a new internal representation, and then translates the internal representation into a single CiliumEnvoyConfig resource that can be consumed by the Cilium proxy layer.
- [x] Ensure that Ingress conformance tests still pass on the shared LB
- [x] Update documentation https://github.com/cilium/cilium/pull/21493
  - [x] Annotations reference
  - [x] Getting Started Guide

**Comment by matdehaast** [comment]
Something I want to make sure is supported is that I want to have potentially two or more shared load balancers. The use case is that I want a shared one for public facing lb and a shared one for an internal facing lb on my cluster.

**Comment by akosveres** [comment]
This is our blocker at the moment, we need to use a lot of these annotations: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/ingress/annotations/ - Looking forward to it being implemented!

**Comment by sayboras** [comment]
> Something I want to make sure is supported is that I want to have potentially two or more shared load balancers. The use case is that I want a shared one for public facing lb and a shared one for an internal facing lb on my cluster. I'm not sure on the mechanics to know which one is being used? Perhaps a name can be set?

I think the above use case will be covered more nicely as part of Gateway API work (tracked as part of https://github.com/cilium/cilium/issues/20655)

**Comment by youngnick** [comment]
@sayboras and I have been working on this, and he's made the pitch that, instead of picking a default of either shared or dedicated, we make it a Helm and config setting. In the PR  (#21386), it's defaulting Ingresses to `dedicated`, which can be overridden on a per-Ingress basis with the annotation. I'll update the main description with this, as I think it gives us a good path forward for flipping the default.
