### ISSUE TITLE
Extend cilium_bpf_map_pressure metric for all maps

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#21508]
Currently the cilium_bpf_map_pressure metric does not support all map types. We should extend it to support all map types.

Tasks:
- [x] Add support for CT / NAT map types (https://github.com/cilium/cilium/issues/20069)
  - [x] https://github.com/cilium/cilium/pull/28183
  - [x] https://github.com/cilium/cilium/pull/27001
- [x] Add policymap to `cilium_bpf_map_pressure_metric` https://github.com/cilium/cilium/pull/14131/files#diff-aeac8ae95e325c39fbeca8b97427e24b733ac5d11e549c7e78279872b05c3533R1082 
  - [x] Investigate why it doesn't show up in `cilium metrics list` output
  - [x] #27332
- [ ] Evaluate whether there are any other missing map types, and add support for those

**Comment by ysksuzuki** [comment]
Hi @joestringer , do you have any plans to work on this issue? I'm planning to work on the enhancement of our monitoring system and want to monitor the map pressure of the CT, NAT, and policy map. Actually, we encountered an issue the other day in which Cilium couldn't create new pods because the policy map was full. Also, we would expect that the communication with Loadbalacner will be disrupted if the CT and NAT map are full. I believe those are very important metrics we should monitor.

**Comment by ysksuzuki** [comment]
> Investigate why it doesn't show up in cilium metrics list output

I think that's because of the threshold.
https://github.com/cilium/cilium/blob/d1d8e7a35b35d3420a33251767ae2696d664da53/pkg/maps/policymap/policymap.go#L44

It shows up in my env if I set the threshold 0. Maybe we should make the threshold configurable?

```
cilium_bpf_map_pressure                               map_name="ipcache"                                                                       0.001301
cilium_bpf_map_pressure                               map_name="lb4_backends_v2"                                                               0.000107
cilium_bpf_map_pressure                               map_name="lb4_reverse_nat"                                                               0.002884
cilium_bpf_map_pressure                               map_name="lb4_services_v2"                                                               0.002884
cilium_bpf_map_pressure                               map_name="lb_affinity_match"                                                             0.000122
cilium_bpf_map_pressure                               map_name="lxc"                                                                           0.001190
cilium_bpf_map_pressure                               map_name="policy_00036"                                                                  0.007553
cilium_bpf_map_pressure                               map_name="policy_00063"                                                                  0.007553
cilium_bpf_map_pressure                               map_name="policy_00114"                                                                  0.004059
cilium_bpf_map_pressure                               map_name="policy_00146"                                                                  0.008057
cilium_bpf_map_pressure                               map_name="policy_00286"                                                                  0.011108
cilium_bpf_map_pressure                               map_name="policy_00301"                                                                  0.008057
cilium_bpf_map_pressure                               map_name="policy_00306"                                                                  0.007553
```

**Comment by christarazi** [comment]
https://github.com/cilium/cilium/pull/27001 will provide support for NAT map.

**Comment by christarazi** [comment]
Endpoint policymaps: https://github.com/cilium/cilium/pull/27367

**Comment by julianwiedmann** [comment]
@joestringer with https://github.com/cilium/cilium/pull/28183 having added support for the CT map, I'd say we're pretty much done here.

> Evaluate whether there are any other missing map types, and add support for those

this part is *very* open-ended :slightly_smiling_face:. Unless we can actually list those missing map types, I'd suggest closing this issue?

**Comment by joestringer** [comment]
> > Evaluate whether there are any other missing map types, and add support for those
> 
> this part is very open-ended 🙂. Unless we can actually list those missing map types, I'd suggest closing this issue?

Isn't this just a matter of listing all of the maps from a live (test) environment then checking `cilium metrics list` output for the `cilium_bpf_map_pressure` metric and validate that all maps can expose map pressure?
