### ISSUE TITLE
bugtool: follow up issues

### ISSUE THREAD

**Issue by aalemayhu** [cilium/cilium#2165]
- [x] Remove all of the files in the gather_files script already covered by the archive?
- [x] Skip commands that do not exist in the pod(s).
- [x] Remove harmless misleading messages like `Error while reading '[bpf ct list 173]', exit status 1`

**Comment by aalemayhu** [comment]
I will be doing some of the items here soon but moving out the bigger ones to separate issues.
