### ISSUE TITLE
CFP: Support TLSRoute in Cilium Gateway API

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#21927]
## Cilium Feature Proposal
        
The first cut for Gateway API was done in https://github.com/cilium/cilium/pull/21749, however, we have a couple of follow-up tasks to support more features from Gateway API upstream.

This is to track the work to support [TLSRoute](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1alpha2.TLSRoute)

## Goals

To implement [TLSRoute](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1alpha2.TLSRoute) into Cilium's existing GatewayAPI implementation in a way that enables further L7 routes to be painlessly implemented.

This would allow routing of TLS traffic without termination of the encryption but allowing it to be routed based on the SNI as seen in the handshake with the GatewayAPI specification. 

## Proposed Solution

**DRAFT by Maartje**
### Envoy

The `HTTPRoute` uses an integration to convert the route to an Envoy rule that is installed via a CEC rule. This is analogue to how ingress does it using many of the same translation "middleware" code. 
`TLSRoute` is very similar to `HTTPRoute` with the difference that it only checks 1 part of the header to route: the SNI. 
A lot of the same logic could be re-used in here to make this work. 

Envoy has support to filter traffic based on SNI in the `serverNames` fillter chain match for TLS with the `TlsInspector` filter, the same logic is used to chose the route to terminate TLS to in the `HTTPRoute`. From there on we can use a TCP proxy to forward the TLS including the initial handshake to the backend service which uses the same discovery mechanism as HTTPRoute/Ingress. 

```yaml
   resources:
    - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
      filterChains:
      - filterChainMatch:
          serverNames:
          - abc.example.com
          transportProtocol: tls
        filters:
        - name: envoy.filters.network.tcp_proxy
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            cluster: gateway-conformance-infra/tls-backend:443
            statPrefix: gateway-conformance-infra/tls-backend:443
      listenerFilters:
      - name: envoy.filters.listener.tls_inspector
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
```

This implementation can build on top of all work already done for HTTPRoute and try to consolidate many helper functions to accept both routes. However Go's type system and the TLSRoute only being v1alpha might make this harder.
Many of this work then can be used again for the GRPCRoute

## Tasks

- [x] Add required reconcile functions to validate TLSRoutes
  - [x] Validate against invalid SNIs
  - [x]  If both the Listener and TLSRoute have specified hostnames, and none match with the criteria above, then the TLSRoute is not accepted
- [x] Add support for Gateways to be TLS and Envoy to be configured acordingly
- [x] Add a translator module for TLSRoute rules to Envoy rules
- [x] Handle edge cases according to spec (TBD)
  - [x]  multi protocol gateways
  - [x] If both the Listener and TLSRoute have specified hostnames, any TLSRoute hostnames that do not match the Listener hostname MUST be ignored (includes *. handling)
- [x] Validate required CRDs will be installed
- [x] Pass conformance tests
- [ ] Awesome documentation!

**Comment by bassiebal** [comment]
Hi guys, 

Great work so far on the gateway API! As luck would have it I need to configure a listener to do tls passthrough as the pod already serves a certificate. Is there any update on the TLSRoute feature?

**Comment by sayboras** [comment]
> Great work so far on the gateway API! As luck would have it I need to configure a listener to do tls passthrough as the pod already serves a certificate. Is there any update on the TLSRoute feature?

It's planned as part of 1.14 development cycle.

**Comment by rouke-broersma** [comment]
@sayboras It seems to me like this is implemented as TLS passthrough only, however I would like to use this with TLS termination on the gateway with a TLS listener in termination mode. See https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.GatewayTLSConfig which is a required field for TLS listeners and which contains the field https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.TLSModeType which according to the spec is valid for TLS listeners.

When a TLSRoute is matched with a TLS listener in terminate mode, it seems to me like the TLSRoute should be configured as terminate and not passthrough.

Perhaps I'm misunderstanding and this is already fully implemented, could you please clarify?

**Comment by sayboras** [comment]
Thanks for your comment above, seems like you have found out the details. 

Feel free to open a new issue if you have any other question or concern.
