### ISSUE TITLE
CFP: Support GRPCRoute in Cilium Gateway API

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#21928]
## Cilium Feature Proposal
        
The first cut for Gateway API was done in https://github.com/cilium/cilium/pull/21749, however, we have a couple of follow-up tasks to support more features from Gateway API upstream.

This is to track the work to support [GRPCRoute](https://gateway-api.sigs.k8s.io/api-types/grpcroute/).

## Goals

Based on the progress and code re-usability introduced in [TLSRoutes](https://github.com/cilium/cilium/issues/21927) we should build a similar implementation of GRPCRoute. This route should re-use logic from both TLS and HTTP routes to route gRPC. 

To implement it we should re-use the Envoy logic as an GRPCRoute can be attached to a HTTP(S) Gateway, we can therefore re-use that for TLS termination. Preferably it should use gRPC specific routing in Envoy where possible. 

## Proposed Solution

TBD

## Tasks

- [ ] Add required reconcile functions to validate GRPCRoute
  - [ ] Validate against hostname re-use between HTTP and gRPC
- [ ] Add a translator module for GRPCRoutes rules to Envoy rules
  - [ ] Consider a gRPC Web filter https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_web_filter & https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml
- [ ] Handle edge cases according to spec (TBD)
- [ ] Validate required CRDs will be installed
- [ ] Pass conformance tests
- [ ] Awesome documentation!

**Comment by networkop** [comment]
Need to test this against our hubble-ui to make sure we don't hit issues like [this](https://github.com/isovalent/customer-support/issues/786).

**Comment by sayboras** [comment]
Addressed by https://github.com/cilium/cilium/pull/28464
