### ISSUE TITLE
CFP: Support for more HTTP filters in Gateway API

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#21924]
## Cilium Feature Proposal

The first cut for Gateway API was done in https://github.com/cilium/cilium/pull/21749, however, we have a couple of follow-up tasks to support more features from Gateway API upstream.

This issue is to track the work of implementing different HTTP Filters such as RequestRedirect, URLRewrite, RequestMirror, etc.

## Goals

Users can fully use all the HTTP filters in Gateway API spec with Cilium.

## Tasks

- [x] Filters (only RequestHeaderModifier is implemented currently) 
    - [x] RequestRedirect _done in_ https://github.com/cilium/cilium/pull/22680
    - [x] ResponseHeaderFilter _done in_ https://github.com/cilium/cilium/pull/22680
    - [x] URLRewrite
    - [x] RequestMirror
    - [ ] ~ExtensionRef~
 - [x] Make sure we have enough coverage for these filters. In addition to unit tests, we might need to add our own e2e tests as the current upstream Conformance test didn't have any. The best is to contribute back upstream.
- [ ] Update Getting Started Guide documentation

**Comment by nvibert** [comment]
@sayboras - can we now tick `URLRewrite` & `RequestMirror`?

**Comment by sayboras** [comment]
Thanks for the ping 👍

**Comment by sayboras** [comment]
Right now, we don't have any plan to add ExtensionRef, so the only item pending for this issue is to add related docs for new filters.

**Comment by sayboras** [comment]
Closing this as all items are done.
