### ISSUE TITLE
[docs] Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [cilium/cilium#22007]
**Google has deprecated Universal Analytics** (UA), in favor of its successor, Google Analytics 4 (GA4). This issue is part of a CNCF-wide effort to upgrade project websites to GA4. For more details about the deprecation and the CNCF migration effort, see:

- https://github.com/cncf/techdocs/issues/108, including reference to a suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Tasks: stages 1 & 2

- [x] From the website data stream (`G-V9SYWYG92Y`), configure cross-domain measurement to docs.dapr.io
- [x] Configure GA4 website ID ([gtag.js]) through ReadTheDocs config:
   `master` - #22220, which is deployed at
   https://docs.cilium.io/en/latest/
- [x] Confirm that the GA4 site tag is receiving events for `latest` 
- [x] Confirm that the UA site tag `UA-96283704-1` is still receiving events
- [x] Backports:
    - [x] stable - for context, see https://github.com/cilium/cilium/pull/22220#issuecomment-1362301083
    - [x] [1.13](https://github.com/cilium/cilium/tree/v1.13)
    - [x] [1.12](https://github.com/cilium/cilium/tree/v1.12) https://github.com/cilium/cilium/pull/24067
    - [x] [1.11](https://github.com/cilium/cilium/tree/v1.11) https://github.com/cilium/cilium/pull/24066
- [x] Confirm that the GA4 site tag is receiving events for:
  - [x] latest
  - [x] stable
  - [x] 1.13
  - [x] 1.12
  - [x] 1.11

### Notes

- The following UA IDs are used, but I (@chalin) don't know how they are being set up (probably via ReadTheDocs config):
  - global_analytics_code: `UA-17997319-1`
  - user_analytics_code: `UA-96283704-1` ([analytics console](https://analytics.google.com/analytics/web/#/report-home/a96283704w141907308p146451474))
- The main repo issue is https://github.com/cilium/cilium.io/issues/164

/cc @caniszczyk @nate-double-u

[gtag.js]: https://developers.google.com/analytics/devguides/collection/gtagjs
[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by chalin** [comment]
Hi @aanm - yes, please reopen this issue. I'll be using it to track GA4 setup for the docs subdomain, which is distinct from the GA4 setup for the main (apex) domain. That is, the required tasks are different for each. Thanks.

**Comment by chalin** [comment]
I can confirm that the GA4 site tag has started receiving docs subdomain events for [docs.cilium.io/en/latest](https://docs.cilium.io/en/latest/):

> <img width="1157" alt="image" src="https://user-images.githubusercontent.com/4140793/209152031-cb2a2850-a47c-4a97-be3d-d406ce44d85f.png">

/cc @joestringer

**Comment by chalin** [comment]
FYI, only `/en/latest` and `/en/v1.13` pages are showing up in the analytics (the latter being new):

> <img width="701" alt="image" src="https://user-images.githubusercontent.com/4140793/216787984-6693fcbf-513a-4203-9789-ad468a90a480.png">

So no `/en/stable` or any other v1.x pages are being tracked yet.

**Comment by chalin** [comment]
I can confirm through the GA4 console that events are being processed for `latest`, `stable`, and `v1.13`.

I suspect that there will be no backport of the GA4 ID for versions older than v1.13? @qmonnet @joestringer can you confirm so that I can drop those older versions from my tracking table (and the opening comment of this issue). Thanks!

**Comment by qmonnet** [comment]
> I suspect that there will be no backport of the GA4 ID for versions older than v1.13?

Hi Patrice,
I was on leave at the time GA was introduced for the Cilium docs and haven't followed all of it closely, but looking at [Joe's comment here](https://github.com/cilium/cilium/pull/22220#issuecomment-1402447428), I'd say it depends on what we want. Backports don't seem to apply neatly, but with a bit of conflict-solving we can make it work, so it depends on how strong we want analytics for older branches (v1.11/v1.12) of the docs. What do you think?

**Comment by qmonnet** [comment]
I created https://github.com/cilium/cilium/pull/24066 and https://github.com/cilium/cilium/pull/24067 to backport to v1.11 and v1.12, respectively.

**Comment by chalin** [comment]
The following analytics data might help you decide which doc versions to backport. Here's the % of traffic (last 30 days) of docs.cilium.io, sorted by decreasing traffic:

Version | % docs traffic<br>(last 30 days)
-- | --
stable | 44.3
latest | 16.4
v1.12 | 13.2
v1.13 | 8.4
v1.9 | 4.2
v1.10 | 1.65
v1.11 | 1.4
v1.8 | 0.92
v1.7 | 0.15
v1.6 | 0.14
v1.5 | 0.03

What's your % cutoff?

Here's the data sorted by version:

| Version | % docs traffic |
|--|--|
stable | 44.3
latest | 16.4
v1.13 | 8.4
v1.12 | 13.2
v1.11 | 1.4
v1.10 | 1.65
v1.9 | 4.2
v1.8 | 0.92
v1.7 | 0.15
v1.6 | 0.14
v1.5 | 0.03

<img width="500" alt="image" src="https://user-images.githubusercontent.com/4140793/221841815-358eb55c-1368-4ea1-ab80-5ae2322958d2.png">

**Comment by qmonnet** [comment]
Thanks! I'm not involved myself in analytics beyond looking at what we need on the build side, so I don't really have an answer based on these figures. We only support (and backport to) three branches, currently 1.13 to 1.11, so it makes sense to me to have support on those, especially now that the PRs are in progress; but it's probably not necessary to add it unmaintained branches.

Cc @zacharysarah for your information.

**Comment by qmonnet** [comment]
@chalin The backport PRs for v1.11 and v1.12 were merged this morning, so you should now be able to receive GA events for the corresponding versions of the documentation.

**Comment by chalin** [comment]
Phew! Quite the effort to backport those changes! I can confirm that the GA4 ID is receiving events from the v1.11 and v1.12 docs, so we're all done here -- even the UA ID cleanup (via https://github.com/cilium/cilium.io/issues/248#issuecomment-1449789284). Thanks all for your collaboration! Closing.

(And "hi" to @zacharysarah!)

**Comment by xmulligan** [comment]
Thanks for all the help!
