### ISSUE TITLE
datapath: WireGuard host-to-host encryption follow ups

### ISSUE THREAD

**Issue by brb** [cilium/cilium#23032]
# v1.14 (release blockers)

- [x] Get rid of WG tests in `datapath_configuration.go`.
- [x] https://github.com/cilium/cilium/pull/25734

# v1.15

- [x] Fix fwd'ing of LB requests via `cilium_vxlan` (unencrypted) instead of `cilium_wg0` (https://github.com/cilium/cilium/pull/19401#discussion_r1066684763).

# v1.16

- [ ] Create and load `from-wireguard` instead  of `from-netdev` (https://github.com/cilium/cilium/pull/19401#discussion_r1066070869): https://github.com/cilium/cilium/issues/33676
- [ ] Extend `ci-e2e` to test for unencrypted LB traffic leakages.

**Comment by julianwiedmann** [comment]
@brb fyi, I opened https://github.com/cilium/cilium/issues/33676 to make this a bit more visible. Could you please open something similar for "Extend ci-e2e to test for unencrypted LB traffic leakages." ?

**Comment by brb** [comment]
Created https://github.com/cilium/cilium/issues/33690. We can close this.
