### ISSUE TITLE
gateway-api: Address already in use :8080

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#23082]
### Description

Cilium Operator wight Gateway API enabled fails to start due to the below error. The issue is due to internal metric server listening to port 8080, which might clash with existing port running in the cluster.

The fix should be to allow users to enable/disable/configure port number in Gateway API subsystem.

```
level=fatal msg="Failed to create gateway controller" error="error listening on :8080: listen tcp :8080: bind: address already in use" subsys=gateway-controller
```

This could be the case that operator is running on host network namespace, and then causes the port conflict.

Reported by: @knfoo

### Tasks

- [x] Provide the way to configure metric port
   - [x] sensible default number
   - [x] disable metric server by convention (e.g. using value as 0)
- [x] Update related docs https://docs.cilium.io/en/latest/operations/system_requirements/

### Cilium Version

1.13.rc4

### Relevant log output

```
level=fatal msg="Failed to create gateway controller" error="error listening on :8080: listen tcp :8080: bind: address already in use" subsys=gateway-controller
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kahirokunn** [comment]
@sayboras I am installing cilium with helm 1.13.0 and I am getting this error.

`level=fatal msg="Failed to create gateway controller" error="error listening on :8080: listen tcp :8080: bind: address already in use" subsys=gateway-controller`

Will it be released in the next patch? 👀

**Comment by kahirokunn** [comment]
I found your commitments.
I look forward to its release.
https://github.com/cilium/cilium/releases/tag/v1.14.0-snapshot.0

**Comment by sayboras** [comment]
This is backported to 1.13, and will be available in 1.13.1 patch release as well.

**Comment by kahirokunn** [comment]
It's great.
