### ISSUE TITLE
Cilium-health cleanups

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2318]
* [x] Remove not-yet-implemented bits from the API
* [x] Add documentation for cilium-health
* [x] Restart cilium-health when killed (extend `cilium-health/launch` and/or `pkg/launch`)
* [x] Don't overwrite newer samples (currently periodic sync may overwrite results of `--probe`)  (#2956)   
* [x] Garbage-collect results for nodes that have left the cluster (#5185)
* [x] Improve representation of HTTP connectivity issues (#3563, PR #6402)
* ~~`cilium-health` endpoint shouldn't respond to requests from other regular endpoints~~
* [ ] If any nodes or endpoints can't be reached in the cluster, `--probe` times out and does not print any output
* [ ] Distribute pings better across the interval
* [ ] Timestamps per individual probe rather than for all probes in the interval                                                              
* [ ] Limit timeout of each probe to ~1-2s rather than the full 60s interval
  * [ ] Update entries more promptly when connectivity is lost in this case (current worst case is almost 2xinterval)
* [ ] Allow cilium-health arguments in `cilium-health/launch` to be configured at runtime (#5713)
* [ ] Add gingko tests for IPv6 
* [ ] Trust IP addresses directly rather than resolving them?
  * https://github.com/cilium/cilium/blob/94c02bb85aee1fe9116a5b43b1b39160d355ee12/pkg/health/server/prober.go#L218
* [ ] Add unit tests

**Comment by joestringer** [comment]
I think that some of the above checkboxes are still valid caveats to the current implementation, but it's clear that @mrostecki and I are not focusing our attention on this at the moment, so I've unassigned us to reflect reality.

Anyone interested in investigating this is welcome to post questions below or on Slack to get pointers on how to work on improving the cluster connectivity checking.
