### ISSUE TITLE
Hubble: add option to sanitize sensitive L7 data from flows

### ISSUE THREAD

**Issue by rolinh** [cilium/cilium#23887]
Hubble has the capability of providing visibility on L7 protocols such as HTTP or Kafka. This [layer 7 protocol visibility](https://docs.cilium.io/en/stable/observability/visibility/#proxy-visibility) feature is opt-in and requires users to either create a L7 policy or to add explicit pod annotations to be enabled. [Layer 7 Hubble flows](https://github.com/cilium/cilium/tree/master/api/v1/flow#flow-Layer7), however, may contain sensitive information, for instance as part of some HTTP headers or in a URL itself.

Hubble should provide an option for users to decide which potentially sensitive L7 data to keep in Hubble flows and it should be finely configurable.

- [x] HTTP URL: sanitize user info part (ie the optional username and password details for a URL), on/off: #28848
- [x] HTTP URL: remove query and fragment part of a URL, on/off: #25746
- [x] HTTP Headers: use a list of allowed HTTP header fields. A default list (e.g. tracing related fields) could be provided. Any header not in the list will have it's value sanitized (the key should be preserved). #26724
- [x] Kafka: redact API key, on/off: #25844 
- [ ] DNS: probably nothing to do.

**Comment by ioandr** [comment]
Hi @rolinh,

we would like to take a stab on this with https://github.com/ChrsMark/, maybe we could split the items you listed. 

Looking at the codebase we understand that we need to extend Hubble's [Layer 7 parser](https://github.com/cilium/cilium/tree/main/pkg/hubble/parser/seven) and implement the described logic there. This is similar to how Hubble's Layer 7 parser already redacts the user's password to not include it in the network flow. Does this hold?

Thanks!

**Comment by rolinh** [comment]
Hi @ioandr,

> we would like to take a stab on this with @ChrsMark, maybe we could split the items you listed.

Nice! I'm happy to create sub-issues if that helps but we can otherwise simply add your github handle next to each of the task.

> Looking at the codebase we understand that we need to extend Hubble's [Layer 7 parser](https://github.com/cilium/cilium/tree/main/pkg/hubble/parser/seven) and implement the described logic there. This is similar to how Hubble's Layer 7 parser already redacts the user's password to not include it in the network flow. Does this hold?

Yes, that's the way to do it indeed.

Thanks for your contributions!

**Comment by ioandr** [comment]
Hi @rolinh 

we would like to continue working on the rest of the items listed in https://github.com/cilium/cilium/issues/23887#issue-1591929009 so that we can deliver the whole L7 redaction/sanitization feature in Hubble.

At your convenience please advise on the following items to make sure we are on the same page and we start with the implementation:

1. **Redact HTTP password**: in https://github.com/cilium/cilium/pull/25844#issuecomment-1600791036 @kaworu suggested that redaction of HTTP passwords should be configurable. This makes sense and seems to be aligned with what we did for Kafka API key and URL query parameters. As @ChrsMark suggested in https://github.com/cilium/cilium/pull/25844#issuecomment-1600807415 we can configure Hubble to redact HTTP passwords by default - if you agree we add an extra item in the description of the current issue for this as it came up as a follow-up.
2. **Sanitize user info part in URL**: we interpret sanitize here as:
    - username: ensure lowercase, check for disallowed/suspicious special characters (https://xkcd.com/327/ :grimacing:)
    - password: ensure minimum length, check for standard values that one should avoid (e.g., "root", "admin", "12345", etc.)
3. **Sanitize HTTP headers**: we understand that Hubble should maintain a list of "trusted" HTTP headers that it does not need to sanitize. Then. Hubble should sanitize the value of any other header it captures in L7 flows, leaving its key unchecked/untouched. Similar to 2, we interpret sanitize here as:
    - HTTP header value: check for max length, check for disallowed/suspicious special characters

Maybe we could keep sanitization logic in a single place and reuse it from multiple places. Other than the above, it seems that Envoy itself provides a list of HTTP headers that it potentially sanitizes:

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_sanitizing

Maybe we could get some inspiration from this, given that Cilium itself [ships with Envoy](https://docs.cilium.io/en/latest/security/network/proxy/envoy/#envoy).

We are looking forward to your thoughts on the above - once again, we can split tasks with ChrsMark

**Comment by kaworu** [comment]
Thanks @ioandr for the detailed comment!


> 1. **Redact HTTP password**: in [Hubble: improve security by adding an option to redact API key in Kafka requests (L7) #25844 (comment)](https://github.com/cilium/cilium/pull/25844#issuecomment-1600791036) @kaworu suggested that redaction of HTTP passwords should be configurable. This makes sense and seems to be aligned with what we did for Kafka API key and URL query parameters. As @ChrsMark suggested in [Hubble: improve security by adding an option to redact API key in Kafka requests (L7) #25844 (comment)](https://github.com/cilium/cilium/pull/25844#issuecomment-1600807415) we can configure Hubble to redact HTTP passwords by default - if you agree we add an extra item in the description of the current issue for this as it came up as a follow-up.

Sounds good to me but again, I'd like some consistency around defaults. In my view, both Kafka API keys and HTTP passwords are secrets (in every context) and we should apply the same default redact policy. Redacting Kafka API keys by default would be the less intrusive option as changing the default for HTTP password would be a kind of "breaking change" and has security implications.

Agree that the issue description is lacking in terms of what "sanitize" means concretely. In my opinion: because at the Hubble level we don't know in which context theses value are going to be used we shouldn't modify them. It's up to consumers inserting into a SQL database to take the usual precautions about theses tainted values, so should do consumers generating HTML, printing to a Terminal, etc. cc @rolinh to clarify the intent.

> […] t seems that Envoy itself provides a list of HTTP headers that it potentially sanitizes:
> 
> https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_sanitizing

While the list is interesting, I think it covers a different use-case. In a reverse-proxy setup (edge node / front-proxy in Envoy documentation) it is critical to "sanitize" some headers (e.g. `x-forwarded-for`) while passing other as-is (e.g. `authentication`). In the Hubble case we should do nothing about the former but care about the latter (since it can include sensitive information, e.g. JWT or user/password).

**Comment by ioandr** [comment]
> Sounds good to me but again, I'd like some consistency around defaults. In my view, both Kafka API keys and HTTP passwords are secrets (in every context) and we should apply the same default redact policy. Redacting Kafka API keys by default would be the less intrusive option as changing the default for HTTP password would be a kind of "breaking change" and has security implications.

With @ChrsMark we agree on this, so we can do the following:

1. Expose a new option to redact HTTP password and enable it by default
2. Modify the existing option to redact Kafka API key to enable it by default
3. Leave the existing option to redact URL query params as is (disabled by default)

I can send a small, dedicated PR for 1 and 2 listed above.

> Agree that the issue description is lacking in terms of what "sanitize" means concretely.
>
> While the list is interesting, I think it covers a different use-case

Regarding sanitization let's wait for some feedback by @rolinh who originally opened the issue to decide how we will move forward.

**Comment by ChrsMark** [comment]
Thanks @rolinh! Makes sense to me. 

Regarding the http-headers' redaction: how about instead of defining the allowed headers, to define the list of "sensitive" headers to be redacted (optionally)?

The following headers could be those we can start with and ofc we can extend:
- `Authorization`
- `Proxy-Authorization`
- `Cookie`
- `Set-Cookie`
- `X-Vault-Token`
- `X-Auth-Token`
- `X-Forwarded-Client-Cert`

**Comment by rolinh** [comment]
> Regarding the http-headers' redaction: how about instead of defining the allowed headers, to define the list of "sensitive" headers to be redacted (optionally)?

I'd strongly prefer to have users to provide a list of allowed headers rather than a list of headers to redact. The reason being that there could be a lot of custom headers and what not that aren't covered and it would give a false sense of security ("secrets are sanitized, it's safe to share the L7 flows"). I think it's simply not possible to be exhaustive. On the other hand, if a header not on the allow-list is redacted, it's easy to add it to the list. This implies that we need to keep all header keys and only redact header values which seems totally fine to me.

**Comment by chancez** [comment]
@rolinh @ChrsMark it seems to me that given the variance in headers, we shouldn't be hardcoding headers to keep/redact, instead it should be user supplied. So rather than a boolean option, as it is in #26724 , it would be a list of headers to either redact/keep.

**Comment by ChrsMark** [comment]
Thanks for the feedback @chancez and @rolinh!

Just to verify what was suggested at https://github.com/cilium/cilium/issues/23887#issuecomment-1632167762, would that mean that we need to change the format of the `hubble-redact` flags/settings?

So far we have the following:
```
--hubble-redact=kafa-api-key
--hubble-redact=http-basic-auth-password
--hubble-redact=http-url-query
```
or in terms of values as
```yml
hubble:
 redact:
  - http-url-query
  - kafka-api-key
```


So would your proposal @rolinh mean that we need to change the schema to sth like the following:
```
--hubble-redact=true
--hubble-redact-http-user-info=true
--hubble-redact-http-url-query=true
--hubble-redact-http-headers-allow=foo,bar,baz
--hubble-redact-kafka-api-key=true
```

**Comment by chancez** [comment]
@ChrsMark Correct, that looks reasonable.

**Comment by rolinh** [comment]
@ChrsMark Given that #25746 made it to the v1.14 branch but #25844 did not and that we have plan to rework the values file, I suggest to pull #25746 out of the v1.14 branch. I believe this would provide a better experience than shipping only a portion of this meta issue. If we ship in v1.14 and then change the values options, we'll also have to deprecate in the next version which mean the whole improvement would land in v1.16 only.

**Comment by ChrsMark** [comment]
Yes @rolinh let's do it like this and revert https://github.com/cilium/cilium/pull/25844 from `v1.14` branch.

**Comment by ChrsMark** [comment]
Hey folks. I have filed https://github.com/cilium/cilium/pull/26989 to implement the discussed changes.

For now, only the `http-query` and `kafka-api-key` options will be supported.
I suggest that once we finalize and merge https://github.com/cilium/cilium/pull/26989 we will update https://github.com/cilium/cilium/pull/26724 to implement the http-headers part and @ioandr can add the `http-userInfo` part in a different PR. The default values' logic will be discussed separately in these follow-up PRs.

@rolinh @chancez let me know what you think :).

**Comment by ChrsMark** [comment]
A heads-up on this one.

Now that https://github.com/cilium/cilium/pull/27553 has been merged, we can resume the work on the following pending tasks:

1) We'll be adding an option to configure the redaction of HTTP passwords, as discussed in more detail here: https://github.com/cilium/cilium/issues/23887#issuecomment-1614840591. -> @ioandr. 

2) The default values of all options related to redaction will be revisited. The aim is to simplify the process by making `redact.enabled=true` sufficient for users who don't require specific fine-tuning. This discussion took place in the comments here: https://github.com/cilium/cilium/issues/23887#issuecomment-1614840591 and https://github.com/cilium/cilium/pull/27553#discussion_r1308873115. -> @ioandr 

3) Resume the work on the http headers redact https://github.com/cilium/cilium/pull/26724: -> @ChrsMark 

@ioandr and everyone feel free to add anything that I might miss here.

**Comment by ioandr** [comment]
Hey there, it seems that the only pending item to close this is to add business logic to control whether we redact the user info part from URLs, if present.

I have started working on this however I bumped into some unexpected behavior that I describe in https://github.com/cilium/cilium/issues/28798. As soon as we build context around it and have a way forward I should be able to proceed and file a PR to:

> Expose a new option to redact HTTP password and enable it by default

CC @rolinh @ChrsMark
