### ISSUE TITLE
CiliumCIDRGroup followups

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#24801]
Following the merge of https://github.com/cilium/cilium/pull/24638.

```[tasklist]
- [ ] https://github.com/cilium/cilium/issues/25123
- [ ] https://github.com/cilium/cilium/issues/25122
- [ ] https://github.com/cilium/cilium-cli/pull/1494
- [ ] https://github.com/cilium/cilium-cli/issues/1538
- [x] Address https://github.com/cilium/cilium/pull/24638#discussion_r1162170243
- [x] Address https://github.com/cilium/cilium/pull/24638#discussion_r1166015858
- [ ] https://github.com/cilium/cilium/issues/25020
- [ ] https://github.com/cilium/cilium/issues/25022
- [ ] https://github.com/cilium/cilium/issues/38939
```

**Comment by christarazi** [comment]
I agree we made some progress but there are still tasks that are not complete in the root comment. Documentation and testing are also a key missing aspects.

**Comment by JonasKs** [comment]
Hi @christarazi , would https://github.com/cilium/cilium/issues/31768#issuecomment-2230206761 be appropriate to add to this list? Currently selectors cannot be used.

**Comment by christarazi** [comment]
Sure, please do

**Comment by squeed** [comment]
I believe we can close this and mark CiliumCIDRGroup as GA in v1.17

**Comment by squeed** [comment]
One last outstanding task: need to move CCG out of the v2alpha1 api group.

**Comment by JonasKs** [comment]
I would like selectors to be implemented, but im not sure of the constraints of promoting to GA.

**Comment by BenoitKnecht** [comment]
@squeed I would just like to draw attention to the issue linked above, as it seems to me that marking this feature as GA while it's unresolved would probably lead to a lot of users breaking their deployments in unexpected ways.
