### ISSUE TITLE
High-scale IPcache mode followups

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#25370]
```[tasklist]
- [ ] Document named ports as not supported in high-scale ipcache mode
- [ ] Address https://github.com/cilium/cilium/pull/25148#discussion_r1181932754
- [ ] Address https://github.com/cilium/cilium/pull/25148#discussion_r1181933806
```
