### ISSUE TITLE
IPAM Multi-Pool Follow-ups

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#25470]
This issue tracks the remaining work items around the Multi-Pool IPAM mode:

- [x] https://github.com/cilium/cilium/pull/24248
- [x] https://github.com/cilium/cilium/pull/24247
- [x] https://github.com/cilium/cilium/pull/22762
- [x] https://github.com/cilium/cilium/pull/25498
- [x] Add IPPool CRDs ([ippool-crd](https://github.com/tklauser/cilium/tree/pr/tklauser/ippool-crd) branch)
  - PR: https://github.com/cilium/cilium/pull/25824
- [x] Add mechanism to determine a workloads IPAM pool based on pod and/or namespace annotations ([Slack thread](https://cilium.slack.com/archives/C2B917YHE/p1683892314962849))
   - PR: https://github.com/cilium/cilium/pull/25511
- [x] https://github.com/cilium/cilium/pull/25765
- [x] https://github.com/cilium/cilium/pull/25991
- [x] Add documentation around how to configure and use multi-pool IPAM mode
   - [x] https://github.com/cilium/cilium/pull/25767
   - [x] https://github.com/cilium/cilium/pull/26308
      - [x] Document limitations
         - [x] Overlapping IPAM pools are not supported due to IPCache limitations
         - [x] Tunnel mode not supported (related https://github.com/cilium/cilium/issues/20170)
         - [x] IPSec not supported
         - [x] Legacy Masquerading not supported (related https://github.com/cilium/cilium/issues/22273)
         - [x] kvstore not supported https://github.com/cilium/cilium/pull/26662
   - [x] Add kind-based workflow for e2e test https://github.com/cilium/cilium/pull/26175
 - [x] Collect `CiliumPodIPPool` resources in `cilium sysdump`
   - [x] https://github.com/cilium/cilium-cli/pull/1726

Best effort/cleanup:
 - [x] Convert to `netip.Prefix` earlier in allocator code https://github.com/cilium/cilium/pull/25991#discussion_r1222850011
   - PR: https://github.com/cilium/cilium/pull/26138
 - [x] Fix issue where IP owner of non-default pool IPs does not show up in `cilium status --verbose` (PR https://github.com/cilium/cilium/pull/27968)
 - [x] Fix bug where `auto-direct-node-routes` parses spec.podCIDR in multi-pool IPAM mode (PR https://github.com/cilium/cilium/pull/26663)
 - [ ] Add check to ensure IPAM pools don't overlap
 - [x] Fix bug where Cilium agent would release CIDRs it considers unused because the endpoints using them weren't restored yet. (PR https://github.com/cilium/cilium/pull/26668)
 - [ ] Fix bug where `status.ipam.operator-status.error` is not cleared after a successful allocation. To reproduce, create Cilium installation without `default` pool, create default pool after one minute, observe nodes successfully allocating pod CIDRs from default pool, but `cannot allocate from non-existing pool: default` error is not cleared https://github.com/cilium/cilium/issues/28758
 - [ ] https://github.com/cilium/cilium/issues/26966
 - [x] https://github.com/cilium/cilium/issues/26937
 - [x] https://github.com/cilium/cilium/issues/27417

**Comment by chestack** [comment]
multiple CIDRs per cluster/node is a highly useful feature, especially for workloads from different tenants. Are there any plans to enable this feature for cloud-related(ENI, Alibaba...) ipam modes?

**Comment by gandro** [comment]
> multiple CIDRs per cluster/node is a highly useful feature, especially for workloads from different tenants. Are there any plans to enable this feature for cloud-related(ENI, Alibaba...) ipam modes?

Not at the moment, there are no plans to support cloud-based IPAM modes. 

One difficulty in particular is that this will require deeper changes to the protocol between cilium-operator and per-node cilium-agent in ENI mode, as at the allocation mechanism for ENI modes and multi-pool work fundamentally different. In ENI mode, the operator decides when and how many IPs a node receives, where as with multi-pool, the agent issues an explicit request. There are multiple options to explore, but such a change requires a design document first.

**Comment by chaunceyjiang** [comment]
Hi @gandro It seems to me that `Add check to ensure IPAM pools don't overlap` has not been implemented yet. Is that correct? I would like to take up this issue.

**Comment by gandro** [comment]
> Hi @gandro It seems to me that `Add check to ensure IPAM pools don't overlap` has not been implemented yet. Is that correct? I would like to take up this issue.

Yes, that has not yet been implemented. Any help here is very much appreciated :tada: !
I've added a note about it in https://github.com/cilium/cilium/issues/26966 but it can be implemented separately. 

One issue with it is that we're not sure how to best address it:
- I don't think we can check this with [CEL](https://kubernetes.io/docs/reference/using-api/cel/), since it is a cross-resource check.
- Maybe we could do it via webhooks, but that's not something we can install via `helm install`
- Maybe we could have a check in the operator? The question is how we expose/reject conflicting pools. A simple version is to just log it as an error, but this will probably not be seen by most users. A more sophisticated version could extend the CiliumPodIPPool CRD with a status field, where we then write an error into the `status` field of the resource. We could then also teach the operator to not use such pools for allocation. 

I'm very open to other ideas as well!

**Comment by chaunceyjiang** [comment]
Perhaps we can build a webhook into `operator`. Similar to https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation

**Comment by gandro** [comment]
> Perhaps we can build a webhook into `operator`. Similar to https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation, This way, we don't need to install an additional webhook-server.

Ah, good point. Yeah, I think we have discussed a `ValidatingAdmissionWebhook` inside the operator in the past too, it would e.g. also be useful for https://github.com/cilium/cilium/issues/23152 - but I think there are some operational concerns about webhooks too (e.g. https://github.com/cilium/cilium/issues/23152#issuecomment-1396838137).

I'm not part of `sig-k8s`, so don't feel like I have the expertise to judge how complicated/tricky a webhook solution could be. On the other hand, having something which is opt-in might also allow us to gain a bit of experience with this. 
It seems to me that adding webhook infrastructure might be something that warrants a CFP.

**Comment by chaunceyjiang** [comment]
> ut I think there are some operational concerns about webhooks too (e.g. https://github.com/cilium/cilium/issues/23152#issuecomment-1396838137).

Oh, you are right.

**Comment by bewing** [comment]
Is there a way to monitor/dashboard 

1.  The percentage of an multi-pool pool that has been allocated to nodes
2.  The total overall usage (IPs assigned to pods) for a given pool?

**Comment by gandro** [comment]
> Is there a way to monitor/dashboard
> 
>     1. The percentage of an multi-pool pool that has been allocated to nodes
> 
>     2. The total overall usage (IPs assigned to pods) for a given pool?

I don't think these metrics exist at the moment (one of the reason why the feature is still beta), I think we would accept PRs providing this
