### ISSUE TITLE
Label-based egress support: datapath implementation

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2553]
Parent: #1488 

Augment the BPF datapath to be able to handle label-based egress. This will consist of reading from a table that is populated by the Cilium agent with pod IPs to which egress traffic is allowed. 

* [x] Add an IP->SecID mapping table to BPF (#2954)
* [x] Add Label-based lookup to the map, following the example of ingress policy map (#2954)
* [x] Refactor the existing L4 port policy from code to a native BPF map (L4-only)  (#2918)
* Extra wishlist items, but not required to implement:
  * [ ] Userspace - populate maps with `proxy_port` (#2564)
  * [ ] Userspace - atomic map replace

**Comment by ianvernon** [comment]
Assigning to @joestringer after discussion with @tgraf . This ticket will be updated over time as the design fleshes out.
