### ISSUE TITLE
Validate, complete & test network policy model

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2594]
Meta issue to capture all efforts around policy enforcement validation, testing and completion.

Immediate fixes:
 - Verification of connection tracking cleanup on policy change:
    - [x] Resolve known issues regarding connection tracking cleanup (@aanm)
        - [x] #2569
     - [x] Resolve datapath issues (@joestringer)
         - [x] #2270 
         - [x] #2056

Document policy specification
  - [ ] Design desired policy specification (@tgraf)
  - [ ] Resolve eventual delta of current implementation to documented policy spec
    - Datapath implementation review: https://github.com/cilium/cilium/issues/3004

Kubernetes:
 - [x] Document delta from Cilium spec to Kubernetes spec
 - [x] Verify and document conformance of Kubernetes NetworkPolicy resource #2942 

Documentation:
 - [x] #2301

CI:
 - [x] #2337
 - [x] #2258
 - [x] #1953

Egress enforcement:
 - [x] Label based egress enforcement (#1488, @ianvernon)
 - [x] Label based service egress #1875

Bugs:
 - [x] #2571
 - [x] #2564 
 - [x] #2415
 - [x] #2199
 - [x] #2053

Proposals:
 - [ ] #2292
 - [x] #2095
 - [x] #1997
 - [x] #1940
 - [x] Policy enforcement to/from service (#1582)
 - [x] #2568

L7:
 - [x] Policy tracing capability #2276
 - [x] Higher level kafka policy specification (#1818)

**Comment by manalibhutiyani** [comment]
Should be add : #2568 in the list?

**Comment by tgraf** [comment]
> Should be add : #2568 in the list?

Add & edit any issue that is related to this effort

**Comment by tgraf** [comment]
Reviewed in context of 1.0. No blockers remaining, reducing severity.

**Comment by ianvernon** [comment]
Removing needs-backport/1.1 label - this is more of a 'meta' issue - things that are related to this can be backported on a case-by-case basis.

**Comment by tgraf** [comment]
This is obsolete by now. Closing.
