### ISSUE TITLE
Testing Follow-ups for BPF-based IPv6 Masquerading

### ISSUE THREAD

**Issue by qmonnet** [cilium/cilium#26074]
Follow-ups for https://github.com/cilium/cilium/pull/23165:

- [x] Add support for the ip-masq-agent
  - PR: https://github.com/cilium/cilium/pull/23219

- [x] Fix ip-masq-agent
  - Issue: https://github.com/cilium/cilium/issues/26262
  - PR: https://github.com/cilium/cilium/pull/26435

- [x] Look into the Host Firewall code and figure out how to run it with BPF IPv6 masquerading. What happens if we have masquerading enable for both IP versions? For one IP version only?
  - Context: https://github.com/cilium/cilium/pull/23165#discussion_r1222689761
  - After addressing it we want to lift the restriction on using BPF IPv6 Masquerading and Host Firewall in `daemon/cmd/daemon_main.go` and in the description of the conformance-e2e workflow
  - PR: https://github.com/cilium/cilium/pull/26323

- [x] Rework `snat_v6_needed()` in bpf/lib/nat.h to bring it closer to `snat_v4_prepare_state()`
  - Context: https://github.com/cilium/cilium/pull/23165#discussion_r1222700605
  - PR: https://github.com/cilium/cilium/pull/26236

- [x] Rework error handling from `ipv6_hdrlen()` and `ct_is_reply6()` in `snat_v6_needed()`, and `ct_is_reply4()` in `snat_v4_prepare_state()`
  - Context: https://github.com/cilium/cilium/pull/23165#discussion_r1222701356
  - PR: https://github.com/cilium/cilium/pull/26501

- [ ] Add BPF integration tests (`bpf/tests/`) for IPv6 Masquerading

- [ ] Enable IPv6 masquerading tests in `datapath_configuration.go` with KPR/BPF masquerading
  - PR: https://github.com/cilium/cilium/pull/26500

- [x] Lift BPF host routing for per-endpoint-routes wrt IPv6 support (for 1.14)
  - PR: https://github.com/cilium/cilium/pull/26205

- [x] IPv6 BIG TCP documentation: fix up ipv6 masquerade=false.. can be removed now
  - PR: https://github.com/cilium/cilium/pull/26172/

- [ ] Once the ip-masq-agent fixes are merged, find a way to move the new test away from Ginkgo

- [x] Mark IPv6 BPF Masquerading as Beta in documentation
  - PR: https://github.com/cilium/cilium/pull/26499

- [x] Investigate and fix https://github.com/cilium/cilium/issues/26816
  - [Likely not related](https://github.com/cilium/cilium/issues/26816#issuecomment-1749102170)

Now that the 1.15 development cycle has started:

- [x] Lift restriction from d6f4c53ba443c63ed22283caf8e9088b99979c49
  - PR: https://github.com/cilium/cilium/pull/27114

- [ ] Get out of Beta

To investigate:

- [ ] https://github.com/cilium/cilium/issues/26074#issuecomment-2830029975

**Comment by julianwiedmann** [comment]
@qmonnet fyi, we recently landed https://github.com/cilium/cilium/pull/28813. I *think* that was the main/only concern regarding HostFW + IPv6 ... and it was only relevant when **not** using BPF Masquerading.

So we might be able to just simply remove the HostFW + IPv6 BPF-masq restriction in `daemon_main.go` ...

**Comment by qmonnet** [comment]
Ack, I'll take another look when I can. Thanks for the heads-up!

**Comment by julianwiedmann** [comment]
I ticked off `Look into the Host Firewall code and figure out how to run it with BPF IPv6 masquerading`, based on https://github.com/cilium/cilium/pull/31511.

**Comment by qmonnet** [comment]
I've lost some of the context because it's been some time, but I note that https://github.com/cilium/cilium/pull/39084 will likely remove from CI a test for IPv6 masquerading that hasn't been running for some time (`K8sDatapathConfig IPv6 masquerading across K8s nodes, skipped due to native routing CIDR`). Might be worth looking into whether it's necessary to update and re-enable, or fix, at some point.
