### ISSUE TITLE
Testing in preparation for v1.14.0

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#26536]
Process to add tasks below. Create issues as necessary to describe steps to close the testing gap:
- [x] Crowdsource any areas we think that Cilium could benefit from additional manual testing prior to release.
- [x] Identify new getting started guides.
- [x] Check for deprecated settings, how those may impact existing docs / GSGs.
- [x] Identify top 5 critical guides to validate.

If you have any areas of concern to validate prior to the v1.14 release, please add a task to this issue and/or comment below.

```[tasklist]
### Tasks
- [ ] https://github.com/cilium/cilium/issues/26932
- [ ] https://github.com/cilium/cilium/issues/26651
- [x] Clarify OpenShift guide
- [ ] https://github.com/cilium/cilium/issues/26926
- [ ] https://github.com/cilium/cilium/issues/26927
- [ ] https://github.com/cilium/cilium/issues/26928
- [ ] https://github.com/cilium/cilium/issues/26929
- [ ] https://github.com/cilium/cilium/issues/26930
- [ ] https://github.com/cilium/cilium/issues/26931
```

**Comment by clay-moss** [comment]
Hello 👋 I can assist with review/testing.

**Comment by aanm** [comment]
The "Test mutal-auth demo from GSG" was successful. Closing since the "Test mutal-auth demo from GSG on EKS" is not part of the v1.14.0
