### ISSUE TITLE
Test quick install with 1.14.0-rc.1

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#26926]
```[tasklist]
### Tasks
- [x] Install Cilium 1.14.0-rc.1
- [x] Quick install  [getting started guide on Minikube](https://docs.cilium.io/en/v1.14/gettingstarted/k8s-install-default/)
- [x] [Enable hubble](https://docs.cilium.io/en/v1.14/gettingstarted/hubble_setup/)
- [x] Run the [star wars demo](https://docs.cilium.io/en/v1.14/gettingstarted/demo/#starwars-demo)
```

**Comment by mathpl** [comment]
@clay-moss can you test this guide? If you need a hand @tommyp1ckles should be able to help.

**Comment by clay-moss** [comment]
Sure thing @mathpl

**Comment by clay-moss** [comment]
All tasks completed succesfully:

```bash
cmoss@macbook ▸ ~
↳ minikube version
minikube version: v1.30.1
commit: 08896fd1dc362c097c925146c4a0d0dac715ace0
```

```bash
# minikube cluster setup

cmoss@macbook ▸ ~
↳ minikube start --network-plugin=cni --cni=false
* minikube v1.30.1 on Darwin 13.4.1 (arm64)
* Automatically selected the docker driver. Other choices: qemu2, ssh
! With --network-plugin=cni, you will need to provide your own CNI. See --cni flag as a user-friendly alternative
* Using Docker Desktop driver with root privileges
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* minikube 1.31.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.31.0
* To disable this notice, run: 'minikube config set WantUpdateNotification false'

* Downloading Kubernetes v1.26.3 preload ...
    > preloaded-images-k8s-v18-v1...:  330.52 MiB / 330.52 MiB  100.00% 9.44 Mi
    > gcr.io/k8s-minikube/kicbase...:  336.39 MiB / 336.39 MiB  100.00% 5.73 Mi
* Creating docker container (CPUs=2, Memory=7803MB) ...
* Preparing Kubernetes v1.26.3 on Docker 23.0.2 ...
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v5
* Enabled addons: storage-provisioner, default-storageclass
* Verifying Kubernetes components...
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

```

```bash
cmoss@macbook ▸ ~
↳ cilium version --client
cilium-cli: enterprise/cilium-cli/v0.15.2-cee.1 compiled with go1.20.2 on darwin/amd64
cilium image (default): v1.13.4
cilium image (stable): v1.13.4
```


```bash
# installing cilium

cmoss@macbook ▸ ~
↳ cilium install --version v1.14.0-rc.1
🔮 Auto-detected Kubernetes kind: minikube
✨ Running "minikube" validation checks
✅ Detected minikube version "1.30.1"
ℹ️  Using Cilium version 1.14.0-rc.1
🔮 Auto-detected cluster name: minikube
🔮 Auto-detected datapath mode: tunnel
🔮 Auto-detected kube-proxy has been installed
```

```bash
# cilium installed successfully

cmoss@macbook ▸ ~
↳ cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       disabled
    \__/       ClusterMesh:        disabled

Deployment             cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet              cilium             Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium             Running: 1
                       cilium-operator    Running: 1
Cluster Pods:          1/1 managed by Cilium
Helm chart version:    1.14.0-rc.1
Image versions         cilium-operator    quay.io/cilium/operator-generic:v1.14.0-rc.1@sha256:36e0d2d4ba8f35031b65d0703a74e1dd68253589479f7007f84b245bc6ebc410: 1
                       cilium             quay.io/cilium/cilium:v1.14.0-rc.1@sha256:47c403975508dcf0f53f801f1fd0cf0804d4dc656ee01a136bd3805ed2ec14bb: 1
```

```bash
cmoss@macbook ▸ ~
↳ k get pods -A
NAMESPACE     NAME                               READY   STATUS    RESTARTS      AGE
kube-system   cilium-operator-58f54cd7f7-6z6kt   1/1     Running   0             7m45s
kube-system   cilium-r6hbd                       1/1     Running   0             7m45s
kube-system   coredns-787d4945fb-fvd6p           1/1     Running   0             7m11s
kube-system   etcd-minikube                      1/1     Running   0             34m
kube-system   kube-apiserver-minikube            1/1     Running   0             34m
kube-system   kube-controller-manager-minikube   1/1     Running   0             34m
kube-system   kube-proxy-sx866                   1/1     Running   0             34m
kube-system   kube-scheduler-minikube            1/1     Running   0             34m
kube-system   storage-provisioner                1/1     Running   1 (33m ago)   34m
```

The enable hubble step didnt output any text/emojis as shown in the OSS docs, although I was using the Cilium EE CLI.

```bash
# enable hubble

cmoss@macbook ▸ ~
↳ cilium hubble enable
```

```bash
# hubble enabled successfully

cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

Deployment             hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Deployment             cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet              cilium             Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium-operator    Running: 1
                       cilium             Running: 1
                       hubble-relay       Running: 1
Cluster Pods:          2/2 managed by Cilium
Helm chart version:    1.14.0-rc.1
Image versions         cilium             quay.io/cilium/cilium:v1.14.0-rc.1@sha256:47c403975508dcf0f53f801f1fd0cf0804d4dc656ee01a136bd3805ed2ec14bb: 1
                       hubble-relay       quay.io/cilium/hubble-relay:v1.14.0-rc.1@sha256:51627988e5df034e2b7a6291ed06593d0bc12a54f01549a2f5c7db46adc1ecfe: 1
                       cilium-operator    quay.io/cilium/operator-generic:v1.14.0-rc.1@sha256:36e0d2d4ba8f35031b65d0703a74e1dd68253589479f7007f84b245bc6ebc410: 1
```

```bash
# star wars demo

kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.14/examples/minikube/http-sw-app.yaml
service/deathstar created
deployment.apps/deathstar created
pod/tiefighter created
pod/xwing created

cmoss@macbook ▸ ~
↳ kubectl get pods,svc
NAME                             READY   STATUS    RESTARTS   AGE
pod/deathstar-8464cdd4d9-77lgp   1/1     Running   0          6m31s
pod/deathstar-8464cdd4d9-qqg67   1/1     Running   0          6m31s
pod/tiefighter                   1/1     Running   0          6m31s
pod/xwing                        1/1     Running   0          6m31s

NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/deathstar    ClusterIP   10.110.155.101   <none>        80/TCP    6m31s
service/kubernetes   ClusterIP   10.96.0.1        <none>        443/TCP   93m

cmoss@macbook ▸ ~
↳ kubectl -n kube-system exec ds/cilium -- cilium endpoint list
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                  IPv6   IPv4         STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                                   
1          Disabled           Disabled          40937      k8s:app.kubernetes.io/name=deathstar                                                10.0.0.237   ready   
                                                           k8s:class=deathstar                                                                                      
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                   
                                                           k8s:io.cilium.k8s.policy.cluster=minikube                                                                
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                          
                                                           k8s:io.kubernetes.pod.namespace=default                                                                  
                                                           k8s:org=empire                                                                                           
15         Disabled           Disabled          4919       k8s:app.kubernetes.io/name=hubble-relay                                             10.0.0.141   ready   
                                                           k8s:app.kubernetes.io/part-of=cilium                                                                     
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system                               
                                                           k8s:io.cilium.k8s.policy.cluster=minikube                                                                
                                                           k8s:io.cilium.k8s.policy.serviceaccount=hubble-relay                                                     
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                              
                                                           k8s:k8s-app=hubble-relay                                                                                 
66         Disabled           Disabled          40937      k8s:app.kubernetes.io/name=deathstar                                                10.0.0.18    ready   
                                                           k8s:class=deathstar                                                                                      
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                   
                                                           k8s:io.cilium.k8s.policy.cluster=minikube                                                                
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                          
                                                           k8s:io.kubernetes.pod.namespace=default                                                                  
                                                           k8s:org=empire                                                                                           
550        Disabled           Disabled          53646      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system          10.0.0.198   ready   
                                                           k8s:io.cilium.k8s.policy.cluster=minikube                                                                
                                                           k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                          
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                              
                                                           k8s:k8s-app=kube-dns                                                                                     
2309       Disabled           Disabled          1          k8s:minikube.k8s.io/commit=08896fd1dc362c097c925146c4a0d0dac715ace0                              ready   
                                                           k8s:minikube.k8s.io/name=minikube                                                                        
                                                           k8s:minikube.k8s.io/primary=true                                                                         
                                                           k8s:minikube.k8s.io/updated_at=2023_07_19T17_21_52_0700                                                  
                                                           k8s:minikube.k8s.io/version=v1.30.1                                                                      
                                                           k8s:node-role.kubernetes.io/control-plane                                                                
                                                           k8s:node.kubernetes.io/exclude-from-external-load-balancers                                              
                                                           reserved:host                                                                                            
2513       Disabled           Disabled          1717       k8s:app.kubernetes.io/name=tiefighter                                               10.0.0.81    ready   
                                                           k8s:class=tiefighter                                                                                     
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                   
                                                           k8s:io.cilium.k8s.policy.cluster=minikube                                                                
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                          
                                                           k8s:io.kubernetes.pod.namespace=default                                                                  
                                                           k8s:org=empire                                                                                           
2519       Disabled           Disabled          4          reserved:health                                                                     10.0.0.227   ready   
2931       Disabled           Disabled          7910       k8s:app.kubernetes.io/name=xwing                                                    10.0.0.177   ready   
                                                           k8s:class=xwing                                                                                          
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                   
                                                           k8s:io.cilium.k8s.policy.cluster=minikube                                                                
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                          
                                                           k8s:io.kubernetes.pod.namespace=default                                                                  
                                                           k8s:org=alliance                                                                                         

cmoss@macbook ▸ ~
↳ kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.14/examples/minikube/sw_l3_l4_policy.yaml
ciliumnetworkpolicy.cilium.io/rule1 created

cmoss@macbook ▸ ~
↳ kubectl exec tiefighter -- curl -s -XPOST deathstar.default.svc.cluster.local/v1/request-landing
Ship landed

cmoss@macbook ▸ ~
↳ kubectl exec xwing -- curl -s -XPOST deathstar.default.svc.cluster.local/v1/request-landing
command terminated with exit code 7

cmoss@macbook ▸ ~
↳ kubectl exec tiefighter -- curl -s -XPUT deathstar.default.svc.cluster.local/v1/exhaust-port
Panic: deathstar exploded

goroutine 1 [running]:
main.HandleGarbage(0x2080c3f50, 0x2, 0x4, 0x425c0, 0x5, 0xa)
        /code/src/github.com/empire/deathstar/
        temp/main.go:9 +0x64
main.main()
        /code/src/github.com/empire/deathstar/
        temp/main.go:5 +0x85

# maybe docs should use `kubectl create` instead at this step?

cmoss@macbook ▸ ~
↳ kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.14/examples/minikube/sw_l3_l4_l7_policy.yaml
Warning: resource ciliumnetworkpolicies/rule1 is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
ciliumnetworkpolicy.cilium.io/rule1 configured
```

```bash
# testing `cilium monitor` and `hubble observe`


cmoss@macbook ▸ ~
↳ kubectl exec -it -n kube-system cilium-r6hbd -- cilium monitor -v --type l7
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
Listening for events on 5 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
<- Request http from 2513 ([k8s:io.kubernetes.pod.namespace=default k8s:org=empire k8s:app.kubernetes.io/name=tiefighter k8s:class=tiefighter k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=minikube k8s:io.cilium.k8s.policy.serviceaccount=default]) to 1 ([k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default k8s:org=empire k8s:app.kubernetes.io/name=deathstar k8s:class=deathstar k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=minikube]), identity 1717->40937, verdict Denied PUT http://deathstar.default.svc.cluster.local/v1/exhaust-port => 0
<- Response http to 2513 ([k8s:io.cilium.k8s.policy.cluster=minikube k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default k8s:org=empire k8s:app.kubernetes.io/name=tiefighter k8s:class=tiefighter k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default]) from 1 ([k8s:app.kubernetes.io/name=deathstar k8s:class=deathstar k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=minikube k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default k8s:org=empire]), identity 40937->1717, verdict Forwarded PUT http://deathstar.default.svc.cluster.local/v1/exhaust-port => 403


kubectl exec -it -n kube-system cilium-r6hbd -- hubble observe
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
Jul 20 00:21:29.717: default/tiefighter:51513 (ID:1717) -> kube-system/coredns-787d4945fb-fvd6p:53 (ID:53646) to-endpoint FORWARDED (UDP)
Jul 20 00:21:29.717: default/tiefighter:51513 (ID:1717) <- kube-system/coredns-787d4945fb-fvd6p:53 (ID:53646) to-endpoint FORWARDED (UDP)
Jul 20 00:21:29.718: default/tiefighter:59102 (ID:1717) -> default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) policy-verdict:L3-L4 INGRESS ALLOWED (TCP Flags: SYN)
Jul 20 00:21:29.718: default/tiefighter:59102 (ID:1717) -> default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-proxy FORWARDED (TCP Flags: SYN)
Jul 20 00:21:29.718: default/tiefighter:59102 (ID:1717) <- default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-endpoint FORWARDED (TCP Flags: SYN, ACK)
Jul 20 00:21:29.718: default/tiefighter:59102 (ID:1717) -> default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-proxy FORWARDED (TCP Flags: ACK)
Jul 20 00:21:29.720: default/tiefighter:59102 (ID:1717) -> default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-proxy FORWARDED (TCP Flags: ACK, PSH)
Jul 20 00:21:29.720: 10.0.0.74:53118 (ID:1717) -> default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-endpoint FORWARDED (TCP Flags: SYN)
Jul 20 00:21:29.720: 10.0.0.74:53118 (host) <- default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-stack FORWARDED (TCP Flags: SYN, ACK)
Jul 20 00:21:29.720: 10.0.0.74:53118 (ID:1717) -> default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-endpoint FORWARDED (TCP Flags: ACK)
Jul 20 00:21:29.720: default/tiefighter:59102 (ID:1717) -> default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) http-request DROPPED (HTTP/1.1 PUT http://deathstar.default.svc.cluster.local/v1/exhaust-port)
Jul 20 00:21:29.720: default/tiefighter:59102 (ID:1717) <- default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) http-response FORWARDED (HTTP/1.1 403 0ms (PUT http://deathstar.default.svc.cluster.local/v1/exhaust-port))
Jul 20 00:21:29.720: 10.0.0.74:53118 (ID:1717) -> default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
Jul 20 00:21:29.720: 10.0.0.74:53126 (ID:1717) -> default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-endpoint FORWARDED (TCP Flags: SYN)
Jul 20 00:21:29.720: 10.0.0.74:53126 (host) <- default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-stack FORWARDED (TCP Flags: SYN, ACK)
Jul 20 00:21:29.720: 10.0.0.74:53126 (ID:1717) -> default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-endpoint FORWARDED (TCP Flags: ACK)
Jul 20 00:21:29.720: default/tiefighter:59102 (ID:1717) <- default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Jul 20 00:21:29.721: 10.0.0.74:53118 (host) <- default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-stack FORWARDED (TCP Flags: ACK, FIN)
Jul 20 00:21:29.721: 10.0.0.74:53118 (ID:1717) -> default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-endpoint FORWARDED (TCP Flags: ACK)
Jul 20 00:21:29.723: default/tiefighter:59102 (ID:1717) -> default/deathstar-8464cdd4d9-77lgp:80 (ID:40937) to-proxy FORWARDED (TCP Flags: ACK, FIN)
```

Cilium sysdump:

[cilium-sysdump-20230719-193604.zip](https://github.com/cilium/cilium/files/12101072/cilium-sysdump-20230719-193604.zip)
