### ISSUE TITLE
Remove reliance on `IPv4/IPv6AllocRange` in Cilium-Agent

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#27018]
Cilium-Agents IPv4/IPv6AllocRange is Cilium's internal representation of the local node's PodCIDR. The concept of a single allocation CIDR however is outdated, since in many IPAM modes (ENI, Azure, AlibabaCloud, MultiPool) there either is no PodCIDR to begin with (and pod IPs are allocated using a different scheme), or there are multiple PodCIDRs (in the case of MultiPool).

However, there is some of code still seems to assume a single pod CIDR per node such as IPSec, tunnel mode and parts of masquerading.

In addition, if no explicit pod CIDR is available, we simply auto-generate one, which also has been a recurring source of confusion and bugs, for example:

- https://github.com/cilium/cilium/issues/9409
- https://github.com/cilium/cilium/issues/22273
- https://github.com/cilium/cilium/pull/26397
- https://github.com/cilium/cilium/pull/25962#discussion_r1221093542

We should revisit all code assuming the existence of a local alloc CIDR, make sure it works in IPAM modes where this concept does not exist (or disallow the combination of the feature and the IPAM mode) and remove the fall-back on the auto-generated alloc CIDR.

### Tasks
- [x] Stop announcing the auto-generated pod CIDR in IPAM modes which are not based on a pod CIDR: https://github.com/cilium/cilium/pull/26663
- [ ] Audit remaining usages of IPv4/IPv6AllocRange in the agent and understand under what conditions they need to rely on the local alloc CIDR
- [ ] Fix remaining usages of IPv4/IPv6AllocRange to not rely on it if it is not available
- [ ] Remove auto-generation of  IPv4/IPv6AllocRange
- [ ] Determine if the auto-generated IPv6 alloc range is needed for exotic setups: https://github.com/cilium/cilium/pull/39917#issuecomment-2983040501

**Comment by oblazek** [comment]
can we add a no-stale?

**Comment by joamaki** [comment]
https://github.com/cilium/cilium/issues/41283 is related to the issues with the auto-generated cidrs.

**Comment by liyihuang** [comment]
we still see some auto generated cidr is used in https://github.com/cilium/cilium/pull/26663 when fixing in https://github.com/cilium/cilium/pull/42531. I dont know if we could really remove single IPv4/IPv6AllocRange in ENI, multi-pool and other ipam modes. Maybe we could have a slice than single field to resolve this type of the issue

**Comment by HadrienPatte** [comment]
FYI https://github.com/cilium/cilium/pull/48415/changes/655b57cf512a5d3a9848f8cf7f12c113dbd03e50
