### ISSUE TITLE
Document cilium-operator role in Service Mesh

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#27167]
Gateway API doesn't seem to be documented here, but the operator plays a role in implementing Gateway API:

https://docs.cilium.io/en/latest/internals/cilium_operator/#cilium-operator

```[tasklist]
### Tasks
- [ ] Document the operator's role in Gateway API
- [ ] Document Ingress role
- [ ] Document Mutual Authentication role
```
