### ISSUE TITLE
Update Azure docs to the current

### ISSUE THREAD

**Issue by tamilmani1989** [cilium/cilium#27289]
Creating this issue to update multiple azure docs to relevant based on this comment:

https://github.com/cilium/cilium/pull/27199#pullrequestreview-1561391819 

PR #27199 

```[tasklist]
### Tasks
- [ ] Add a new Azure CNI Powered by Cilium entry to External Installers and add delegated ipam section https://docs.cilium.io/en/latest/installation/external-toc/ @tamilmani1989
- [ ] Getting Started guide https://docs.cilium.io/en/latest/gettingstarted/k8s-install-default/. Rework the AKS tabs so that only instructions for BYOCNI remain. Completely remove Azure IPAM.  @tamilmani1989
- [ ] Helm guide https://docs.cilium.io/en/latest/installation/k8s-install-helm/. Update Getting started instructions for AKS @tamilmani1989
- [ ] IPAM guides https://docs.cilium.io/en/latest/network/concepts/ipam/. Rename Azure IPAM to Azure IPAM (Legacy)  @tamilmani1989
- [ ] Azure IPAM https://docs.cilium.io/en/latest/network/concepts/ipam/azure/. Rename  Azure IPAM page to Azure IPAM (Legacy) and reason out why its legacy @tamilmani1989
- [ ] CNI chaining guides https://docs.cilium.io/en/latest/installation/cni-chaining/. Rename Azure CNI to Azure CNI (Legacy). @vipul-21
- [ ] Azure CNI chaining https://docs.cilium.io/en/latest/installation/cni-chaining-azure-cni/.  @vipul-21
- [x] NodePort XDP on Azure https://docs.cilium.io/en/latest/network/kubernetes/kubeproxy-free/#nodeport-xdp-on-azure  @vipul-21
```

**Comment by tamilmani1989** [comment]
@nbusseneau all tasks have been completed and its ready for review 

https://github.com/cilium/cilium/pull/28286
https://github.com/cilium/cilium/pull/28571
https://github.com/cilium/cilium/pull/28685
https://github.com/cilium/cilium/pull/28910
https://github.com/cilium/cilium/pull/28933
https://github.com/cilium/cilium/pull/28946
https://github.com/cilium/cilium/pull/29091

**Comment by nbusseneau** [comment]
Thanks @tamilmani1989 I will review today or tomorrow :)

**Comment by joestringer** [comment]
Heads up that we're gearing up for v1.15.0-rc.0 next week. In preparation, we have enacted a feature freeze. However, for docs and Helm updates these changes may be exempt and allowed through. Glancing at the PR list above, I can't get a good gauge for the goals of each of the PR or any active discussion items, but if you would like to target these improvements in time for rc.0 so that users & developers can start testing the release candidate, then now would be a good time to try to coordinate landing them into the tree. Next step would probably be to identify what decisions we need to make to drive those PRs forward and coordinate with the reviewers to ensure that the PRs meet the quality bar. cc @tamilmani1989 @nbusseneau

**Comment by tamilmani1989** [comment]
Thanks @joestringer for bringing this up. @nbusseneau can you please review above PRs and let know. I marked all PRs ready for review.

**Comment by joestringer** [comment]
@tamilmani1989 sure. I would suggest making sure that the other PRs just mention this issue number, for example by using `Related: #27289` in the PR description. Otherwise any time any PR with `Fixes: #27289` gets merged, this issue will be closed again.

**Comment by tamilmani1989** [comment]
yep it was mentioned `Fixes: #27289` in every PR but not sure why it's being closed when you merged one of them. Also it shows 4 remaining pull requests in title section
