### ISSUE TITLE
Use kernel sockets list to relate traffic with initiating direction

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2805]
Background
---

Policy is defined upon a set of endpoints based on labels. When a user writes a policy to allow some kind of traffic to be admitted into/out of a set of endpoints, the policy is intended to allow not just the exact traffic that is specified, but to allow the connections for this traffic - ie, there's no use in allowing inbound traffic from A->B without also allowing the reverse traffic from B->A. We do not force users to be explicit about every 5- (or more) tuple to be allowed into the set of endpoints.

To allow this, we perform "connection-tracking". That is to say, when traffic flows into or out of an endpoint, the first thing we do is to determine whether we've seen the traffic before. 
* If we haven't seen this connection before, then we will perform a policy lookup and admit traffic depending on the whether the policy allowed it. If the policy allows the traffic, then we save the details of the connections (5tuple and some other misc attributes) into a map.
* When subsequent traffic for the connection arrives, this initial lookup will tell us which connection the traffic is associated with, and the original direction of this traffic. Based on the original direction of the connection, we apply policy and admit/deny the traffic based on this.

Description
---

The connection tracking map must be managed by the userspace Cilium daemon. 
* Due to BPF API restrictions, Cilium must determine the max number of 5tuples to track ahead of time. It's significantly disruptive to the datapath to modify this number.
* When this threshold is met, connections are dropped
* If the number is set globally, then a large number of connections for one endpoint may adversely affect connectivity to other endpoints. The number can be broken down to per-endpoint, but then the number (and therefore memory usage) is multipled by the number of endpoints on the node.
* Any time a policy changes, Cilium scans through the map to flush entries associated with connections that should no longer be admitted

Proposal
---

The kernel already tracks all relevant connections at the socket layer. If the primary piece of information we need to know is whether a particular set of traffic (identified by 5tuple) is corresponding to an inbound or outbound connection, so that we may apply the appropriate policy, then perhaps we can just reuse the kernel socket pool to retrieve this information instead. This alleviates the scaling concerns described in the problem description, because the datapath will no longer need to track connections.

Outline
---

* [x] Propose `bpf_sk_lookup()` function
  * RFC sent upstream: [submit/sk-lookup-rfc](http://github.com/joestringer/linux/tree/submit/sk-lookup-rfc)
  * v1 sent upstream: [submit/sk-lookup-v1](http://github.com/joestringer/linux/tree/submit/sk-lookup-v1)
  * v2 sent upstream: [submit/sk-lookup-v2](http://github.com/joestringer/linux/tree/submit/sk-lookup-v2)
  * v3 sent upstream: [submit/sk-lookup-v3](http://github.com/joestringer/linux/tree/submit/sk-lookup-v3)
  * v4 sent upstream: [submit/sk-lookup-v4](http://github.com/joestringer/linux/tree/submit/sk-lookup-v4)
  * Merged upstream for v4.20 cycle
  * [x] Add reference-tracking to verifier
  * [x] Needs to perform lookup with 5tuple in packet contents (might not match skb metadata)
  * [x] Needs to perform lookup with reverse 5tuple
  * [x] Consider non-TC usage in defining API (XDP, sk hooks?)
  * [x] Extend socket access to include `SO_MARK`
  * [ ] Extend socket access to include socket state
  * [x] Needs to have a path to determining the direction of the packet cf. connection direction
* [x] Investigate the requirement for storing state with the connection
  * [ ] Make cached ct_state fields as stateless as possible
  * If socket must hold state,
    * [x] Add additional allocate primitive to get (and transparently allocate) scratch space for socket
      * [Upstream implementation](https://lwn.net/Articles/787194/)
      * Outstanding question: SK_LOCAL_STORAGE requires fullsock, do we need to track something before we get a fullsock?
    * [ ] Investigate need for locking
      * [x] If necessary, propose simple locking primitives
        * `bpf_lock(u16 lockid)`, `bpf_unlock(u16 lockid)`
* [ ] Investigate required Cilium changes
  * [ ] Rework datapath to use `bpf_sk_lookup()`
  * [ ] When creating veth pairs, retrieve `NETNS_ID` for peer dev
    * [ ] Plumb this down to BPF code generation
  * [ ] If CT remains for some cases, conditionally trigger userspace handling code for it

Limitations
---

* For TCP connections, the transition between different states is well defined through `socket()` + `bind()` / `connect()`, which makes it easy to determine from the socket whether the kernel is initiating a connection or expecting inbound traffic. However, for UDP sockets this is not the case. Applications are not required to `connect()` for UDP, so it's possible that the socket is only identified by the local port. If applications do not `connect()`, but are only expecting to initiate connections, there is no way for Cilium to perform a socket lookup and understand this intention to only allow outbound connections. In this case, Cilium could not allow only return traffic to this port.
