### ISSUE TITLE
Socket-LB limitation follow-ups

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#28820]
This is a meta issue to track follow-ups for fully resolving the limitation with socket-lb where client applications continue to send (connected UDP) traffic to deleted service backends.

This is currently resolved in the host netns - https://github.com/cilium/cilium/pull/25169.

### Old kernels

- [x] Address the limitation for pod network namespaces by forcefully terminating connections to deleted backends - https://github.com/cilium/cilium/pull/33459
- [ ] User `sock_diag` filters to filter out sockets being retrieved via the netlink call

Blockers: 
Cilium agent is deployed as a pod in the host netns, and we currently don't bind mount `/var/run/netns` or `/proc` directory on host inside the agent pod, so it doesn't see pod netns's. Options to enable netns access: (1) run cilium agent with hostPID (security implications) so that it can scan netns (2) bind mount `/var/run/netns` inside the agent pod

### New kernels
Use the forceful termination capability from BPF using socket iterators - [Patch](https://lore.kernel.org/bpf/20230519225157.760788-1-aditi.ghag@isovalent.com/) released in kernel 6.5. https://github.com/cilium/cilium/issues/37907
[Resolved in v1.17](https://github.com/cilium/cilium/pull/36197) - Blockers: The LLVM version currently used in Cilium doesn't support kfuncs. 

### Testing:

- [ ] Add a CI test in cilium-cli test suite to catch any regressions

**Comment by alex-berger** [comment]
Not sure, but isn't this (now) fixed by https://github.com/cilium/cilium/pull/33459, which is part of Cilium >= 1.16.0?

**Comment by sbocahu** [comment]
Can somebody explain the shortcomings of using socketLB.hostNamespaceOnly=true ?

IIUC, #33459 fixes the issue with UDP,but not TCP. Why is TCP unsupported ? Is this a technical limitation or by principle, expecting the client side to use TCP keepalive and applicative heartbeats to handle network changes & connection breaking ?

I am facing issues with Redis & ioredis client, that do not support applicative heartbeats & TCP keepalive is not enough.
It seems to be OK with hostNamespaceOnly but I had expected "socket-LB: Terminate pod netns connections to deleted service backends" to terminate TCP connections as well when looking at issues/pr/doc.

thanks !

**Comment by jrife** [comment]
> Use the forceful termination capability from BPF using socket iterators - [Patch](https://lore.kernel.org/bpf/20230519225157.760788-1-aditi.ghag@isovalent.com/) released in kernel 6.5.
Blockers: The LLVM version currently used in Cilium doesn't support kfuncs.

Hi @aditighag Is this still a blocker? It seems like https://github.com/cilium/cilium/pull/36197 bumped the LLVM version to 18. I'd be happy to lend a hand here to get Cilium using `bpf_sock_destroy()`.

**Comment by aditighag** [comment]
> > Use the forceful termination capability from BPF using socket iterators - [Patch](https://lore.kernel.org/bpf/20230519225157.760788-1-aditi.ghag@isovalent.com/) released in kernel 6.5.
> > Blockers: The LLVM version currently used in Cilium doesn't support kfuncs.
> 
> Hi [@aditighag](https://github.com/aditighag) Is this still a blocker? It seems like [#36197](https://github.com/cilium/cilium/pull/36197) bumped the LLVM version to 18. I'd be happy to lend a hand here to get Cilium using `bpf_sock_destroy()`.

@jrife Sounds good! I've filed a new issue - https://github.com/cilium/cilium/issues/37906. Do you want to add a comment outlining a high level approach?

**Comment by aditighag** [comment]
>IIUC, https://github.com/cilium/cilium/pull/33459 fixes the issue with UDP,but not TCP. Why is TCP unsupported ? Is this a technical limitation or by principle, expecting the client side to use TCP keepalive and applicative heartbeats to handle network changes & connection breaking ?
I am facing issues with Redis & ioredis client, that do not support applicative heartbeats & TCP keepalive is not enough.

@sbocahu We can extend the fix to TCP. Are you interested in submitting a PR?

**Comment by aditighag** [comment]
>User sock_diag filters to filter out sockets being retrieved via the netlink call

@jrife FYI in case you are interested in tackling this on older kernels - https://github.com/cilium/cilium/issues/40862.

**Comment by jrife** [comment]
@aditighag Thanks, I'm happy to look into it when I get a little extra time. 

Another idea I wanted to explore was being smarter about skipping network namespaces for pods that we know don't have a connection to a given backend. We would need to maintain some extra state mapping net namespace cookies to backends or something like that. Then we could use that as a filter when deciding whether or not to explore sockets in that namespace. You still need to visit all the sockets in system UDP/TCP hash for each namespace you *do* visit, and the extra bookkeeping is annoying, but it would save on iterations if the set of connected pods is small relative to the total number of pods.

**Comment by alex-berger** [comment]
Using Cilium 1.19.1 with the below configuration to enable SocketLB, we still observe that some UDP connections are not properly termianted (by Cilium) when the corresponding backend Pod disappears. So it looks like there are still some bugs or limitations in the current implementation.

```
  ...
  kube-proxy-replacement: "true"
  bpf-lb-sock: "true"
  bpf-lb-sock-hostns-only: "false"
  bpf-lb-sock-terminate-pod-connections: "true"
```

I have not yet much insights into what exactly goes wrong, but it looks like BPF map `cilium_lb4_reverse_sk` on the affected nodes is leaking, i.e. is slowly growing until it exceeds its capacity. A quick search revealed the below potential related issues: 

- https://github.com/cilium/cilium/issues/42649
- https://github.com/cilium/cilium/issues/40336 (closed without any resolution)

I used the below shell script to very this and as you can see there are quite some nodes which are at capacity of `cilium_lb4_reverse_sk`.

```shell
while true; do      
      for pod in $(kubectl get pods -n kube-system -l k8s-app=cilium -o jsonpath='{.items[*].metadata.name}'); do
        limit=$(kubectl exec -n kube-system "$pod" -c cilium-agent -- sh -c "cilium-dbg status --verbose | grep 'Sock reverse NAT' | awk '{print \$4}'")
        count=$(kubectl exec -n kube-system "$pod" -c cilium-agent -- sh -c "cilium-dbg map list | grep cilium_lb4_reverse_sk | awk '{print \$2}'")
        if (( count > limit * 90 / 100 )); then # only list nodes with usage above 90%
          node=$(kubectl get pod -n kube-system "$pod" -o jsonpath='{.spec.nodeName}')
          echo "[$(date)] on ${node} has cilium_lb4_reverse_sk ${count} entries, which is $(( (count * 100) / limit ))% of the limit ${limit}"
        fi
      done
      echo "====================================================================================================================="
      sleep 300
done
zsh: command not found: #
[Fri Feb 27 10:28:34 CET 2026] on ip-10-2-10-179.eu-central-1.compute.internal has cilium_lb4_reverse_sk 72165 entries, which is 99% of the limit 72584
zsh: command not found: #
[Fri Feb 27 10:28:39 CET 2026] on ip-10-2-1-232.eu-central-1.compute.internal has cilium_lb4_reverse_sk 585071 entries, which is 99% of the limit 586045
zsh: command not found: #
[Fri Feb 27 10:28:42 CET 2026] on ip-10-2-47-242.eu-central-1.compute.internal has cilium_lb4_reverse_sk 143216 entries, which is 99% of the limit 144319
zsh: command not found: #
[Fri Feb 27 10:28:46 CET 2026] on ip-10-2-47-226.eu-central-1.compute.internal has cilium_lb4_reverse_sk 143092 entries, which is 99% of the limit 144319
zsh: command not found: #
[Fri Feb 27 10:28:49 CET 2026] on ip-10-2-22-17.eu-central-1.compute.internal has cilium_lb4_reverse_sk 139506 entries, which is 96% of the limit 145110
zsh: command not found: #
[Fri Feb 27 10:28:51 CET 2026] on ip-10-2-6-43.eu-central-1.compute.internal has cilium_lb4_reverse_sk 72097 entries, which is 99% of the limit 72584
zsh: command not found: #
[Fri Feb 27 10:28:54 CET 2026] on ip-10-2-3-52.eu-central-1.compute.internal has cilium_lb4_reverse_sk 72240 entries, which is 99% of the limit 72584
zsh: command not found: #
[Fri Feb 27 10:28:57 CET 2026] on ip-10-2-36-45.eu-central-1.compute.internal has cilium_lb4_reverse_sk 71463 entries, which is 99% of the limit 71811
zsh: command not found: #
[Fri Feb 27 10:29:06 CET 2026] on ip-10-2-26-54.eu-central-1.compute.internal has cilium_lb4_reverse_sk 585299 entries, which is 99% of the limit 586045
zsh: command not found: #
[Fri Feb 27 10:29:11 CET 2026] on ip-10-2-46-247.eu-central-1.compute.internal has cilium_lb4_reverse_sk 71615 entries, which is 99% of the limit 72083
```

Also, in our case the vast majority of entries (>99.99%) in `cilium_lb4_reverse_sk` are not for ClusterIPs (which in our case are in CIDR `172.20/16`), but are mapping the IP of our Datadog Agents (e.g. `10.2.18.113`) to the IP of the Node (HostIP e.g. `10.2.26.54`). Also, the negative port reported `-17121` looks suspicious (mabye a bug in `cilium-dbg bpf socknat list` and it is actually port `48415`):

```
cilium-dbg bpf socknat list
...
2889893         10.2.18.113:-17121 -> 10.2.26.54:-17121 (revnat=43520)     
3053758         10.2.18.113:-17121 -> 10.2.26.54:-17121 (revnat=43520)     
3640048         10.2.18.113:-17121 -> 10.2.26.54:-17121 (revnat=43520)     
4600429         10.2.18.113:-17121 -> 10.2.26.54:-17121 (revnat=43520) 
```

Is SocketLB really production ready yet, or not resp. what is the official recommendation use it or not?

**Comment by jrife** [comment]
@alex-berger 

> Also, in our case the vast majority of entries (>99.99%) in cilium_lb4_reverse_sk are not for ClusterIPs (which in our case are in CIDR 172.20/16), but are mapping the IP of our Datadog Agents (e.g. 10.2.18.113) to the IP of the Node (HostIP e.g. 10.2.26.54). Also, the negative port reported -17121 looks suspicious (mabye a bug in cilium-dbg bpf socknat list and it is actually port 48415):
> 
> ```
> cilium-dbg bpf socknat list
> ...
> 2889893         10.2.18.113:-17121 -> 10.2.26.54:-17121 (revnat=43520)     
> 3053758         10.2.18.113:-17121 -> 10.2.26.54:-17121 (revnat=43520)     
> 3640048         10.2.18.113:-17121 -> 10.2.26.54:-17121 (revnat=43520)     
> 4600429         10.2.18.113:-17121 -> 10.2.26.54:-17121 (revnat=43520) 
> ```

What does the set up look like for traffic going to the Datadog Agent? Are you using a `NodePort` service? Are there a lot of short-lived sockets talking to the Datadog Agent, a lot of long-lived connected UDP sockets, or something different?

 > some UDP connections are not properly termianted (by Cilium) when the corresponding backend Pod disappears

Is the backend Pod in question the Datadog Agent or is there something else?

**Comment by alex-berger** [comment]
@jrife 
> What does the set up look like for traffic going to the Datadog Agent? Are you using a NodePort service? 

Actually, the DataDog agent (DaemonSet) is using `hostPort` 
```yaml
    ports:
    - name: dogstatsdport
      hostPort: 8125
      containerPort: 8125
      protocol: UDP
```

```shell
root@ip-10-2-1-232:/home/cilium# cilium-dbg bpf lb list | grep 8125 | sort     
SERVICE ADDRESS                BACKEND ADDRESS (REVNAT_ID) (SLOT)
0.0.0.0:8125/UDP (0)           0.0.0.0:0 (171) (0) [HostPort, non-routable]                   
0.0.0.0:8125/UDP (1)           10.2.6.169:8125/UDP (171) (1)                                  
10.2.1.232:8125/UDP (0)        0.0.0.0:0 (172) (0) [HostPort]                                 
10.2.1.232:8125/UDP (1)        10.2.6.169:8125/UDP (172) (1)                                  
172.20.6.173:8125/UDP (0)      0.0.0.0:0 (1) (0) [ClusterIP, InternalLocal, non-routable]     
172.20.6.173:8125/UDP (1)      10.2.6.169:8125/UDP (1) (1)                                    
172.20.92.248:8125/UDP (0)     0.0.0.0:0 (10) (0) [ClusterIP, non-routable]                   
172.20.92.248:8125/UDP (1)     10.2.5.232:8125/UDP (10) (1)                                   
172.20.92.248:8125/UDP (2)     10.2.6.169:8125/UDP (10) (2)                                   
172.20.92.248:8125/UDP (3)     10.2.7.31:8125/UDP (10) (3)                                    
172.20.92.248:8125/UDP (4)     10.2.9.103:8125/UDP (10) (4)                                   
172.20.92.248:8125/UDP (5)     10.2.11.180:8125/UDP (10) (5)                                  
172.20.92.248:8125/UDP (6)     10.2.12.113:8125/UDP (10) (6)                                  
172.20.92.248:8125/UDP (7)     10.2.14.224:8125/UDP (10) (7)
```

> Are there a lot of short-lived sockets talking to the Datadog Agent, a lot of long-lived connected UDP sockets, or something different?

Looks like its the former, a lot of short-lived sockets. The offending client is using PHP DogStatsd version 1.6.1, which creates a fresh socker for each message, sends the message and then closes the socket. https://github.com/DataDog/php-datadogstatsd/blob/brian/release-1.6.1/src/DogStatsd.php#L487

```PHP
    public function flush($message)
    {
        $message .= $this->flushTelemetry();

        // Non - Blocking UDP I/O - Use IP Addresses!
        if (!is_null($this->socketPath)) {
            $socket = socket_create(AF_UNIX, SOCK_DGRAM, 0);
        } elseif (filter_var($this->host, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)) {
            $socket = socket_create(AF_INET6, SOCK_DGRAM, SOL_UDP);
        } else {
            $socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
        }
        socket_set_nonblock($socket);

        if (!is_null($this->socketPath)) {
            $res = socket_sendto($socket, $message, strlen($message), 0, $this->socketPath);
        } else {
            $res = socket_sendto($socket, $message, strlen($message), 0, $this->host, $this->port);
        }

        if ($res !== false) {
            $this->resetTelemetry();
            $this->bytes_sent += strlen($message);
            $this->packets_sent += 1;
        } else {
            $this->bytes_dropped += strlen($message);
            $this->packets_dropped += 1;
        }

        socket_close($socket);
    }
```


> Is the backend Pod in question the Datadog Agent or is there something else?

Yes, it is the Datadog Agent. 

I increased `cilium_lb4_reverse_sk` map size from 586'045 to 1'758'135, and it managed to fill it up withing less than an hour :-(. So, this is definitively some kind of a leak.

**Comment by jrife** [comment]
>     public function flush($message)
>     {
>         $message .= $this->flushTelemetry();
> 
>         // Non - Blocking UDP I/O - Use IP Addresses!
>         if (!is_null($this->socketPath)) {
>             $socket = socket_create(AF_UNIX, SOCK_DGRAM, 0);
>         } elseif (filter_var($this->host, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)) {
>             $socket = socket_create(AF_INET6, SOCK_DGRAM, SOL_UDP);
>         } else {
>             $socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
>         }
>         socket_set_nonblock($socket);
> 
>         if (!is_null($this->socketPath)) {
>             $res = socket_sendto($socket, $message, strlen($message), 0, $this->socketPath);
>         } else {
>             $res = socket_sendto($socket, $message, strlen($message), 0, $this->host, $this->port);
>         }
> 
>         if ($res !== false) {
>             $this->resetTelemetry();
>             $this->bytes_sent += strlen($message);
>             $this->packets_sent += 1;
>         } else {
>             $this->bytes_dropped += strlen($message);
>             $this->packets_dropped += 1;
>         }
> 
>         socket_close($socket);
>     }

This fills up `cilium_lb4_reverse_sk` because this pattern triggers this `sendmsg4` hook a bunch of times:

https://github.com/cilium/cilium/blob/17d9df006d135fb80970d3472cf947f5f5125ffd/bpf/bpf_sock.c#L602-L614

Each time would add a new entry to the map. This `sock_release` hook is meant to clean up entries associated with the socket in the map when the socket is closed:

https://github.com/cilium/cilium/blob/17d9df006d135fb80970d3472cf947f5f5125ffd/bpf/bpf_sock.c#L1240-L1276

However, since these aren't connected UDP sockets, `dst_ip4` and `dst_port` would be 0 in `sock4_delete_revnat` here:

https://github.com/cilium/cilium/blob/17d9df006d135fb80970d3472cf947f5f5125ffd/bpf/bpf_sock.c#L180

I'm working on removing the need for `sock4_delete_revnat` anyway by using socket storage directly which would make this a non-issue in Cilium, but in the meantime one workaround would be to update the client code here to just create a connected UDP socket. In other words, instead of this:

1. Create socket
2. sendto()
3. Close socket

You would do:

1. Create socket
2. connect()
3. sendmsg()
4. Close socket()

Then all the garbage should get cleaned up correctly.

**Comment by alex-berger** [comment]
@jrife Thank you very much for the above analysis and your feedback. 

From a user's point of view this is clearly a limitation (i.e. a bug / missing feature) as using unconnected UDP sockets is a very common thing (nothing esoteric). Shouldn't there be a clear warning in the docs to not use SocketLB until https://github.com/cilium/cilium/issues/42658 is in place to resolve this?

> but in the meantime one workaround would be to update the client code here to just create a connected UDP socket.

Unfortunately, the proposed workaround is not feasible as we are not under full control of all upstream dependencies of the affected software. Also, adding `connect(...)` would very likely be rejected by the upstream mantainers as technically using unconnected sockets is the correct (and more performant) approach in that specific case (because it uses one system call less).

**Comment by jrife** [comment]
> [@jrife](https://github.com/jrife) Thank you very much for the above analysis and your feedback.
> 
> From a user's point of view this is clearly a limitation (i.e. a bug / missing feature) as using unconnected UDP sockets is a very common thing (nothing esoteric). Shouldn't there be a clear warning in the docs to not use SocketLB until [#42658](https://github.com/cilium/cilium/issues/42658) is in place to resolve this?

Sure, we can add it [here](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#known-issues). To be clear, I didn't know about this issue specifically until I looked more into your case, but it's clearly a limitation and should be documented until this class of problem is eliminated with https://github.com/cilium/cilium/issues/42658.

> > but in the meantime one workaround would be to update the client code here to just create a connected UDP socket.
> 
> Unfortunately, the proposed workaround is not feasible as we are not under full control of all upstream dependencies of the affected software. Also, adding `connect(...)` would very likely be rejected by the upstream mantainers as technically using unconnected sockets is the correct (and more performant) approach in that specific case (because it uses one system call less).

Why not create your socket and call connect in the constructor [here](https://github.com/nexxiot/php-datadogstatsd/blob/0c898f37b237d06b37c0975c23a92cc85090ebf4/src/DogStatsd.php#L111) then just use `socket_send` inside `writeToSocket` with the socket you've already established? That would ultimately lead to less syscalls, since you aren't creating and destroying a socket every time you call `flush()`. Is there a reason this library needs to create a new socket every time?

> we still observe that some UDP connections are not properly termianted (by Cilium) when the corresponding backend Pod disappears

Going back to this part of your original problem, it makes sense how `cilium_lb4_reverse_sk` would fill up quickly and eject old entries given the pattern with PHP DogStatsd, but I'm not sure where socket termination comes in. It wouldn't matter for DogStatsd, since it's creating a new socket every time. Do you have some other workload creating long-lived connected UDP sockets which are not terminated when your backend disappears?

**Comment by alex-berger** [comment]
@jrife 

> but I'm not sure where socket termination comes in.

The problem is not affecting DogStatsd itself, which can still successfully send its metrics. I guess the problem is that once `cilium_lb4_reverse_sk` is full (at capacity), some new UDP connections for DNS resolution (mostly from nginx) are no longer tracked in it and thus not closed when the corresponding CoreDNS backend Pod disappears. This in turn then results in nginx failing to resolve DNS (timeout) and thus failing to serve/forward requests. I suspect that nginx is using long-living UDP sockets for DNS resolution and therefore is specifically vulnerable to this issue (but I had not yet time to proof whether this is actually true or not).

> Do you have some other workload creating long-lived connected UDP sockets which are not terminated when your backend disappears?

Yes, the above mentioned nginx DNS UDP sockets.

We decided, to disable SocketLB for now for east-west traffic (i.e. setting `hostNamespaceOnly: true` in the HelmChart). So, we are looking forward to the implementation of https://github.com/cilium/cilium/issues/42658, after which we might reconsider SocketLB.

**Comment by firmero** [comment]
We’ve run into similar problems. We use `node-local-dns` and `LRP` for the `kube-dns` svc. Specifically, after restarting daemonset `node-local-dns`, nginx kept UDP sockets stuck with the old node-local-dns pod IP and started reporting timeouts during resolution. We also observed that `cilium_lb4_reverse_sk`  is full of entries with UDP sockets to DNS. 

We performed an experiment (without LRP): 

-   Emptied the `cilium_lb4_reverse_sk` table and scheduled pods on a single, clean node.
-   Deployed a server pod running: `nc -vukl 3333` and exposed it via a svc.
-   In a client pod, ran: `while true; do date; sleep 10; done | nc -vu server 3333`
-   Everything worked, and we could find the mapping `SERVER_IP:1293 -> SVC_SERVER_IP:1293` in the table.
     
Then we started ~8 pods running: `while true; do curl fake-$RANDOM-$RANDOM-$RANDOM; done`. The table filled up quickly and we could no longer find the original mapping. Everything still worked as expected at this point.

After restarting the server deployment, the `nc` in the client got stuck and we observed periodic drops in cilium:
```
xx drop (Stale or unroutable IP) flow 0xa6152688 to endpoint 0, ifindex 6, file bpf_host.c:865, , identity host->unknown: 10.96.4.223:39698 -> 10.96.4.235:3333 udp 
```

If we did a rollout restart while the mapping was still present in the table, `nc` terminated cleanly and did not hang, unlike the case when the mapping was missing.
