### ISSUE TITLE
bpf: enhance FIB-driven redirect support

### ISSUE THREAD

**Issue by julianwiedmann** [cilium/cilium#30903]
* [ ] benefit from `HAVE_FIB_INDEX` on stable kernels (#27642)
* [ ] handle `BPF_FIB_LKUP_RET_FRAG_NEEDED` (#29583). Potentially by returning a corresponding ICMP message.
* [ ] implement support for [BPF_FIB_LOOKUP_MARK](https://lore.kernel.org/bpf/20240326101742.17421-1-aspsk@isovalent.com/T/) (added with kernel 6.10).
