### ISSUE TITLE
[Epic] Improve CRD-mode scalability

### ISSUE THREAD

**Issue by marseel** [cilium/cilium#30967]
I wanted to summarize all efforts and what needs to be done to improve CRD mode scalability and also the reasoning behind it.

Advantages of CRD over KVstore/Etcd:
- From architecture point of view, the k8s apiserver serves as a cache for data in Etcd and can be scaled horizontally as opposed to Etcd, which essentially supports [5 replicas](https://etcd.io/docs/v3.2/faq/#what-is-maximum-cluster-size) - the more replicas the lower write throughput, but higher read throughput.
- K8s control-plane has a throttling mechanism ([APF](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/)) for the excessive load as compared to Etcd, which doesn't - this definitely helps with recovery in case all agents crash in the cluster and start bootstrapping at the same time etc.
- Managing Etcd cluster is a pain for our users - there is no reasonable operator for managing Etcd, backups, health-checking, recovery etc. and using CRD-based mode is just simply easier to use.
- There are future improvements in k8s planned for making CRDs more scalable - KEP-3157 for replacing the initial list with a streaming watch (this is indirect, not only CRDs are affected by it) and KEP-4222 for binary serialization of CRDs. 
- Out of the box k8s provides with `goaway-chance` to equalize long-connections between apiservers and  draining of watch requests `shutdown-watch-termination-grace-period`

Disadvantages over KVstore/Etcd:
- In cloud-provider environments, customers usually don't have direct control over control plane horizontal/vertical scaling, which can result in poorer scalability in some cases.
- The CRD representation of CiliumEndpoint is significantly larger than the one in Etcd. I think there is a definitely room for improvement here

Efforts (some of them don't have the corresponding issues yet, TBD):
- [ ] Stabilize CiliumEndpointSlices - it's currently beta, also document migration from regular CEP to CES.
- [ ] Perform 5k nodes test with standard [k8s scale-test ](https://github.com/kubernetes/perf-tests/tree/master/clusterloader2/testing/load) - ideally as CI to ensure we don't have regressions
- [ ] Document test results + configuration of both k8s control plane and Cilium and limitations, for example:
  1. Enabling EndpointSlice batching in k8s
  2. Number of k8s control plane nodes
  3. Enabling CiliumEndpointSlices in Cilium
  4. Limitations not covered by test like ENI-mode
- [ ]  [nice-to-have] Support more granular health-check to disable cilium-agent restart when k8s control-plane is down - the main goal is to still serve fqdn and not disrupt connection when L7 policies are used ( https://github.com/cilium/cilium/issues/25288 )
- [ ] [nice-to-have] [Improve scalability of node-to-node health checking - currently we recommend just disabling it for large-scale deployments](https://github.com/cilium/cilium/issues/32820)
- [ ] [nice-to-have] Support KVStore to CRD migration ( https://github.com/cilium/cilium/issues/30689 )
- [ ] [nice-to-have] Consider pruning CEP CRD data  - I'm pretty sure we could remove `external-identifiers` and `identity/labels` from CEP (or just adding an option to disable it) - this doesn't matter that much though when CES is enabled
