### ISSUE TITLE
Migrate CiliumCIDRGroup watcher to ipcache async metadata APIs

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#30992]
`CiliumCIDRGroup` is implemented with two aspects: Firstly, the `CIDRGroupRef` field in `CiliumNetworkPolicy` objects. Secondly, the `CiliumCIDRGroup` ingestion.

The network policy `CidrGroupRef`s can be translated into a `LabelSelector` for `cidrgroup:name=<name>`. This could happen for example as part of `parseToCiliumIngressCommonRule()`. This requires minimal changes to the network policy watchers and doesn't involve introducing any additional rule iteration or calculation when different resources change.

Separately, when updates for `CiliumCIDRGroup`s are received, we can translate that into calls to `ipcache.UpsertLabels(...)`. We'd have some canonical representation of the label such as `{Source: "CIDRGroup",Key:"name",Value:"<name>"}`. For each CIDR in the `CiliumCIDRGroup`, we can inform the IPCache that this CIDR corresponds to this set of labels. Similar to the kube-apiserver entity feature, this will automatically associate these labels with identities for the relevant IP addresses and automatically trigger calculation of any policy impacts whenever the IPCache is informed about this new label association.

I think that this will have a few benefits:
- Simpler implementation/policy handling code
- Cheaper policy parsing/ingestion
- Native hubble visibility

More discussion here:
https://github.com/cilium/cilium/pull/24638#discussion_r1159190757

Related: https://github.com/cilium/cilium/pull/24638
Related: #24801
Related: https://github.com/cilium/cilium/issues/30162

```[tasklist]
### Tasks
- [x] https://github.com/cilium/cilium/pull/29717
- [x] Move the ipcache metadata map over to use bitlpm
- [x] Extend ipcache identity allocation to perform an ancestors search when collecting labels to allocate the identity
- [x] Extend ipcache upsert / delete to perform descendents searches when modifying CIDRs to identify child prefixes that need to be reallocated to remove corresponding labels.
- [x] Plumb CiliumCIDRGroup k8s resource handling into ipcache async APIs
- [x] Delete CiliumCIDRGroup policy translation watcher code
```

**Comment by oblazek** [comment]
This is awesome! Thanks @squeed
