### ISSUE TITLE
CFP: Active Connection Tracking

### ISSUE THREAD

**Issue by AwesomePatrol** [cilium/cilium#31752]
### Active Connection Tracking

This proposal was presented during Cilium Developer Summit on 18 March, 2024.

**Is your proposed feature related to a problem?**

"Advanced" L4 load balancers can't make informed decisions on load distribution between the zones without information that could approximate L7 concept of a request.

This is a prerequisite for further xDS control-plane integration.

**Describe the feature you'd like**

Track number of active and new connections to each service grouped by the backend's zone.

**Describe your proposed solution**

More details in [the design doc](https://docs.google.com/document/d/1EdhtDavDzpEk7jamWhNV7uM5h6MhHbVmy7bI8U8nitM/edit#heading=h.dkumlwuhiwuf)

This proposal will consist of the following stages:
- [x] Passing zone information from `EndpointSlices` to `lb{4,6}_backend`
- [x] Updating counters in `cilium_lb_lrs` BPF map (make it available only with cilium map get cilium_lb_lrs)
- [x] Adding way to configure zone ID<->name mapping
- [x] Surfacing this information in /metrics

**Comment by AwesomePatrol** [comment]
The last PR in the series was merged. I expect only bugfixes and minor feature enhancements to follow (for example: more configuration options).
