### ISSUE TITLE
CiliumEndpointSlice Graduation to Stable

### ISSUE THREAD

**Issue by thorn3r** [cilium/cilium#31904]
CiliumEndpointSlice Graduation to Stable

**SIG: sig-scalability**

**Begin Design Discussion:** 2024-04-11

**Cilium Release:** 1.16

**Authors:** Tim Horner <timothy.horner@isovalent.com>, Marcel Zięba <marcel.zieba@isovalent.com>, Marco Iorio <marco.iorio@isovalent.com>

## Summary

CiliumEndpointSlice facilitates the grouping of multiple CiliumEndpoint objects to achieve better scalability. This document describes the remaining work needed to consider CiliumEndpointSlice a Stable feature.

## Goals

* Blanket test CiliumEndpointSlice in all CI workflows.
    - CiliumEndpointSlice will be temporarily enabled for all CI workflows to identify failures or feature incompatibilities. The goal of the blanket test is to provide guidance on areas of improvement to focus on and any gaps in tooling.

* Enable CiliumEndpointSlice in CI tests.
    - The feature has unit test coverage but there is no end-to-end testing. CiliumEndpointSlice will be enabled in the Conformance E2E and 100 Nodes Scale Test workflows. Additional workflows may be added based on the findings of the blanket test.

* Identify feature incompatibilites
    - Identify features that rely on the use of CiliumEndpoint and summarize the work needed to support CiliumEndpointSlice. A decision should be made per-feature whether the incompatibility should be fixed or documented. The decision should be made based on the amount of work needed and the value add of making the feature compatible with CiliumEndpointSlice.
* Simplify CiliumEndpointSlice configuration
    - Cilium Operator accepts the following 8 options for configuring CiliumEndpointSlice:
        - ces-max-ciliumendpoints-per-ces
	    - ces-slice-mode
	    - ces-write-qps-limit
	    - ces-write-qps-burst
	    - ces-enable-dynamic-rate-limit
	    - ces-dynamic-rate-limit-nodes
	    - ces-dynamic-rate-limit-qps-limit
	    - ces-dynamic-rate-limit-qps-burst

    - Configuration should be simplified by setting sane defaults and removing any unused or deprecated options. CiliumEndpointSlice should use its own Kubernetes ClientSet to decouple it from the ClientSet used by the CiliumOperator for all other resources.

* Define a migration path from CiliumEndpoint to CiliumEndpointSlice
    - A migration path is needed to allow users to enable CiliumEndpointSlice on clusters utilizing CiliumEndpoint. The process should be simple and well documented, with CI test coverage to identify regressions. 
    - https://github.com/cilium/cilium/issues/32057

### Tasks
- [ ] https://github.com/cilium/cilium/issues/32589
- [ ] https://github.com/cilium/cilium/issues/32590
- [ ] https://github.com/cilium/cilium/issues/32591
- [ ] https://github.com/cilium/cilium/issues/32057
- [ ] https://github.com/cilium/cilium/pull/32535
- [ ] https://github.com/cilium/cilium/pull/33361
- [ ] https://github.com/cilium/cilium/pull/33821
- [ ] https://github.com/cilium/cilium/pull/33946
- [ ] https://github.com/cilium/cilium/issues/35532
- [ ] https://github.com/cilium/cilium/issues/33778
- [ ] https://github.com/cilium/cilium/issues/24833
- [ ] https://github.com/cilium/cilium/issues/37562
- [ ] https://github.com/cilium/cilium/issues/42171

**Comment by antonipp** [comment]
Thank you for starting this! 🙌 

Just for future reference, my PR https://github.com/cilium/cilium/pull/31800 already has the docs for the `Define a migration path from CiliumEndpoint to CiliumEndpointSlice` item (although there are no tests)

**Comment by thorn3r** [comment]
@antonipp I saw that, nice work and thank you for writing that up!

**Comment by marseel** [comment]
Issue related to CES and `ces-slice-mode` option: https://github.com/cilium/cilium/issues/31564

**Comment by dlapcevic** [comment]
I think ces-slice-mode should be deprecated together with Identity batching mode, and FCFS batching mode will be the default and only one.

Reason:
FCFS is a simpler algorithm (fewer possible bugs) that has better performance for almost all cases.

**Comment by dlapcevic** [comment]
Is the purpose of having a separate K8s client for CES to ensure that it doesn't impact or get impacted by other resources?

If so, is there a pattern that can be applied across resources? Which resources require a separate client?

**Comment by marseel** [comment]
> If so, is there a pattern that can be applied across resources? Which resources require a separate client?

I don't think there is a pattern in Cilium yet, but definitely, there are other controllers for which we would like to do it too. 
The pattern is mostly inspired by kcm in k8s.

**Comment by jshr-w** [comment]
I would like to help with the CI coverage for the migration path, as in the issue above. Would someone be able to help assign the issue to me, please?

**Comment by thorn3r** [comment]
Agreed that the identity-based mode should be deprecated. We should also add some validation for this option until it is removed. Currently, if anything other than `cesSliceModeIdentity` is supplied (including typos), you get FCFS. The risk is low, but still worth covering the bases imo.

**Comment by joestringer** [comment]
As discussed during the @cilium/sig-scalability discussion on 2024-06-27, we didn't make sufficient progress on this during v1.16 cycle to promote the feature. Removing the milestone.

**Comment by dlapcevic** [comment]
We should get this ready for 1.18 release.
According to the discussion during the last sig-scalability meeting (in January), Egress Gateway incompatibility is the only remaining item to make CES GA. Is there an issue for it?

**Comment by karol-szymanowski** [comment]
I think there might be additional task blocking this issue: https://github.com/cilium/cilium/issues/42171
