### ISSUE TITLE
Unencrypted traffic among nodes when IPsec is used with L7 egress proxy

### ISSUE THREAD

**Issue by jschwinger233** [cilium/cilium#31984]
Security advisory: https://github.com/cilium/cilium/security/advisories/GHSA-j89h-qrvr-xc36

Previous PRs (#29530, #29594, #30095) addressed the vulnerabilities for IPsec and L7 ingress proxy, this issue is opened for IPsec and L7 **egress** proxy.

## Initial Attempts 

In the first place we tried to simply add an ip rule for from-egress-proxy traffic, just like what we did at https://github.com/cilium/cilium/pull/29530/commits/bca5f075b795bc9bc29a7500bf7ce5a533dc8e19, which added an ip rule for from-ingress-proxy traffic. This commit (https://github.com/cilium/cilium/pull/31980/commits/1c97de7da4c93ef228574e145fdb57cd9ec53a34) implemented the idea, 

However, it has turned out to be not enough. We realized iptables also needs to be taken care of, so the second commit (https://github.com/cilium/cilium/pull/31980/commits/1b5e7d6e777e77b1bf77fbb8881dd4178fcdecd7) followed. Please see the commit message for reasons.

After above two patches, ci-ipsec-e2e seemed to be happy, even with leak detection, but ci-ipsec-upgrade turned broken badly. We found the failure happened during downgrade from, say, 1.15-patched to 1.14-tip (minor downgrade). 1.15-patches will install the new from-egress-proxy rule + new iptables rule; after downgrade to 1.14-tip, the new iptables rule is cleaned up, but the new from-egress-proxy rule is left over, because the old 1.14-tip doesn't recognise from-egress-rule at all. The stale ip rule messed up.

To handle rules carefully without breaking downgrade, I propose the two-stage patches as followed.

### Stage one

We will have to merge the following PRs:

- [x] #31923 
- [x] #31922 
- [x] #31926 
- [x] #31928 
- [ ] #31930 (Closed as commented at https://github.com/cilium/cilium/pull/31930#issuecomment-2126383055)

These PRs are doing a simple thing: remove from-egress-proxy rule, even they doesn't install the rule. The rule is probably installed by higher version of cilium.

### Stage two

After PRs in stage one are all merged into stable branches and released in weeks, we can proceed with the following PRs:

- [ ] ~~#31955~~
- [ ] https://github.com/cilium/cilium/pull/32683 
- [ ] ~~#31975~~ 
- [ ] https://github.com/cilium/cilium/pull/32932
- [ ] #31976 
- [ ] #31977 

Right now they consists of two commits described in "Initial Attempts" section, plus "manually specify downgrade version", plus leak detection CI checks. I will clean up the PRs once ready, for now the leak detection patches and "manually specify" patch are temporarily added to demonstrate the solution works. We have noted that ci-ipsec-upgrade and ci-ipsec-e2e are mostly in green status.

## Outstanding issues

Leak detection check sometimes failes at the very end of ci-ipsec-e2e. The latest speculation is it's caused by conn-disrupt pods deletion.

If conn-disrupt-server is deleted with its ipcache entry, but an skb holding conn-disrupt-client -> conn-disrupt-server already gets emitted, then this skb at from_host@cilium_host won't be marked as need-ipsec-encryption (0xe00) due to ipcache entry missing. bpftrace wil then catch it.

Right now there is no obvious solution (if the theory turns out to be correct). We will move forward and discuss it later.

**Comment by jschwinger233** [comment]
Because of https://github.com/cilium/proxy/pull/742 and https://github.com/cilium/cilium/pull/32331, the backport of https://github.com/cilium/cilium/pull/32683 needs extra care.

The above two PRs avoids an issue while bringing about a new issue:
- issue solved: With to-world packets from proxy having original src IP, bpf masquerading works for them
- new issue: With to-world packets from proxy linked with a transparent socket, we introduced new mark `MARK_MAGIC_PROXY_TO_WORLD` to avoid iptables modifying mark

Cilium 1.15- doesn't have these two PRs, so we have to:
- solve the bpf masquerading issue for to-world packets from proxy
- drop the patch introducing new mark `MARK_MAGIC_PROXY_TO_WORLD`

I think I'll just disable bpf masquerading in ci-ipsec-e2e for 1.15-, for now. Then open a separate issue for it.
