### ISSUE TITLE
CFP: Support Gateway API v1.1.0

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#32492]
## Cilium Feature Proposal
        
Cilium supports Gateway API 1.0.0 since v1.15, this issue is to track the work to support Gateway API 1.1.0, which is released recently

https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.1.0

## Tasks

We don't need to complete all of the below tasks, however, the goal is to make sure all the Core Conformance features (with respective tests) are supported.

- [x] GRPCRoute has Graduated to GA
   - GRPCRoute API version is not v1 (instead of v1alpha2)
- [x] _(optional)_ Service Mesh Support has Graduated to GA
   - Related to https://github.com/cilium/cilium/issues/22512
- [ ] _(optional)_ Extended feature ParentRef Port field Graduated to GA
  - [x] Related to https://github.com/cilium/cilium/issues/31279
  - [ ] Once Gateway8080 feature is supported, ParentRef Port feature can be easily enabled in CI tests.
- [x] Conformance Profiles and Reports
   - The current Gateway API conformance test is already updated to use upstream test framework, so the work here might be just to bump Gateway API version to v1.1.0 in go.mod 
 - [x] Make sure all Core supported features are enabled in conformance tests. Currently, we are skipping a few beta/un-supported feature in https://github.com/cilium/cilium/blob/f211c17e43a870512a4766055d5ff87f6164a8b8/.github/workflows/conformance-gateway-api.yaml#L134-L136.
   - [x] Support headless service in Gateway API. Related to https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/httproute-service-types.yaml.
   - [x] Upload the latest conformance test reports to upstream repo  https://github.com/kubernetes-sigs/gateway-api/tree/main/conformance/reports/v1.1.0

**Comment by sayboras** [comment]
Remove release-blocker label, as all of required tasks are done as part of #32233. Pending taks:

- [ ] (optional) Extended feature ParentRef Port field Graduated to GA 
- [ ] (optional) Extended feature GatewayStaticAddress
   - https://github.com/cilium/cilium/pull/33042
   - Seems like some work is still required in term of CI

**Comment by sayboras** [comment]
Closing this issue, other optional tasks are tracked separately.
