### ISSUE TITLE
Scale test with 5000 nodes

### ISSUE THREAD

**Issue by thorn3r** [cilium/cilium#33778]
Expand the [100 nodes scale test](https://github.com/cilium/cilium/blob/main/.github/workflows/scale-test-100-gce.yaml) to 5000 nodes with CiliumEndpointSlice enabled.

Motivation:
1. To update the [Scalability Report](https://docs.cilium.io/en/stable/operations/performance/scalability/report/) and automate for running on a regular cadance (i.e. every minor version release).
2. To stress test CiliumEndpointSlice and its default configuration, and ideally be able to suggest CES with CRD mode for large-scale clusters rather than running etcd.
```[tasklist]
### Tasks
- [ ] https://github.com/cilium/cilium/pull/33664
- [ ] https://github.com/cilium/cilium/pull/32800
- [ ] https://github.com/cilium/scale-tests-action/pull/12
- [ ] https://github.com/cilium/cilium/pull/33777
- [ ] https://github.com/cilium/scale-tests-action/pull/15
```

**Comment by thorn3r** [comment]
Results at 2k look promising, however at 3k we are seeing failures with some Pods getting stuck Terminating and some Pending, crossing the test timeout:
```
2024-07-12T17:05:23.3671025Z E0712 17:05:23.366668   18165 clusterloader.go:248] --------------------------------------------------------------------------------
2024-07-12T17:05:23.3672694Z E0712 17:05:23.366675   18165 clusterloader.go:249] Test Finished
2024-07-12T17:05:23.3674602Z E0712 17:05:23.366681   18165 clusterloader.go:250]   Test: ./testing/load/config.yaml
2024-07-12T17:05:23.3675526Z E0712 17:05:23.366686   18165 clusterloader.go:251]   Status: Fail
2024-07-12T17:05:23.3677724Z E0712 17:05:23.366690   18165 clusterloader.go:253]   Errors: [measurement call WaitForControlledPodsRunning - WaitForRunningDeployments error: 4 objects timed out: Deployments: test-ad4h95-23/big-deployment-1, test-ad4h95-30/small-deployment-181, test-ad4h95-6/medium-deployment-19, test-ad4h95-19/medium-deployment-22
2024-07-12T17:05:23.3680167Z measurement call WaitForControlledPodsRunning - WaitForRunningStatefulSets error: 1 objects timed out: StatefulSets: test-ad4h95-19/medium-statefulset-0
2024-07-12T17:05:23.3681870Z measurement call WaitForControlledPodsRunning - WaitForRunningDaemonSets error: 1 objects timed out: DaemonSets: test-ad4h95-1/daemonset-0
2024-07-12T17:05:23.3685258Z measurement call WaitForControlledPodsRunning - WaitForRunningDeployments error: 10 objects timed out: Deployments: test-ad4h95-20/medium-deployment-2, test-ad4h95-16/small-deployment-7, test-ad4h95-16/big-deployment-1, test-ad4h95-15/big-deployment-1, test-ad4h95-28/small-deployment-62, test-ad4h95-30/small-deployment-181, test-ad4h95-6/medium-deployment-19, test-ad4h95-19/medium-deployment-22, test-ad4h95-27/big-deployment-1, test-ad4h95-23/big-deployment-1
2024-07-12T17:05:23.3688380Z measurement call WaitForControlledPodsRunning - WaitForRunningDaemonSets error: 1 objects timed out: DaemonSets: test-ad4h95-1/daemonset-0
2024-07-12T17:05:23.3689787Z measurement call WaitForControlledPodsRunning - WaitForRunningStatefulSets error: 1 objects timed out: StatefulSets: test-ad4h95-19/medium-statefulset-0
2024-07-12T17:05:23.3692806Z measurement call WaitForControlledPodsRunning - WaitForRunningDeployments error: 10 objects timed out: Deployments: test-ad4h95-23/big-deployment-1, test-ad4h95-20/medium-deployment-2, test-ad4h95-16/small-deployment-7, test-ad4h95-16/big-deployment-1, test-ad4h95-15/big-deployment-1, test-ad4h95-28/small-deployment-62, test-ad4h95-30/small-deployment-181, test-ad4h95-6/medium-deployment-19, test-ad4h95-19/medium-deployment-22, test-ad4h95-27/big-deployment-1
2024-07-12T17:05:23.3695666Z measurement call PodPeriodicCommand - cilium-agent-PodPeriodicCommand error: hit timeout of 55s while executing command Profiles in pod kube-system/cilium-7zvcg]
2024-07-12T17:05:23.3696966Z E0712 17:05:23.366696   18165 clusterloader.go:255] --------------------------------------------------------------------------------
```

```
2024-07-12T15:39:00.6230165Z E0712 15:39:00.618778   18165 wait_for_controlled_pods.go:648] WaitForControlledPodsRunning: error for test-ad4h95-6/medium-deployment-19: got context deadline exceeded while waiting for 30 pods to be running in namespace(test-ad4h95-6), controlledBy(medium-deployment-19) - summary of pods : Pods: 30 out of 30 created, 29 running (29 updated), 1 pending scheduled, 0 not scheduled, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
```

```
2024-07-12T16:01:40.7318045Z E0712 16:01:40.729172   18165 wait_for_controlled_pods.go:648] WaitForControlledPodsRunning: error for test-ad4h95-19/medium-statefulset-0: got context deadline exceeded while waiting for 21 pods to be running in namespace(test-ad4h95-19), controlledBy(medium-statefulset-0) - summary of pods : Pods: 20 out of 21 created, 20 running (20 updated), 0 pending scheduled, 0 not scheduled, 0 inactive, 1 terminating, 0 unknown, 0 runningButNotReady 
```

It seems that the KCM and scheduler on master-4 have disproportionately high load compared to the other master instances:
![kcm-cpu](https://github.com/user-attachments/assets/8971842f-ed6d-4e8d-87e1-8886eee586e9)
![kcm-memory](https://github.com/user-attachments/assets/f3797f20-be51-4897-af52-878e0285f994)
![scheduler-cpu-mem](https://github.com/user-attachments/assets/0386439e-73f6-4464-9c1b-a25edbc4602a)

I'll look at some data from other runs to see if the spread is comparable. I'm wondering if it might be worth backing down on the LOAD and DELETE throughput

**Comment by marseel** [comment]
A disproportional load is expected, kcm / scheduler use leader election. 

One typical case is when nodes run out of capacity for new pods being scheduled. 
Another related thing could be slow scheduler due to https://github.com/cilium/cilium/issues/33462

**Comment by thorn3r** [comment]
Yeah I wasn't even thinking about leader election, should have been obvious with all the other instances at identical usage :sweat_smile: Testing with the anti-affinity rule removed from the agent daemonset :crossed_fingers:

**Comment by thorn3r** [comment]
etcd is filling up again, despite increasing etcd volume size from 20gb to 50gb. I'll see if we are collecting any metrics in the snapshot that could help identify the cause
```
2024-07-15T20:27:57.8624302Z E0715 20:27:57.860220   12973 clusterloader.go:248] --------------------------------------------------------------------------------
2024-07-15T20:27:57.8625797Z E0715 20:27:57.860234   12973 clusterloader.go:249] Test Finished
2024-07-15T20:27:57.8626919Z E0715 20:27:57.860240   12973 clusterloader.go:250]   Test: ./testing/load/config.yaml
2024-07-15T20:27:57.8628018Z E0715 20:27:57.860245   12973 clusterloader.go:251]   Status: Fail
2024-07-15T20:27:57.8630059Z E0715 20:27:57.860250   12973 clusterloader.go:253]   Errors: [namespace test-khs9w6-28 object medium-statefulset-0 updating error: etcdserver: mvcc: database space exceeded
2024-07-15T20:27:57.8632342Z namespace test-khs9w6-1 object medium-statefulset-0 updating error: etcdserver: mvcc: database space exceeded
2024-07-15T20:27:57.8634250Z namespace test-khs9w6-25 object medium-statefulset-0 updating error: etcdserver: mvcc: database space exceeded
2024-07-15T20:27:57.8636051Z namespace test-khs9w6-5 object small-job-0 updating error: etcdserver: mvcc: database space exceeded
2024-07-15T20:27:57.8637751Z namespace test-khs9w6-14 object small-job-0 updating error: etcdserver: mvcc: database space exceeded
2024-07-15T20:27:57.8639431Z namespace test-khs9w6-29 object big-job-0 updating error: etcdserver: mvcc: database space exceeded
2024-07-15T20:27:57.8641087Z namespace test-khs9w6-17 object big-job-0 updating error: etcdserver: mvcc: database space exceeded
2024-07-15T20:27:57.8642751Z namespace test-khs9w6-18 object big-job-0 updating error: etcdserver: mvcc: database space exceeded
2024-07-15T20:27:57.8644396Z namespace test-khs9w6-3 object big-job-0 updating error: etcdserver: mvcc: database space exceeded
2024-07-15T20:27:57.8646033Z namespace test-khs9w6-28 object big-job-0 updating error: etcdserver: mvcc: database space exceeded
2024-07-15T20:27:57.8647761Z namespace test-khs9w6-21 object big-deployment-1 updating error: etcdserver: mvcc: database space exceeded
2024-07-15T20:27:57.8649528Z namespace test-khs9w6-18 object big-deployment-0 updating error: etcdserver: mvcc: database space exceeded
2024-07-15T20:27:57.8651429Z namespace test-khs9w6-15 object big-deployment-0 updating error: etcdserver: mvcc: database space exceeded
2024-07-15T20:27:57.8653202Z namespace test-khs9w6-13 object big-deployment-1 updating error: etcdserver: mvcc: database space exceeded
```

**Comment by thorn3r** [comment]
Rate-limiting also seems to be a (benign) issue. Google revoked a partial increase to 19k (I asked for 20k, they granted 19k - didn't realize they would revoke the increase when I didn't respond to the lengthy survey they sent :sweat_smile: ). It looks like this may continue in any case, however, since during deletion kops is making ~700 requests per second, and I don't think they're going to bump our limit to 40k. The deletion still finishes, but it fills the logs with tons of errors
![kops-read-requests](https://github.com/user-attachments/assets/4bfc788b-9dc5-4dfc-9a07-3c7eb40bfe19)

**Comment by thorn3r** [comment]
Updated create-cluster to increase the etcd backend quota from 2gb to 8gb: https://github.com/cilium/scale-tests-action/pull/12/commits/efbf8e395175459d4badde52d4473050d6986d60

**Comment by thorn3r** [comment]
3k test was successful after increase the etcd backend quota to 8gb. The results look great with CEP Queue Delay and CEP Propagation remaining relatively the same as 1k nodes, at just around 1 second each.

Policy implementation delay has actually dropped a bit for p99 (probably due to the various improvements added since then) from 0.045s to .007s. p90 and p50 remained the same.

Data points are 500, 1k, 2k, and 3k nodes

![policy-delay](https://github.com/user-attachments/assets/a2451901-54de-4867-b959-e352b312264a)
![cepprop](https://github.com/user-attachments/assets/f6e1f3ab-4e90-4051-9b03-a785f144d1f2)

Count of CEPs to help correlate test size (500, 1k, 2k, 3k)
![ceps](https://github.com/user-attachments/assets/5fd399ff-1f46-40ca-9e09-aca7a7862403)

**Comment by thorn3r** [comment]
very quickly captured some data from the CP and etcd in [this gist](https://gist.github.com/thorn3r/fc675986a89c9a25692aead06f2609e5). etcd is falling over when crossing the 4k threshold. Peer RTT is wildly high and it looks like disk IO is slowing it down to a crawl, causing leader election to fail and the cluster to lose quorum. I'll look into the volume type options and see if there's something more performant we can use

**Comment by thorn3r** [comment]
Increasing the etcd volume size to 500gb maxes out possible throughput at 15k IOPS, compared to 1.7k at 50gb.
This increase decreased the number of slow applies significantly:

With 50gb volumes:
```
grep 'etcd_server_slow_apply_total' /tmp/etcd.metrics                                                                                                                                                                                                                                                               ✔  12s  
# HELP etcd_server_slow_apply_total The total number of slow apply requests (likely overloaded from slow disk).
# TYPE etcd_server_slow_apply_total counter
etcd_server_slow_apply_total 59953
```

With 500gb volumes:
```
grep 'etcd_server_slow_apply_total' /tmp/etcd500.metrics                                                                                                                                                                                                                                                                    ✔ 
# HELP etcd_server_slow_apply_total The total number of slow apply requests (likely overloaded from slow disk).
# TYPE etcd_server_slow_apply_total counter
etcd_server_slow_apply_total 3306
```

This got us very close to 5k, falling short at 4829 healthy nodes:
```
ks get ds                                                                                                                                                                                                                                                            ✔  24s   scale-100-10031977526-1.k8s.local ⎈ 
NAME                       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
cilium                     4829      4829      4036    4829         4036        kubernetes.io/os=linux   120m
cilium-envoy               4829      4829      4041    4829         4041        kubernetes.io/os=linux   120m
cloud-controller-manager   5         5         5       5            5           <none>                   121m
kops-controller            5         5         5       5            5           <none>                   121m
```

However, shortly after the etcd cluster died again. I've collected all the metrics and added them to the [info-dump gist](https://gist.github.com/thorn3r/fc675986a89c9a25692aead06f2609e5)

**Comment by dlapcevic** [comment]
Is it safe to assume that etcd failures are due to many writes?
I remember that the bottleneck we were facing was related to CES watchers (5k), which affects KCP performance and not etcd, since they are read requests. That's why we ended up having 10/s rate limiter on CES updates, because more than that (10/s x 5k = 50k/s CES events need to be sent to watchers) was saturating the KCP CPU and affecting other KCP operations.

The default for CES size is 100, same as K8s EndpointSlice. https://github.com/cilium/cilium/blob/v1.16/operator/pkg/ciliumendpointslice/cell.go#L77

We’ve tested Cilium with CES on GKE, and found that smaller size, such as 50, could scale higher and had better performance.
@marseel should we also test different CES sizes, and then consider changing the default before making it GA?

**Comment by marseel** [comment]
> Is it safe to assume that etcd failures are due to many writes?

I think most likely it was misconfiguration / overload during the bootstrap phase. The test for 5k nodes failed during provisioning last 1k nodes - not during the real test. I've talked with Tim offline. Essentially:
- we were setting inflights to 
```
spec.kubeAPIServer.maxRequestsInflight=800 \
--set spec.kubeAPIServer.maxMutatingRequestsInflight=400
```
which is probably way to high for n2-standard-64 machines. Tim followed up with PR: https://github.com/cilium/scale-tests-action/pull/16 to make it configurable and we will switch to 640 inflights and rerun the test. We could also split provisioning into smaller batches of 500 nodes instead of 1k nodes. 
But this suggests that we should improve bootstrapping of cilium-agent - currently, we run lots of parallel informers at the beginning + if apiserver fails, we close connections / fail cilium-agent healthcheck / potentially restart agent - there is some ongoing work in https://github.com/cilium/cilium/pull/32724 to improve that, but there is probably more we could do here.
While for normally operating clusters (with autoscaler scaling nodes etc) it doesn't matter as much - it matters for the case when apiserver goes down - we want to make sure it can recover, no matter what's the number of nodes. 

> We’ve tested Cilium with CES on GKE, and found that smaller size, such as 50, could scale higher and had better performance.
[Marcel Zięba](https://github.com/marseel) should we also test different CES sizes, and then consider changing the default before making it GA?

Was the 50 batch size with identity-based or fcfs? 
With 4k nodes test, we were getting peak 30 qps of CES updates with default 100 size and fcfs:
![image](https://github.com/user-attachments/assets/cd7369ea-f693-40b8-a5fb-b775f62ebce0)
with very reasonable latency of API calls:
![image](https://github.com/user-attachments/assets/c6f6d5d6-1c5c-4693-8989-440047d4b459)
so I'm not sure, to be honest.

**Comment by bowei** [comment]
@dlapcevic FYI

**Comment by elias-dbx** [comment]
What etcd version are you using? We can scale to ~15k nodes using the following config:
1. --quota-backend-bytes=100GB
2. --auto-compaction-retention=30m
3. --auto-compaction-mode=periodic
4. daily defragment
5. etcd 3.5.14
6. 96 cores and 256GB RAM per etcd node
7. 5 etcd nodes

> However, shortly after the etcd cluster died again
Did the etcd nodes OOM? Was quorum broken? What was the actual failure mode?

**Comment by elias-dbx** [comment]
You may also want to try enabling the alpha watch list feature, that supposedly should drastically reduce the resource requirements for LIST requests: https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/3157-watch-list/README.md

I noticed that the cilium agents hammer the k8s API server pretty hard with LIST requests during startup which can manifest as an OOM on the k8s API server.

**Comment by elias-dbx** [comment]
If the cilium agents use the client-go library setting `KUBE_FEATURE_WatchListClient=true` should enable the functionality.
https://kubernetes.io/blog/2024/08/12/feature-gates-in-client-go/#overriding-client-go-feature-gates

The k8s API server and control plane have separate toggles for the watch list client: https://kubernetes.io/docs/reference/using-api/api-concepts/#streaming-lists

**Comment by dlapcevic** [comment]
> We can scale to ~15k nodes

Hi @elias-dbx, did you manage to run the ClusterLoader2 load test (https://github.com/kubernetes/perf-tests/tree/master/clusterloader2/testing/load) on 15k nodes with Cilium installed?

I would be interested to understand the K8s and Cilium configuration, and test metrics and results for it.

GKE is only recently able to scale up from 5k to 7.5k nodes with Dataplane v2 (Cilium), considering the massive load on KCP coming from network policy enforcement system (Cilium Endpoint, Cilium Endpoint Slice, Cilium Identity).
(GKE ref: https://cloud.google.com/kubernetes-engine/docs/concepts/dataplane-v2#node-limit-increase-7500)

**Comment by marseel** [comment]
FYI, I've been playing with our infrastructure last week, and by changing a few things, like:
- switching from ipam clusterpool to ipam kubernetes
- increasing workers on CCM manager
- Simplifying kops validation that cluster is running

I successfully bootstrapped 5k nodes cluster with Cilium installed - I haven't performed a full e2e CL2 load test yet, but it's definitely a step towards running 5k scale test. Previous attempts from Tim failed on bootstrapping cluster. 

Run: https://github.com/cilium/cilium/actions/runs/11054764777/job/30712334733
(please ignore exporting data to GS error)

For graduation to Stable on a similar node, would you mind @dlapcevic if we would deprecate ces-slicing-mode, remove identity-based mode, and stick to fcfs?
I will double-check if migration from identity-based to fcfs-based is safe, but I assume you have already tested that too?

**Comment by dlapcevic** [comment]
>For graduation to Stable on a similar node, would you mind @dlapcevic if we would deprecate ces-slicing-mode, remove identity-based mode, and stick to fcfs?

I agree with deprecating Identity batch mode and ces-slicing-mode flag, and making FCFS mode the default.

>I will double-check if migration from identity-based to fcfs-based is safe, but I assume you have already tested that too?

Yes, there were no issues from migrating from Identity to FCFS batching mode. The FCFS mode is very simple, it keeps adding endpoints to the largest CES in the namespace. AFAIK, the only thing is that the CESs won't be compressed immediately, but rather over time with pod churn.
It's good to double check.

**Comment by thorn3r** [comment]
Hey @tamilmani1989 sorry I missed your comment. I'm going to un-assign myself from this ticket, I don't have the capacity to work on it at the moment

**Comment by joestringer** [comment]
All of the subtasks of this issue have been completed and the scope of remaining items is unclear.

If we think that there are further tasks to take in the spirit of this issue, I would suggest filing a brand new issue to track those so that we can more easily identify the scope and avoid long-running issues with vague deliverables.
