### ISSUE TITLE
CFP: Move hubble v1.Events drop emitter to beta

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#33975]
Cilium v1.16 introduced support to forward drop events towards the kube-apiserver through `v1.Events` in order to provide better visibility into cluster networking behaviour to users ([CFP](https://github.com/cilium/cilium/issues/29399), [PR](https://github.com/cilium/cilium/pull/29565)). The feature is enabled through Helm via `hubble.dropEventEmitter` or through the cilium-agent commandline flag `--hubble-drop-events`.

This issue can be used to collect feedback about the feature, the information it provides, and the scalability / performance impacts that it introduces.

### Tasks
- [ ] Define beta graduation criteria
  - [ ] Review output format (For example, drop reasons)
  - [ ] Review ratelimiting/QPS behaviour and maximum event emit rates per node
  - [ ] Enable in scale tests and assess impact with varying traffic drop rates
  - [ ] Validate behaviour with DDoS-style drop pattern
  - [ ] Add a documentation page for the feature
- [ ] feedback improvements
  - [ ] consolidate event rate-limit / throttling flags, see [this comment](https://github.com/cilium/cilium/pull/41693#pullrequestreview-3422772881).
  - [ ] limit the number of policies shown in the message when `--hubble-drop-events-extended` is provided, see [this comment](https://github.com/cilium/cilium/pull/41693#pullrequestreview-3415977311).

**Comment by robinelfrink** [comment]
We currently have four of our kubernetes clusters running Cilium v1.16 for a couple of weeks, with the drop event emitter active. No issues found. More clusters will be upgrade in the coming 1 or 2 months.

The created events triggered prometheus alerts we forgot about, from our coreos+iptables-tailer days 😎

**Comment by joestringer** [comment]
@robinelfrink awesome, thanks for sharing. Are you able to speak at all about scale parameters like size of cluster, overall connection rate, k8s control plane resource usage or more specifically how many drop events you are handling? I think that the primary concern overall with this feature is to what extent the k8s control plane will be able to handle these events.

**Comment by robinelfrink** [comment]
Small clusters (6-10 worker nodes), some 150-200 pods each, and packet drop events ranging between 500 and 70000 in the past week.

**Comment by joestringer** [comment]
@Fabccc It looks like the [original PR](https://github.com/cilium/cilium/pull/29565) didn't add the functionality to pull FQDNs from the flow, but it should be possible to extend the feature for that use case.

**Comment by kaworu** [comment]
Hi @robinelfrink 👋 are you still interested to work on this issue?

**Comment by robinelfrink** [comment]
> Hi [@robinelfrink](https://github.com/robinelfrink) 👋 are you still interested to work on this issue?

Sure, I'm happy to help in any way I can. Though I'm not really familiar with automated performance tests and such.

**Comment by 41ks** [comment]
The default reasons for generating drop events are `auth_required` and `policy_denied`. I feel like another important reason to include in the defaults is `policy_deny` which indicates a drop due to deny list which is the case with this kind of policy:
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
...
spec:
  egressDeny:
  - toCIDR:
    - 1.2.3.4/32
  endpointSelector:
    matchLabels:
    ...
```
With the current default configs a drop due to such a CNP or CCNP does not generate a k8s event.

**Comment by avthart** [comment]
Great feature! 

It would be helpful if Kubernetes events in Cilium supported an allow/deny list for protocols, similar to Hubble Export.
Being able to filter events by protocol (e.g., TCP, UDP, ICMP) would make it easier to reduce noise and limit the events.

**Comment by 41ks** [comment]
FYI, we have enabled this feature at scale across all our clusters with the following configuration (Cilium v1.19.3):
```yaml
  hubble-drop-events: "true"
  hubble-drop-events-extended: "true"
  hubble-drop-events-interval: "1h"
  hubble-drop-events-reasons: "policy_deny policy_denied"
```
Everything seems to be running smoothly even in our `deny-by-default` clusters.

**Comment by joestringer** [comment]
@41ks thanks for sharing. Are you able to speak at all about scale parameters like size of cluster, overall connection rate, k8s control plane resource usage or more specifically how many drop events you are handling? I think that the primary concern overall with this feature is to what extent the k8s control plane will be able to handle these events.

**Comment by 41ks** [comment]
It is a bit tricky to provide representative numbers. Under normal operation, each of our clusters emits only a few packet drop events per hour, due in part to the aggregation settings for Hubble drop events. As a result, this has a negligible impact on our Kubernetes API server. What I can share, however, is what happens when things go wrong. We recently encountered such a situation in a staging cluster that began dropping a large number of packets (a few million per minute).

Cluster stats:
- Nodes: a few hundred
- Pods: a few thousand
- kube-apiserver load: a few hundred HTTP requests per second

Despite this, the system remained stable, and the number of PacketDrop events emitted to Kubernetes peaked at around 100 per minute, which was easily handled by the kube-apiserver.
