### ISSUE TITLE
Tracking issue for experimental load-balancing control-plane

### ISSUE THREAD

**Issue by joamaki** [cilium/cilium#34176]
This issue gathers the tasks related to getting `pkg/loadbalancer/experimental` to feature parity with existing implementation.

```[tasklist]
### Tasks
- [x] Uses of ServiceCache/ServiceManager getters migrated to Table[T] queries. Initially via a shim? Data types not a exact match, perhaps API can be simplified first.
- [ ] Reimplement reflector with k8s.ListerWatcherToObservable (similar to pkg/k8s/statedb.go). See early PRs for the code for this. This way we don't have a useless cache.Store holding the v1.Service etc. objects. Need to commit initial list in one go to avoid restoration issues! HostPort with Table[LocalPod]. This will require that we've first converted every use of `Resource[Service]` etc. over to `Table[Service]` etc. Not a goal for v1.18.
- [x] Reimplement pkg/policy/k8s/service.go against new control-plane
- [x] Remove cilium-dbg map events support for lbmaps (from sysdump as well)
- [ ] CI workflow for running stress tests when experimental etc. packages change. Or perhaps stress testing unit tests when a package containing txtar files changes
- [x] Review all metrics related to services etc. and make sure the new implementation emits them as well. Especially important to keep all metrics that are documented. Also consider all BPF map metrics (map ops total etc.)
- [x] Add lrp-address-matcher-cidrs option to limit what addresses can be used with addressMatcher (https://github.com/cilium/cilium/pull/39858) 
- [x] k8s client HA update on backend changes (https://github.com/cilium/cilium/pull/37601/files#top). Needed once watchers/service.go is removed. https://github.com/cilium/cilium/issues/38574#issuecomment-2772809335
- [ ] Go through code coverage for all the tests (go test -coverprofile=...) and expand coverage as much as possible
- [x] Migrate uses of pkg/maps/lbmap to pkg/loadbalancer/maps (e.g. cilium-dbg bpf lb ...)
- [x] KubeProxy Healthz interface (GetLastUpdatedTs() etc.) https://github.com/cilium/cilium/pull/39195/files#r2068167441
- [ ] Change pkg/dial to use Table[Frontend] instead of Resource[Service] to resolve to IP
- [x] Remove Resource[CiliumEnvoyConfig]
- [x] Delay endpoint regeneration until Envoy listeners have been created (https://github.com/cilium/cilium/pull/39910)
- [ ] Log hive health transitions? https://github.com/cilium/cilium/pull/37855
```

**Comment by julianwiedmann** [comment]
@joamaki just checking, are you still keeping this list up-to-date? Is there anything left that we might want to fork off into individual issues, so that it's more visible to folks who'd like to contribute?

**Comment by joamaki** [comment]
Let's close this.
