### ISSUE TITLE
Debug all master Jenkins failures and make it reliable

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3459]
Need triaging / RCA:
- [ ] Runtime L3L4 Test connect timeout: https://github.com/cilium/cilium/issues/3588
- [ ] endpoint BPF program generation failed https://github.com/cilium/cilium/issues/3549
- [ ] Upgrade test failed in K8s 1.8: https://github.com/cilium/cilium/issues/3657

Fixed / closed : 
- [x] Kafka policy ingress failure: https://github.com/cilium/cilium/issues/3502
- [x] NAT46 test flake: https://github.com/cilium/cilium/issues/3471
- [x] EndpointSetConfig issue https://github.com/cilium/cilium/issues/3489
- [x] Containers can't connect https://github.com/cilium/cilium/issues/3493
- [x] TCP keepAlive issues https://github.com/cilium/cilium/issues/3492
- [x] egress flows removed during CT cleanup : https://github.com/cilium/cilium/issues/3558
- [x] Cilium Agent died: https://github.com/cilium/cilium/issues/3491
- [x] Endpoint recovery on restart : https://github.com/cilium/cilium/issues/3467
- [x] GuestBook test: https://github.com/cilium/cilium/issues/3462
- [x] Invalid NUL character: https://github.com/cilium/cilium/issues/3584
- [x] Error installing kubeadm: https://github.com/cilium/cilium/issues/3586
- [x] Pod did not terminate in timeout window: https://github.com/cilium/cilium/issues/3620
- [x] PoliciesAcrossNamespaces test failure: https://github.com/cilium/cilium/issues/3623
- [x] K8s test CNP reviews app: https://github.com/cilium/cilium/issues/3470

RCA'd, but not fixed:
- [ ] Error doing policymap L3+L4 updates: https://github.com/cilium/cilium/issues/3621
