### ISSUE TITLE
feat: IP packet tracing implementation

### ISSUE THREAD

**Issue by sypakine** [cilium/cilium#35057]
Tracking issue for IP packet tracing feature implementation.

Feature: https://github.com/cilium/design-cfps/blob/main/cilium/CFP-33716-packet-tracing.md

During review of implementation, found refactoring is required for notification structs:

https://github.com/cilium/cilium/pull/33957/commits/93820ad2430742325242025c7993e084ecfdd48b

This is easier to implement and write tests for in a separate PR.

```[tasklist]
### Tasks
- [ ] https://github.com/cilium/cilium/pull/35059
- [ ] https://github.com/cilium/cilium/pull/35413
- [ ] https://github.com/cilium/cilium/pull/33957
- [ ] https://github.com/cilium/cilium/pull/36825
```
