### ISSUE TITLE
Add bpfps to docs and troubleshooting tools

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3917]
New tool by @jessfraz to list and diagnose BPF programs
https://github.com/genuinetools/bpfps

**Tasks:**
- [ ] Add bpfps to cilium-bugtool
- [ ] Refer to it in documentation
- [ ] Add section to troubleshooting guides

**Example:** (https://github.com/genuinetools/bpfps)

```
$ bpfps -h
 _            __
| |__  _ __  / _|_ __  ___
| '_ \| '_ \| |_| '_ \/ __|
| |_) | |_) |  _| |_) \__ \
|_.__/| .__/|_| | .__/|___/
      |_|       |_|

 A tool to list and diagnose bpf programs.  (Who watches the watchers..? :)
 Version: v0.1.0
 Build: be7363d

  -d    run in debug mode
  -v    print version and exit (shorthand)
  -version
        print version and exit
```

```
$ sudo bpfps                                                                                                             
BID                 NAME                TYPE                UID                 MAPS                LOADTIME
21                                      Array               0                   []uint32(nil)       17h25m55.523229433s
22                                      Array               0                   []uint32(nil)       17h25m55.530713603s
```
