### ISSUE TITLE
Trace notification aggregation in BPF

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4080]
The datapath currently has three levels of granularity to provide visibility:
- drops
- trace notifications (per packet) for all forwarding decisions
- debug notifications to troubleshoot the datapath

In order to allow for low overhead tracing in the future, the aggregation of trace notifications should occur in BPF. Trace notifications should be changed to provide the following notifications:

- [x] Make early trace notification before conntrack lookup conditional on a new gate to keep this capability for troubleshooting. If packet is dropped before conntrack, the drop notification will provide the hint that a packet as being processed. (#4828 )
- [x] Push a trace notification whenever a conntrack entry has been created. This notification must include the packet headers to allow differentiating whether the entry was created for a SYN packet or whether it was re-established.
- [x] Add a `last-reported` timestamp to the conntrack entry and use it to send a ~~new~~ trace notification type in a configurable interval (default 5s) which represents ongoing connection activity. (#4875)
  - ~~This notification must include packets and bytes counters. Future iterations of this could contain histograms over the packet sizes.~~
- [x] Defer the sending of the notification until the forwarding decision has been made to ensure that a single notification is sent out for each pass through the BPF datapath. (#4875)

**Comment by joestringer** [comment]
@tgraf regarding the third point:

> Add a last-reported timestamp to the conntrack entry and use it to send a new trace notification type in a configurable interval (default 5s) which represents ongoing connection activity. This notification must include packets and bytes counters. Future iterations of this could contain histograms over the packet sizes.

This is still triggered based on packet receive though, right? It's just that we will only fire an event if at least a specified amount of time has passed since the last event being fired. Furthermore, events would be missed until the next packet arrives.

Second question: Does the packet/bytes counters here aggregate everything since the last notification?

**Comment by tgraf** [comment]
Correct

**Comment by joestringer** [comment]
>  Push a trace notification whenever a conntrack entry has been created. This notification must include the packet headers to allow differentiating whether the entry was created for a SYN packet or whether it was re-established.

The latter is already always included as part of the first 128B of the packet. If needed, we can pull this out into one of the header fields of the TraceNotification message type, by for instance repurposing the dstID or ifindex field. However, without the full feature to do this I don't see a point in adding this yet. The rest of the issue description makes no reference to this, so I assume it's part of future thinking or some other issue.

**Comment by tgraf** [comment]
> Second question: Does the packet/bytes counters here aggregate everything since the last notification?

Yes, that is at least the idea. We already have the counters in the ct table.

**Comment by joestringer** [comment]
@tgraf Do you invision this being a whole new type of notifications beside drop, trace, debug, or do you imagine this taking over trace?

**Comment by joestringer** [comment]
I've updated the description of this issue and highlighted the pieces which are addressed with the current trace notification aggregation implementation.

I'm considering any conntrack-related notifications, including special notifications for creation events and packet/byte counting work to be out-of-scope for 1.2. The core aggregation (well, ratelimiting) work for active connections is all in the PR #4828 . We can revisit and clarify the requirements for another round of this functionality for 1.3 timeframe.

**Comment by tgraf** [comment]
The work effort scheduled for 1.2 have been completed. Moving this to 1.3 for the remaining work.

**Comment by tgraf** [comment]
@joestringer Makes sense. Please create another issue to track the 1.3 and propose it for 1.3 so we can close this and document what has been done for 1.2

**Comment by joestringer** [comment]
@tgraf Done: #5047 #5048
