### ISSUE TITLE
Support CIDR-dependent L4 ingress policies

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4129]
We don't currently support specifying policies that have both "FromCIDR" and "ToPorts" on ingress. This should allow only traffic that matches both of these conditions, and would only apply to traffic that does not originate from another Cilium-managed endpoint.

This is the equivalent issue to #1684, but for ingress.

The interesting thing about ingress is that in many cases (most commonly nodeport with k8s), we lose the source IP address before traffic reaches Cilium, so the CIDR policy would only apply to the source address of the host which the traffic is masqueraded to. Note that CIDR policy does not apply to traffic received from another pod managed by Cilium, so this functionality would not be particularly useful in this scenario.

**UPDATE 2019/06/03**: With v1.6 providing BPF-based nodeport which does not require obscuring the original IP address, this feature may become more interesting.

That said, even for this case, it could potentially shift some complexity for CIDR handling from the `bpf_lxc` program to the `bpf_netdev` program, which would free up some BPF instruction count for use by other features.

In cases of direct routing it may be useful to be able to perform CIDR-dependent ingress L4 policies, as in this case we should still have access to the original source.

Tasks:
* [x] Add IPCache lookup to `bpf_netdev`, propagate these identities through to ingress `bpf_lxc` logic
  * Actual implementation may just introduce the IPCache lookup in ingress policy function
* [x] Ensure that policy lookup in ingress path uses this identity
* [x] Remove ingress CIDR policy lookups from datapath
* [x] Remove plumbing of CIDR map from userspace
* [x] Allow configuration of these policies at the API layer -- https://github.com/cilium/cilium/pull/12482
* [x] Add tests for the new functionality -- https://github.com/cilium/cilium/pull/12482

Follow-up
* [ ] Consider whether there's a better way to structure visibility into CIDR policy in the endpoint API

**Comment by joestringer** [comment]
This would also alleviate deny policy -> allow policy transitions for ingress traffic from host/cluster/world which is addressed in most other cases by #4142.

**Comment by joestringer** [comment]
@tgraf I believe that all of this issue was addressed by #4547, correct?

EDIT: I think it covers the datapath work, but the API allow and testing is still missing. I updated the list of tasks in the description.

**Comment by tgraf** [comment]
@joestringer Anything left here?

**Comment by joestringer** [comment]
@tgraf yes, this is still disallowed for ingress L3+L4 at the API, and entirely untested.

**Comment by bmcstdio** [comment]
Are there any plans to resume work on this anytime soon? I could probably help with testing if this could get backported to 1.6.

**Comment by joestringer** [comment]
I doubt that we're going to put too much more attention into the remaining task in the issue description around providing a more informative view into the CIDR policy in the endpoint API since we rarely use that to debug and by this point we're somewhat familiar with what the output looks like anyway, so we may as well close out this issue. The support is now merged and is planned for inclusion in Cilium v1.8.2.
