### ISSUE TITLE
etcd-operator compatible Cilium bootstrap

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4314]
## Goal

Allow to deploy Cilium with a etcd-operator as part of the deployment resources and have Cilium provide networking connectivity first to allow etcd-operator to be deployed. Then have Cilium connect to the deployed etcd and establish the identity system for global policy. Allow policies to be applied to etcd using fixed/init policies without requiring kvstore access.

## Tasks
- [x] Reserve numeric identity 128-256 for fixed numeric identities
  - [x] Introduce mapping of reserved:<name>
- [x] Add a special label `io.cilium.fixed-identity=identity-name` to allow containers to select a fixed identity
- [ ] Make kvstore connect async on bootstrap with a 3 minute hard timeout. cilium status should not report unhealthy state in this 3 minute period if kvstore cannot be reached. As soon as connectivity has been established once, loss of connectivity to all cluster members is a unhealthy state again.
- [ ] Add desired/realized state logic to endpoint when identity is being resolved for endpoint. Export this via API for visibility.
- [ ] Verify that k8s service handler is fine while kvstore is not reachable yet. We might have to defer allocation of service IDs to later.

## Explanation
- etcd-operator can be defined with special label to select fixed identity
- Respective endpoint will come up immediately without requiring kvstore access.
- All other endpoints will be in init identity state and will have identity resolution pending
- As kvstore connectivity is achieved, other endpoints will transition to real identities
