### ISSUE TITLE
Improve timer handling for conntrack entries

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4400]
* [x] Reduce timers for UDP (#4389)
* [x] Increase CT GC interval (#4408)
  * [x] Add configuration option for the GC collection interval (#4529)
* [x] Add metrics to provide visibility into CT issues (#4507)
* [ ] Generate CT timeout macros during header file generation in the daemon
  * [ ] Add enviroment variables for the timers so they can be defined in a YAML and updated easily on-the-fly
    * [ ] Document how to use these
  * Macros to regenerate: 
    * https://github.com/cilium/cilium/blob/5bcbe807bcc942431301daa411eb23e46ae1a151/bpf/lib/conntrack.h#L31-L34
  * We could do this globally in `node_config.h`, or per-EP in `lxc_config.h`:
    * https://github.com/cilium/cilium/blob/5bcbe807bcc942431301daa411eb23e46ae1a151/daemon/daemon.go#L876
    * https://github.com/cilium/cilium/blob/5bcbe807bcc942431301daa411eb23e46ae1a151/pkg/endpoint/bpf.go#L139

**Comment by joestringer** [comment]
Remaining work should be pretty quick, just passing arguments / env variables from YAML through the daemon to write to config files.

**Comment by joestringer** [comment]
This is no longer a big priority, now that https://github.com/cilium/cilium/pull/6318 is fixed (and the # of connections is configurable). Feel free to reopen if a new motivation comes up for configurability of individual timeout values.
