### ISSUE TITLE
CI Status

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4459]
## Top 5 CI flakes
- [x]  k8s-1.10.K8sValidatedUpdates Updating Cilium stable to master (https://github.com/cilium/cilium/issues/3878) (@raybejjani, @eloycoto)
   - We seem to have missing visibility to debug this further
   - @nebril has a PR out to re-enable microscope in the CI for better datapath visibility on CI failures
- [x] 1.9.K8sValidatedPolicyTest - DNS "redis-master.default.svc.cluster.local" is not ready after timeout (https://github.com/cilium/cilium/issues/3878) (@eloycoto @raybejjani )
- [x] Microscope leftover (https://github.com/cilium/cilium/issues/4579) (@nebril )

## Top Bugs found by CI

- [x] Pods stuck in ContainerCreating: https://github.com/cilium/cilium/issues/4485 #4541 

**Rules:**
- All top CI flake must have an assignee, ping @tgraf if a flake is not assigned
- Top CI flakes are treated equally to priority/high bugs

# CI Pipeline Failures

**Rules:**
- Add all failures of master builds
- Mark as done when CI flake is resolved

## master
Source: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/

**Failures:**
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1075/
   - Needs triage
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1070/
   - known issue (https://github.com/cilium/cilium/issues/4579)
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1067/
  - https://github.com/cilium/cilium/issues/4541, https://github.com/cilium/cilium/issues/4541#issuecomment-398386111
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1064/
  -  runtime.RuntimeValidatedLB Services Policies tests with conntrack enabled (https://github.com/cilium/cilium/issues/4417)
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1063/
  - runtime.RuntimeValidatedLB Services Policies tests with conntrack enabled (https://github.com/cilium/cilium/issues/4417)
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1060/
  - 1.9.K8sValidatedPolicyTest - DNS \"redis-master.default.svc.cluster.local\" is not ready after timeout https://github.com/cilium/cilium/issues/3878
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1018/ 
(https://github.com/cilium/cilium/issues/3878)
   - k8s-1.10.K8sValidatedUpdates Updating Cilium stable to master

## Cilium-PR-Ginkgo-Tests-K8s/
Source: https://jenkins.cilium.io/view/PR/job/Cilium-PR-Ginkgo-Tests-K8s/

**Comment by tgraf** [comment]
Dup #4541

**Comment by manalibhutiyani** [comment]
Status regarding #4431 : In addition to the kafka broker not being ready before executing the first produce, I identified another issue where zookeeper does not respond to kafka broker and kafka broker session times out. This is because the session timeout is currently configured to 20ms. I have also increased the timeouts. PR #4488

**Comment by manalibhutiyani** [comment]
Merged #4488 ( #4431) into master.

**Comment by joestringer** [comment]
Now that we have https://github.com/cilium/cilium/projects/8 , do we need this at all?
