### ISSUE TITLE
Further endpoint regeneration improvements

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5365]
The final goal is to reduce the need to recompute all state relevant for an endpoint via a single 'kitchen-sink' approach. Ideally we can handle different types of events from different parts of the cilium-agent. 

[ Several comments have been integrated into this top level description ]

*High Level:*
- [x] reduce the number of calls to regenerate if possible for endpoints (I am trying to do this in #5359 , for instance).
   - [ ] Needs to split into individual tasks
- [x] reduce the number of compilations per endpoint (e.g., #5294)
- [x] speeding up compilation if compilation is indeed necessary (e.g., #5363 )
- [ ] reducing amount of locking (#5446)
- [x] improve build queue code for endpoints (@tgraf)
- [x] extract configuration updates for endpoints from policy regeneration (@ianvernon)
- [ ] Discuss what happens in failure cases; rollback (if so, what needs to be rolled back - PolicyMap, XDS Cache changes, BPF program itself?)
- [ ] Simplification of policy calculation by removing extraneous / unnecessary fields
    - this will reduce the amount of state kept in the endpoint and will make testing regeneration of policy easier.
- [ ] Add UUID to regenerationContext. This will make it easy to track a single regeneration for an endpoint.

*Individual Tasks:*
- [ ] Get rid of CompilationLock (#5446)
- [ ] Get rid of BuildMutex (#5446)
- [x] Cache header file content to not having to do expensive IO operations before hashing header file
    - #5438
- [ ] Don't hold endpoint mutex in regeneratePolicyAndBPF()
- [x] Remove `DROP_ALL` from datapath (https://github.com/cilium/cilium/pull/5379)
    - This requires removing support for labels on creation.
- [x] Remove `POLICY_INGRESS` and `POLICY_EGRESS` from datapath (#5294)
- [x] Do not blindly TriggerPolicyUpdates for all endpoints when we receive a K8s endpoint update (#5359)

**Comment by ianvernon** [comment]
We also limit the entire endpoint regeneration process based off of the number of CPUs present. This includes application of updated configuration, policy regeneration, PolicyMap updates, etc. We should maintain such a queue limited by number of CPUs, but only for *compilations* of the programs themselves. A lot of the time now, we don't even need to re-compile the programs, especially with changes like #5332 and #5325 coming in. This would allow for a ton of concurrent regenerations with respect to policy, PolicyMap updates, etc., to occur at once (without having a limit based off of CPUs), but have the actual compilation process for endpoints still be gated by the number of CPUs present.

**Comment by ianvernon** [comment]
For tracking purposes, these are my thoughts on multiple other angles to this as well:

* reduce the number of calls to regenerate if possible for endpoints (I am trying to do this in  #5359 , for instance). 
* reduce the number of compilations per endpoint (e.g., #5294)
* speeding up compilation if compilation is indeed necessary (e.g., #5363 )
* reducing amount of locking (which this issue is tracking)
* figuring out what are the main blocking operations in regeneration (which this issue has implemented)

**Comment by tgraf** [comment]
* After #5294 is merged, remove `DROP_ALL` from datapath.

**Comment by aanm** [comment]
@tgraf consider replacing https://github.com/cilium/cilium/blob/359943d562dfcf534794bb2a144706e530f758b4/pkg/endpoint/endpoint.go#L1384 with something faster like https://golang.org/pkg/encoding/gob. When doing this, it will require us to maintain that function for at least 2 releases to allow for downgrades without breaking the restore functionality.

**Comment by tgraf** [comment]
> with something faster like https://golang.org/pkg/encoding/gob. When doing this, it will require us to maintain that function for at least 2 releases to allow for downgrades without breaking the restore functionality.

I think we would have to encode both for a while as otherwise, the downgrade will be a problem.

**Comment by tgraf** [comment]
The remaining work will be scheduled for 1.4

**Comment by ianvernon** [comment]
Moving this to be part of the Policy Engine Improvements project temporarily for tracking purposes.

**Comment by tgraf** [comment]
All the important work on this has been completed. Closing.
