### ISSUE TITLE
1.3 New Prometheus metrics 

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#5382]
# Metrics

## Policy related

- [x] Number of endpoints with ingress policy enforcement #3338
- [x] Number of endpoints with egress policy enforcement #3338
- [ ] L7 latency #3337
- [ ] Count of policy operations labelled by operation={add, update, delete}

## Services

- [x] Number of services #3338 (https://github.com/cilium/cilium/pull/5580) 
- [ ] Traffic used by a service? 

## Endpoint

- [x] Number of connections in endpoint CT.
    - https://github.com/cilium/cilium/pull/5296
- [x] Endpoint garbage collector for CT last run.
    - [x] Number of entries cleaned?
    - https://github.com/cilium/cilium/pull/5296

- [x] Lock avg time. https://github.com/cilium/cilium/pull/5329
- [x] labelled by: state={init, regen, ready…} , restored={true, false} https://github.com/cilium/cilium/pull/5329

## KVStore
PR Out, invalid data -> https://github.com/cilium/cilium/pull/5412
- [ ] Number of inserts per second?
- [ ] Number of updates deletes per second
- [ ] Count of identities entries.
- [ ] Count of ipcache entries.

## Envoy

- [x] Number of proxy redirects #5463 

## Kubernetes

- [x] Number of watcher calls received.  (per type?) https://github.com/cilium/cilium/pull/5621
- [x] Report success of calls. https://github.com/cilium/cilium/pull/5621

## Workloads

- [ ] Label all metrics with subsystem={containerd, crio}
- [ ] Ignored container gauge
- [ ] Count of events labelled by type={create, delete}
- [ ] Count of workloads created labelled by status={success, failed}

## Subroutines

- [x] Restarts and count (counter of starts labelled by subsystem and restart/start)
- [x] Counter of subroutines started labelled by subsystem={envoy, monitor, health} reason={start, restart}

## Clustermesh

- [ ] Gauge of number of remote clusters
- [ ] Last seen timestamps counter labelled by cluster={name from config}

## Controllers

- [x] Gauge of controllers labelled by running/failed

## Ipam

- [x] Count of IP operations labelled by operation_type={allocate, release} and type={ipv4,ipv6} https://github.com/cilium/cilium/pull/5692

## Logs metrics: 
- [x] Represent logs as metrics: https://github.com/cilium/cilium/issues/4268

**Comment by vadorovsky** [comment]
Please include also #4268
