### ISSUE TITLE
Audit Info messages

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#7201]
* [x] `cilium-health/launch/endpoint.go:		log.WithField("netns", netns).WithField("command", cmd).Info("Adding route")` (#7198)
* [x] `cilium-health/launch/endpoint.go:		scopedLog.Info("Failed to kill previous cilium-health instance")` (#7198)
* [x] `cilium-health/launch/endpoint.go:				scopedLog.WithError(err).Info("Couldn't delete cilium-health device")` (#7198)
* [x] `cilium-health/launch/endpoint.go:					Info("Unable to remove netns")` (#7198)
* [x] `cilium/cmd/cleanup.go:	log.Info("Trying to unmount ", cgroupRoot)`
* [x] `cilium/cmd/debuginfo.go:func runDebugInfo(cmd *cobra.Command, args []string) {`
* [x] `daemon/cleanup.go:			log.WithField("signal", s).Info("Exiting due to signal")`
* [x] `daemon/daemon.go:	log.Info("Setting sysctl net.core.bpf_jit_enable=1")`
* [x] `daemon/daemon.go:	log.Info("Setting sysctl net.ipv4.conf.all.rp_filter=0")`
* [x] `daemon/daemon.go:	log.Info("Setting sysctl net.ipv6.conf.all.disable_ipv6=0")`
* [x] `daemon/daemon.go:	ctmap.InitMapInfo(option.Config.CTMapEntriesGlobalTCP, option.Config.CTMapEntriesGlobalAny)`
* [x] `daemon/daemon.go:	log.Info("Clearing leftover Cilium veths")` (#7198)
* [x] `daemon/daemon.go:		log.Info("Kubernetes information:")`
* [x] `daemon/daemon.go:			log.Info("k8s mode: Allowing localhost to reach local endpoints")`
* [x] `daemon/daemon.go:	log.Info("Initializing node addressing")`
* [x] `daemon/daemon.go:	log.Info("Initializing IPAM")`
* [x] `daemon/daemon.go:	log.Info("Addressing information:")`
* [x] `daemon/daemon.go:		log.Info("Annotating k8s node with CIDR ranges")`
* [x] `daemon/daemon.go:			log.Info("Cluster-ID is not specified, skipping ClusterMesh initialization")`
* [x] `daemon/daemon.go:			log.WithField("path", path).Info("Initializing ClusterMesh routing")`
* [x] `daemon/daemon.go:		}).Info("Attached BPF program to existing container")`
* [x] `daemon/daemon_main.go:		log.Info("linking environment: OK!")`
* [x] `daemon/daemon_main.go:	log.Info("     _ _ _")`
* [x] `daemon/daemon_main.go:	log.Info(" ___|_| |_|_ _ _____")`
* [x] `daemon/daemon_main.go:	log.Info("|  _| | | | | |     |")`
* [x] `daemon/daemon_main.go:	log.Info("|___|_|_|_|___|_|_|_|")`
* [x] `daemon/daemon_main.go:		log.Info("Envoy version check disabled")`
* [x] `daemon/daemon_main.go:				Info("Waiting for the underlying interface to be initialized with containers")`
* [x] `daemon/daemon_main.go:				Info("Underlying interface initialized with containers!")`
* [x] `daemon/daemon_main.go:	log.Info("Initializing daemon")`
* [x] `daemon/daemon_main.go:	log.Info("Validating configured node address ranges")`
* [x] `daemon/daemon_main.go:	log.Info("Starting connection tracking garbage collector")`
* [x] `daemon/daemon_main.go:	log.Info("Launching node monitor daemon")`
* [x] `daemon/daemon_main.go:		log.Info("No previous state to restore. Cilium will not manage existing containers")` (#7198)
* [x] `daemon/daemon_main.go:			log.Info("Searching for existing containers...")`
* [x] `daemon/daemon_main.go:		Info("Daemon initialization completed")`
* [x] `daemon/daemon_main.go:	log.Info("Initializing Cilium API")`
* [ ] `daemon/endpoint.go:				ep.Logger(daemonSubsys).Info("Endpoint has sidecar proxy, returning from synchronous creation request before regeneration has succeeded")`
* [x] `daemon/fqdn.go:		log.WithField(logfields.Path, preCachePath).Info("Reading toFQDNs pre-cache data")`
* [x] `daemon/health.go:	log.Info("Building health endpoint")` (#7198)
* [x] `daemon/health.go:	log.Info("Launching Cilium health daemon")`
* [x] `daemon/health.go:	log.Info("Launching Cilium health endpoint")`
* [x] `daemon/health.go:				log.Info("Stopping health endpoint")`
* [x] `daemon/k8s_watcher.go:		log.Info("Waiting until all pre-existing resources related to policy have been received")`
* [x] `daemon/k8s_watcher.go:		log.Info("All pre-existing resources related to policy have been received; continuing")`
* [x] `daemon/k8s_watcher.go:	log.Info("Enabling k8s event listener")`
* [ ] `daemon/k8s_watcher.go:	scopedLog.Info("NetworkPolicy successfully added")`
* [ ] `daemon/k8s_watcher.go:	scopedLog.Info("NetworkPolicy successfully removed")`
* [x] `daemon/k8s_watcher.go:		}).Info("Kubernetes service definition changed")` (#7198)
* [ ] `daemon/k8s_watcher.go:	scopedLog.Info("Kubernetes ingress added")`
* [ ] `daemon/k8s_watcher.go:		scopedLog.Info("Imported CiliumNetworkPolicy")`
* [ ] `daemon/k8s_watcher.go:		scopedLog.Info("Deleted CiliumNetworkPolicy")`
* [x] `daemon/loadbalancer.go:				scopedLog.Info("Restored service ID from datapath")` (#7198)
* [x] `daemon/loadbalancer.go:	log.Info("Syncing BPF LBMaps with daemon's LB maps...")`
* [x] `daemon/loadbalancer.go:			}).Info("Frontend service ID read from BPF map was out of sync with KVStore, got new ID")` (#7198)
* [ ] `daemon/policy.go:		logger.WithField(logfields.CiliumNetworkPolicy, rules.String()).Info("Policy Add Request")`
* [ ] `daemon/policy.go:	logger.WithField(logfields.PolicyRevision, rev).Info("Policy imported via API, recalculating...")`
* [x] `daemon/state.go:		log.Info("Endpoint restore is disabled, skipping restore step")`
* [x] `daemon/state.go:	log.Info("Restoring endpoints from former life...")`
* [x] `daemon/state.go:		log.Info("No old endpoints found.")`
* [x] `daemon/state.go:				scopedLog.Info("No workload could be associated with endpoint being restored, ignoring")` (#7198)
* [x] `daemon/state.go:	}).Info("Endpoints restored")`
* [x] `daemon/state.go:					}).Info("Security identity for endpoint is different from the security identity restored for the endpoint")`
* [x] `daemon/state.go:			scopedLog.WithField(logfields.IPAddr, []string{ep.IPv4.String(), ep.IPv6.String()}).Info("Restored endpoint")`
* [x] `daemon/state.go:		}).Info("Finished regenerating restored endpoints")`
* [x] `daemon/state.go:			scopedLog.Info("C header file not found. Ignoring endpoint")` (#7198)
* [x] `monitor/monitor.go:	log.Info("Beginning to read cilium agent events")`
* [x] `monitor/monitor.go:	defer log.Info("Stopped reading cilium agent events")`
* [x] `monitor/monitor.go:	scopedLog.Info("Beginning to read perf buffer")`
* [x] `monitor/monitor.go:	defer scopedLog.Info("Stopped reading perf buffer")`
* [x] `monitor/monitor_main.go:	log.WithField(logfields.Signal, sig).Info("Exiting due to signal")`
* [x] `operator/k8s_service_sync.go:		}).Info("Kubernetes service definition changed")` (#7198)
* [x] `operator/k8s_service_sync.go:		log.Info("Starting to synchronize Kubernetes services to kvstore")`
* [x] `operator/main.go:			log.Info("Received termination signal. Shutting down")`
* [ ] `pkg/api/socket.go:		}).Info("Group not found")`
* [x] `pkg/bpf/bpf_linux.go:		}).Info("Map type mismatch for BPF map")` (#7198)
* [x] `pkg/bpf/bpf_linux.go:		}).Info("Key-size mismatch for BPF map")` (#7198)
* [x] `pkg/bpf/bpf_linux.go:		}).Info("Value-size mismatch for BPF map")` (#7198)
* [x] `pkg/bpf/bpf_linux.go:		}).Info("Max entries mismatch for BPF map")` (#7198)
* [x] `pkg/bpf/bpf_linux.go:		}).Info("Flags mismatch for BPF map")` (#7198)
* [x] `pkg/bpf/bpf_linux.go:		scopedLog.Info("Removing map to allow for property upgrade (expect map data loss)")` (#7198)
* [x] `pkg/clustermesh/remote_cluster.go:				rc.getLogger().Info("Established connection to remote etcd")`
* [x] `pkg/clustermesh/remote_cluster.go:				rc.getLogger().Info("All resources of remote cluster cleaned up")`
* [x] `pkg/clustermesh/remote_cluster.go:	rc.getLogger().Info("New remote cluster discovered")`
* [x] `pkg/clustermesh/remote_cluster.go:				rc.getLogger().Info("etcd configuration has changed, re-creating connection")`
* [x] `pkg/clustermesh/remote_cluster.go:				rc.getLogger().Info("Closing connection to remote etcd")`
* [x] `pkg/clustermesh/remote_cluster.go:	rc.getLogger().Info("Remote cluster disconnected")`
* [x] `pkg/datapath/maps/map.go:		log.WithField(logfields.Path, path).Info("Removed stale bpf map")`
* [ ] `pkg/endpoint/bpf.go:				Info("Recompiled endpoint BPF program")`
* [ ] `pkg/endpoint/bpf.go:			e.getLogger().WithError(err).Info("Reloaded endpoint BPF program")`
* [ ] `pkg/endpoint/endpoint.go:	e.getLogger().Info("Removed endpoint")`
* [ ] `pkg/endpoint/endpoint.go:		}).Info("Invalid state transition skipped")`
* [ ] `pkg/endpoint/endpoint.go:		e.getLogger().WithError(err).Info("Cannot run labels resolver")`
* [ ] `pkg/endpoint/endpoint.go:	e.getLogger().Info("New endpoint")`
* [ ] `pkg/endpoint/policy.go:	scopedLog.Info("Completed endpoint regeneration")`
* [ ] `pkg/endpoint/policy.go:		}).Info("Identity of endpoint changed")`
* [x] `pkg/endpointmanager/conntrack.go:				scopedLog.Info(msg)` (#7198)
* [x] `pkg/endpointmanager/conntrack.go:		log.Info("Initial scan of connection tracking completed")`
* [x] `pkg/envoy/accesslog_server.go:			log.Info("Envoy: Accepted access log connection")`
* [x] `pkg/envoy/accesslog_server.go:		log.Info("Envoy: Closing access log connection")`
* [x] `pkg/envoy/envoy.go:			log.Info("Envoy: Sleeping for 100ms before restarting proxy")`
* [x] `pkg/envoy/envoy.go:				scopedLog.Info(msg)`
* [x] `pkg/envoy/xds/server.go:		logfields.XDSVersionInfo: req.GetVersionInfo(),`
* [ ] `pkg/envoy/xds/server.go:	streamLog.Info("starting xDS stream processing")`
* [ ] `pkg/envoy/xds/server.go:				streamLog.Info("xDS stream closed")`
* [x] `pkg/envoy/xds/server_e2e_test.go:		log.Info("comp1 callback received with ", err)`
* [x] `pkg/envoy/xds/server_e2e_test.go:		log.Info("comp2 callback received with ", err)`
* [ ] `pkg/health/server/prober.go:		scopedLog.WithError(err).Info("Failed to express greeting to host")`
* [ ] `pkg/health/server/server.go:		log.WithError(err).Info("Failed to run ping")`
* [x] `pkg/identity/cache/allocator.go:	log.Info("Initializing identity allocator")`
* [x] `pkg/ipam/ipam.go:			}).Info("Marking local route as no-alloc in node allocation prefix")`
* [x] `pkg/ipcache/kvstore.go:			log.Info("Starting IP identity watcher")`
* [x] `pkg/k8s/apis/cilium.io/v2/register.go:		scopedLog.Info("Creating CRD (CustomResourceDefinition)...")`
* [x] `pkg/k8s/apis/cilium.io/v2/register.go:		scopedLog.Info("Updating CRD (CustomResourceDefinition)...")`
* [x] `pkg/k8s/apis/cilium.io/v2/register.go:	scopedLog.Info("CRD (CustomResourceDefinition) is installed and up-to-date")`
* [x] `pkg/k8s/client.go:		log.Info("Waiting for k8s api-server to be ready...")`
* [x] `pkg/k8s/client.go:		log.WithField(logfields.IPAddr, config.Host).Info("Connected to k8s api-server")`
* [x] `pkg/k8s/init.go:	log.WithField(logfields.NodeName, n.Name).Info("Retrieved node information from kubernetes")`
* [x] `pkg/k8s/init.go:			}).Info("Received own node information from API server")`
* [x] `pkg/k8s/service.go:		scopedLog.Info("Ignoring k8s service: empty ClusterIP")` (#7198)
* [ ] `pkg/kvstore/allocator/allocator.go:				scopedLog.Info("Deleted unused allocator master key")`
* [x] `pkg/kvstore/allocator/cache.go:	logger.Info("Starting to watch allocation changes")`
* [x] `pkg/kvstore/consul.go:	log.Info("Waiting for consul to elect a leader")`
* [x] `pkg/kvstore/etcd.go:			log.WithError(err).Info("Waiting for all etcd configuration files to be available")`
* [x] `pkg/kvstore/etcd.go:	}).Info("Connecting to etcd server...")`
* [x] `pkg/kvstore/etcd.go:		}).Info("Successfully verified version of etcd endpoint")`
* [x] `pkg/labels/filter.go:	log.Info("Valid label prefix configuration:")`
* [x] `pkg/maps/ctmap/ctmap.go:	InitMapInfo(option.CTMapEntriesGlobalTCPDefault, option.CTMapEntriesGlobalAnyDefault)`
* [x] `pkg/maps/ctmap/ctmap.go:			scopedLog.Info("CT Map upgraded, expect brief disruption of ongoing connections")` (#7198)
* [x] `pkg/monitor/dissect.go:		log.Info("Initializing dissection cache...")`
* [x] `pkg/node/node_address.go:			log.WithField(logfields.V4Prefix, ipv4AllocRange).Info("Using autogenerated IPv4 allocation range")`
* [x] `pkg/node/node_address.go:			log.WithField(logfields.V6Prefix, ipv6AllocRange).Info("Using autogenerated IPv6 allocation range")`
* [x] `pkg/node/node_address.go:		scopedLog.WithField(logfields.V4Prefix, node.IPv4AllocCIDR).Info("Retrieved IPv4 allocation range for node. Using it for ipv4-range")` (#7198)
* [x] `pkg/node/node_address.go:		scopedLog.WithField(logfields.V6Prefix, node.IPv6AllocCIDR).Info("Retrieved IPv6 allocation range for node. Using it for ipv6-range")` (#7198)
* [x] `pkg/node/node_address.go:		scopedLog.WithField(logfields.IPAddr, nodeIP4).Info("Automatically retrieved IP for node. Using it for ipv4-node")` (#7198)
* [x] `pkg/node/node_address.go:		scopedLog.WithField(logfields.IPAddr, nodeIP6).Info("Automatically retrieved IP for node. Using it for ipv6-node")` (#7198)
* [x] `pkg/nodediscovery/nodediscovery.go:		log.Info("Adding local node to cluster")`
* [x] `pkg/pidfile/pidfile.go:	}).Info("Killing old process")`
* [ ] `pkg/policy/groups/actions.go:		}).Info("New CNP does not have derivative policy, but old had. Deleted old policies")`
* [x] `pkg/proxy/logger/logger.go:	log.WithField(FieldFilePath, logPath).Info("Opened access log")`
* [ ] `pkg/service/id_kvstore.go:			log.WithField(logfields.Identity, *incID).Info("Recycling Service ID")`
* [x] `pkg/sockops/sockops.go:	log.Info("Sockmsg Enabled, bpf_redir loaded")`
* [x] `pkg/sockops/sockops.go:	log.Info("Sockmsg Disabled.")`
* [x] `pkg/sockops/sockops.go:	log.Info("Sockmap disabled.")`
* [x] `pkg/workloads/containerd.go:	log.Info("Enabling containerD event listener")`
* [x] `pkg/workloads/cri.go:	log.Info("Enabling CRI event listener")`
* [ ] `pkg/workloads/cri.go:	scopedLog.Info("No request received to manage networking for container")`
* [ ] `pkg/workloads/cri.go:		scopedLog.Info("Adding running container to the list of ignored containers")`
* [ ] `pkg/workloads/cri.go:		}).Info("Found container running with potential " +`
* [x] `pkg/workloads/docker.go:	log.Info("Enabling docker event listener")`
* [x] `pkg/workloads/docker.go:				log.Info("Docker error channel closed")`
* [ ] `pkg/workloads/docker.go:	scopedLog.Info("No request received to manage networking for container")`
* [ ] `pkg/workloads/docker.go:		scopedLog.Info("Adding running container to the list of ignored containers")`
* [ ] `pkg/workloads/docker.go:		}).Info("Found container running with potential " +`
* [x] `plugins/cilium-docker/driver/driver.go:				scopedLog.Info("Waiting for cilium daemon to start up...")`
* [x] `plugins/cilium-docker/main.go:			log.WithField(logfields.Path, driverSock).Info("Listening for events from Docker")`
* [x] `proxylib/cassandra/cassandraparser.go:	log.Info("init(): Registering cassandraParserFactory")`
* [x] `proxylib/memcached/parser.go:	log.Info("init(): Registering memcacheParserFactory")`
* [x] `proxylib/npds/client.go:				log.Info(err)`
* [x] `proxylib/npds/client_test.go:			log.Info("ACK Callback called")`
* [x] `proxylib/npds/client_test.go:			log.Info("NACK Callback called")`
* [x] `proxylib/r2d2/r2d2parser.go:	log.Info("init(): Registering r2d2ParserFactory")`
* [x] `proxylib/test/accesslog_server.go:	log.Info("Starting Access Log Server")`
* [x] `proxylib/test/accesslog_server.go:			log.Info("Accepted access log connection")`
* [x] `proxylib/test/accesslog_server.go:		log.Info("Closing access log connection")`
* [x] `proxylib/testparsers/blockparser.go:	log.Info("init(): Registering blockParserFactory")`
* [x] `proxylib/testparsers/headerparser.go:	log.Info("headerparser rule matched!")`
* [x] `proxylib/testparsers/headerparser.go:	log.Info("init(): Registering headerParserFactory")`
* [x] `proxylib/testparsers/lineparser.go:	log.Info("init(): Registering lineParserFactory")`
* [x] `proxylib/testparsers/passer.go:	log.Info("init(): Registering PasserParserFactory")`
* [ ] `tools/ring-dump/cmd/root.go:			log.Info("Found data; will decode this later...")`
* [ ] `cilium-health/launch/endpoint.go:			scopedLog.Infof("%s", in.Text())`
* [x] `cilium-health/launch/endpoint.go:	log.Infof("Spawning health endpoint with arguments %#v", args)`
* [ ] `cilium-health/launch/launcher.go:			log.WithError(err).Infof("Cannot establish connection to local %s instance", targetName)`
* [ ] `daemon/daemon.go:			log.Infof("Using IPv4 host address: %s", option.Config.HostV4Addr)`
* [ ] `daemon/daemon.go:			log.Infof("Using IPv6 host address: %s", option.Config.HostV6Addr)`
* [x] `daemon/daemon.go:		log.Infof("  Namespace: %s", option.Config.K8sNamespace)` (#7198)
* [x] `daemon/daemon.go:		log.Infof("Container runtime options set: %s", workloads.GetRuntimeOptions())`
* [x] `daemon/daemon.go:	log.Infof("  Cluster-Name: %s", option.Config.ClusterName)`
* [x] `daemon/daemon.go:	log.Infof("  Cluster-ID: %d", option.Config.ClusterID)`
* [x] `daemon/daemon.go:	log.Infof("  Local node-name: %s", node.GetName())`
* [x] `daemon/daemon.go:		log.Infof("  Node-IPv6: %s", node.GetIPv6())`
* [x] `daemon/daemon.go:		log.Infof("  IPv6 node prefix: %s", node.GetIPv6NodeRange())`
* [x] `daemon/daemon.go:		log.Infof("  IPv6 allocation prefix: %s", node.GetIPv6AllocRange())`
* [x] `daemon/daemon.go:		log.Infof("  IPv6 router address: %s", node.GetIPv6Router())`
* [x] `daemon/daemon.go:		log.Infof("  External-Node IPv4: %s", node.GetExternalIPv4())`
* [x] `daemon/daemon.go:		log.Infof("  Internal-Node IPv4: %s", node.GetInternalIPv4())`
* [x] `daemon/daemon.go:		log.Infof("  Cluster IPv4 prefix: %s", node.GetIPv4ClusterRange())`
* [x] `daemon/daemon.go:		log.Infof("  IPv4 allocation prefix: %s", node.GetIPv4AllocRange())`
* [x] `daemon/daemon.go:		log.Infof("  Loopback IPv4: %s", node.GetIPv4Loopback().String())`
* [x] `daemon/daemon_main.go:		log.Infof("%s check: OK!", logType)`
* [x] `daemon/daemon_main.go:		log.Infof("clang (%s) and kernel (%s) versions: OK!", clangVersion, kernelVersion)`
* [x] `daemon/daemon_main.go:	log.Infof("Cilium %s", version.Version)`
* [x] `daemon/daemon_main.go:		log.Infof("%s", envoyVersion)`
* [ ] `daemon/fqdn.go:			log.WithField(logfields.Controller, dnsGCJobName).Infof(`
* [ ] `daemon/k8s_watcher.go:	scopedLog.Infof("updating node status due to annotations-only change to CiliumNetworkPolicy")`
* [ ] `daemon/k8s_watcher.go:			log.Infof("not updating ipcache entry for node %s because it does not have the CiliumHostIP annotation yet", k8sNode.Name)`
* [x] `daemon/metrics.go:		log.Infof("Serving prometheus metrics on %s", option.Config.PrometheusServeAddr)`
* [x] `daemon/state.go:					scopedLog.Infof(` (#7198)
* [x] `daemon/state.go:				scopedLog.Infof("Interface %s could not be found for endpoint being restored, ignoring", ep.IfName)` (#7198)
* [x] `daemon/state.go:	log.Infof("Regenerating %d restored endpoints", len(state.restored))`
* [x] `monitor/monitor_main.go:	log.Infof("Serving cilium node monitor v1.0 API at unix://%s", defaults.MonitorSockPath1_0)`
* [x] `monitor/monitor_main.go:	log.Infof("Serving cilium node monitor v1.2 API at unix://%s", defaults.MonitorSockPath1_2)`
* [x] `operator/k8s_pod_controller.go:								log.Infof("Restarting unmanaged kube-dns pod %s started %s ago", podID, age)`
* [x] `operator/main.go:	log.Infof("Cilium Operator %s", version.Version)`
* [x] `operator/main.go:		log.Infof("KubeDNS unmanaged pods controller disabled as %q option is set to 'disabled' in Cilium ConfigMap", option.DisableCiliumEndpointCRDName)`
* [x] `pkg/bpf/bpffs_linux.go:		log.Infof("Mounted BPF filesystem %s", mapRoot)`
* [ ] `pkg/controller/controller.go:		c.getLogger().Infof("Limiting interval to %s", maxInterval)`
* [ ] `pkg/endpointmanager/manager.go:	log.Infof("regenerating all endpoints due to %s", regenMetadata.Reason)`
* [x] `pkg/envoy/envoy.go:			log.Infof("Envoy: Proxy started with pid %d", cmd.Process.Pid)`
* [x] `pkg/envoy/envoy.go:				log.Infof("Envoy: Stopping proxy with pid %d", cmd.Process.Pid)`
* [x] `pkg/envoy/grpc.go:		log.Infof("Envoy: Starting xDS gRPC server listening on %s", listener.Addr())`
* [ ] `pkg/fqdn/dnsproxy/proxy.go:		log.Infof("DNS reject response '%s' is not valid, available options are '%v'",`
* [x] `pkg/labels/filter.go:		log.Infof(" - %s", l)`
* [x] `pkg/logging/logging.go:		logrus.Infof("logrus level %v is not supported at this time; defaulting to info level", level)` (#7198)
* [x] `pkg/maps/ctmap/metrics.go:	}).Infof("Conntrack garbage collection statistics")` (#7198)
* [ ] `pkg/maps/ipcache/ipcache.go:			log.Infof("Periodic IPCache map swap will occur due to lack of kernel support for LPM delete operation. Upgrade to Linux 4.15 or higher to avoid this.")`
* [ ] `pkg/mtu/detect_linux.go:		log.Infof("Detected MTU %d", mtu)`
* [ ] `pkg/node/node_address.go:			log.Infof("Restored IPv4 internal node IP: %s", ipv4GW.String())`
* [ ] `pkg/node/node_address.go:			log.Infof("Restored IPv6 router IP: %s", ipv6Router.String())`
* [x] `pkg/option/config.go:		entry.Infof("  --%s='%s'", k, viper.GetString(k))`
* [x] `pkg/sockops/sockops.go:			log.Infof("Mounted Cgroup2 filesystem %s", mapRoot)`
* [x] `pkg/sockops/sockops.go:	log.Infof("Sockmap Enabled: bpf_sockops prog_id %d and map_id %d loaded", progID, mapID)`
* [x] `plugins/cilium-docker/driver/driver.go:	log.Infof("Cilium Docker plugin ready")`
* [x] `proxylib/memcached/binary/parser.go:	log.Infof("ParserFactory: Create: %v", connection)`
* [x] `proxylib/memcached/text/parser.go:	log.Infof("ParserFactory: Create: %v", connection)`
* [x] `proxylib/npds/client.go:		log.Infof("NPDS: Client %s closing on %s", c.nodeId, c.path)`
* [x] `proxylib/npds/client.go:	log.Infof("NPDS: Client %s starting on %s", c.nodeId, c.path)`
* [x] `proxylib/npds/client.go:				log.Infof("NPDS: Client %s connected on %s", c.nodeId, c.path)`
* [x] `proxylib/npds/client_test.go:	log.Infof("Received policy update: %v", *resp)`
* [x] `proxylib/proxylib/instance.go:			log.Infof("Opened existing library instance %d, open count: %d", id, old.openCount)`
* [x] `proxylib/proxylib/instance.go:	log.Infof("Opened new library instance %d", instanceId)`
* [x] `proxylib/proxylib/instance.go:		log.Infof("CloseInstance(%d): Remaining open count: %d", id, count)`
* [x] `proxylib/proxylib/instance.go:		log.Infof("CloseInstance(%d): Not found (closed already?)", id)`
* [x] `proxylib/proxylib/policymap.go:	log.Infof("NPDS: Registering L7 rule parser: %s", l7PolicyTypeName)`
* [x] `proxylib/proxylib/test_util.go:		log.Infof("Text -> proto.Message: %s -> %v", policy, pb)`
* [x] `proxylib/proxylib_test.go:	log.Infof("PanicParserFactory: Create: %v", connection)`
* [x] `proxylib/proxylib_test.go:		log.Infof("Expected error: %s", err)`
* [x] `proxylib/r2d2/r2d2parser.go:		log.Infof("R2d2Rule: cmd mismatch %s, %s", rule.cmdExact, reqData.cmd)`
* [x] `proxylib/r2d2/r2d2parser.go:		log.Infof("R2d2Rule: file mismatch %s, %s", rule.fileRegexCompiled.String(), reqData.file)`
* [x] `proxylib/r2d2/r2d2parser.go:	log.Infof("policy match for rule: '%s' '%s'", rule.cmdExact, regexStr)`
* [x] `proxylib/r2d2/r2d2parser.go:		log.Infof("Parsed rule '%s' '%s'", rr.cmdExact, regexStr)`
* [x] `proxylib/r2d2/r2d2parser.go:	log.Infof("OnData: '%s'", data)`
* [x] `proxylib/r2d2/r2d2parser.go:		log.Infof("No delimiter found, requesting more bytes")`
* [x] `proxylib/r2d2/r2d2parser.go:	log.Infof("Request = '%s'", msgStr)`
* [x] `proxylib/r2d2/r2d2parser.go:		log.Infof("reply, passing %d bytes", msgLen)`
* [x] `proxylib/r2d2/r2d2parser.go:		log.Infof("Policy mismatch, dropping %d bytes", msgLen)`
* [x] `proxylib/test/accesslog_server.go:		log.Infof("Access log message: %s", pblog.String())`
* [x] `proxylib/testparsers/blockparser.go:	log.Infof("BlockParserFactory: Create: %v", connection)`
* [x] `proxylib/testparsers/blockparser.go:		log.Infof("BlockParser: Request: %s", block)`
* [x] `proxylib/testparsers/blockparser.go:		log.Infof("BlockParser: Response: %s", block)`
* [x] `proxylib/testparsers/blockparser.go:	log.Infof("BlockParser: missing: %d", missing)`
* [x] `proxylib/testparsers/headerparser.go:	log.Infof("headerparser checking rule %v", *rule)`
* [x] `proxylib/testparsers/headerparser.go:		log.Infof("headerparser HasPrefix %s does not match %s", bs, rule.hasPrefix)`
* [x] `proxylib/testparsers/headerparser.go:		log.Infof("headerparser Contains %s does not match %s", bs, rule.contains)`
* [x] `proxylib/testparsers/headerparser.go:		log.Infof("headerparser HasSuffix %s does not match %s", bs, rule.hasSuffix)`
* [x] `proxylib/testparsers/headerparser.go:		log.Infof("Parsed HeaderRule pair: %v", hr)`
* [x] `proxylib/testparsers/headerparser.go:	log.Infof("HeaderParserFactory: Create: %v", connection)`
* [x] `proxylib/testparsers/headerparser.go:		log.Infof("HeaderParser: Request: %s", line)`
* [x] `proxylib/testparsers/headerparser.go:		log.Infof("HeaderParser: Response: %s", line)`
* [x] `proxylib/testparsers/lineparser.go:	log.Infof("LineParserFactory: Create: %v", connection)`
* [x] `proxylib/testparsers/lineparser.go:			log.Infof("getLine: unit: %d length: %d index: %d", i, len(s), index)`
* [x] `proxylib/testparsers/lineparser.go:		log.Infof("LineParser: Request: %s", line)`
* [x] `proxylib/testparsers/lineparser.go:		log.Infof("LineParser: Response: %s", line)`
* [x] `proxylib/testparsers/passer.go:	log.Infof("PasserParserFactory: Create: %v", connection)`
* [x] `proxylib/testparsers/passer.go:		log.Infof("PasserParser: Request: %d bytes", n_bytes)`
* [x] `proxylib/testparsers/passer.go:		log.Infof("PasserParser: Response: %d bytes", n_bytes)`
* [x] `tools/ring-dump/cmd/root.go:		log.Infof("%s: %s", k, []byte(v))`

**Comment by ianvernon** [comment]
We can probably ignore `* proxylib/testparsers/*` since it wouldn't be used in an actual Cilium installation in a high-scale environment.

**Comment by jrajahalme** [comment]
@ianvernon Most, if not all, of the `/proxylib` info messages are actually debug messages emitted at info level for convenience (debug messages do not show by default when running tests). I propose we change them to `Debug` and then selectively trigger debug option when needed for unit test debugging.
