### ISSUE TITLE
Improve Cilium policymap entry generation for allow-all with many identities

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#8060]
## Problem description

Cilium master (v1.6 dev cycle)

When there are a large number of identities (for example, 10K with otherwise default Cilium settings), and there is a Cilium endpoint with no policy applied, the agent populates the endpoint's policymap with an entry for each identity, for each direction (for example, 20K entries).

With the default settings, the endpoint PolicyMap size is ~16K, which is less than 20K.

This leads to errors like this showing up in the logs when identity events are received:

```
level=error msg="Failed to add PolicyMap key Ingress: 70734 0" containerID=4af29ea1bc datapathPolicyRevision=0 desiredPolicyRevision=1707 endpointID=1259 error="Unable to update element for map with file descriptor 34: argument list too long" identity=23679 ipv4=10.132.172.182 ipv6= k8sPodName=default/foo subsys=endpoint
```

### Symptoms

Over time, if identities continue to be added, significant increases in policymap update events occur, here is an example as we approach 10K identities with 8 local endpoints, only one of which has policy applied:

![map-sync-failures](https://user-images.githubusercontent.com/1243336/57876002-225a8400-77c9-11e9-84e4-1abd1517493c.png)

At the same time, with many events being handled, we observe high mapSync time:

![map-sync-expensive1](https://user-images.githubusercontent.com/1243336/57876088-559d1300-77c9-11e9-9aae-45038cf8d900.png)

If a Cilium instance gets into this state with such an endpoint, then I have observed locally that upon Cilium restart, Cilium times out ~before starting the API~, and gets into a crashloopbackoff state:

```
...
level=error msg="Failed to add PolicyMap key Ingress: 70734 0" containerID=4af29ea1bc datapathPolicyRevision=0 desiredPolicyRevision=1707 endpointID=1259 error="Unable to update element for map with file descriptor 34: argument list too long" identity=23679 ipv4=10.132.172.182 ipv6= k8sPodName=default/foo subsys=endpoint
level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID=4af29ea1bc datapathPolicyRevision=0 desiredPolicyRevision=1707 endpointID=1259 file-path=1259_next_fail identity=23679 ipv4=10.132.172.182 ipv6= k8sPodName=default/foo subsys=endpoint
level=info msg="Completed endpoint regeneration" bpfCompilation=0s bpfLoadProg=0s bpfWaitForELF=0s bpfWriteELF=0s buildDuration=203.742008ms containerID=4af29ea1bc datapathPolicyRevision=0 desiredPolicyRevision=1707 endpointID=1259 identity=23679 ipv4=10.132.172.182 ipv6= k8sPodName=default/foo mapSync=175.07156ms policyCalculation=27.293584ms prepareBuild="39.022µs" proxyConfiguration=0s proxyPolicyCalculation=0s proxyWaitForAck=0s reason="one or more identities created or deleted" subsys=endpoint waitingForCTClean=0s waitingForLock="1.017µs"
level=info msg="Shutting down... " subsys=daemon
level=info msg="HTTP server Shutdown: context deadline exceeded" subsys=daemon
level=info msg="Stopped serving cilium at unix:///var/run/cilium/cilium.sock" subsys=daemon
level=info msg="Exiting due to signal" signal=terminated subsys=daemon
level=fatal msg="Agent pipe unexpectedly closed, shutting down" subsys=cilium-node-monitor
```

The error `Failed to add PolicyMap key` with `argument list too long` is trying to communicate that the BPF policymap cannot be updated because it is full.

Note also that the mapSync takes quite some time: `mapSync=175.07156ms `.

The killing of Cilium above appears to be triggered from Cilium's own HTTP API handling code, not from kubernetes liveness checks. I'm not sure what the exact impact is of endpoints that fail to regenerate (maybe this causes Cilium startup to always fail?)

## Improving on this behaviour

Upon ingress, we already use a `ep_config_map` entry to skip policymap lookup when no policy is applied:

https://github.com/cilium/cilium/blob/9499c3d70f144d4e555ce7b282dec48613bfc743/bpf/bpf_lxc.c#L771-L775

However, we still populate the policymap entries for such endpoints with no ingress policy.

On egress, there is no corresponding logic to skip policymap lookup when no policy is applied.

## Tasks

* [ ] Investigate how Cilium bootstrap works when an endpoint is guaranteed to fail regeneration
* [ ] Consider whether identity allocation from Cilium should be bounded by some function of `policymap.MaxEntries` (eg, `policymap.MaxEntries / 2`)
* [x] Don't populate the BPF maps with all identities on ingress when policy is disabled
* [x] Consider how to extend egress to gain similar behaviour
  * [x] Introduce datapath logic to handle egress allow-all
    1. Option: Extend the datapath egress path to respect `EP_F_SKIP_POLICY_EGRESS`, similar to the code above
    1. Option: Re-add `#ifdef POLICY_ENABLED_EGRESS`.
       * I'm not as big of a fan of this, because for every potentially common option we introduce, that leads to more required compilations which is quite expensive when starting up Cilium.
  * [x] Don't populate the BPF maps with all identities on egress when policy is disabled

**Comment by joestringer** [comment]
(Also related: #8071 , makes policymap size configurable so the limit can be extended)

**Comment by joestringer** [comment]
Also relevant: Recent improvements to map sync logic have decreased map sync time in similar situations by an order of magnitude.

**Comment by aanm** [comment]
@joestringer btw shouldn't the policy map size be 2 * `number of identities we can have`? because the policy map has ingress and egress policies

**Comment by ianvernon** [comment]
@aanm this "identity explosion" can be worse with port-based policy since we could allow a large set of identities at one port, and then a large set of identities at another port, for both ingress and egress. I don't expect this to be a very common use-case, however.

**Comment by ianvernon** [comment]
From the sig-policy meeting today, @jrajahalme proposed that we could add an option to have a 'wildcard' entry in the policymap that 'allows-all', e.g. with identity 0, port 0, etc. If feasible, this would map nicely to the xDS NetworkPolicy and make those protobufs smaller on average. It would also make the maps stored within Cilium per-endpoint much smaller, as we would simply have one key in the desired / realized state. I suspect that iteration over these maps in userspace when computing what has changed between desired / realized state is costly to performance. One note - would be good to profile this! 

@joestringer has determined that map lookups are fairly cheap, but in the case of allow-all, we would be performing an extra lookup in the drop case.

The flow would be:

* L3-dependent L4
* L4-only (allow all at L3 on a specific port)
* L3-only (allow specific traffic from L3 for all ports)
* L3-only allow all

@joestringer can you please confirm?
