### ISSUE TITLE
Improve unit tests for conntrack lookup in BPF

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9303]
* [x] Merge initial framework PR #9304
* [x] Test the monitor notification behaviour with respect to new, established, closing, closed connection
  * [x] The first lookup should be monitored #9304
  * [x] Subsequent lookups within the timeout should not be monitored #9304
  * [x] After the monitor timeout has passed, a packet should be monitored #9304
  * [x] The first FIN in a direction should be monitored #9304
  * [x] Subsequent packets in the same direction do not need to be monitored #9771
  * [x] The second FIN (closing the other direction) should be monitored #9304
  * [x] Subsequent packets in the FIN direction do not need to be monitored #9304
* [x] Test the timeout behaviour of `__ct_lookup()`
  * [x] When only SYN was seen, there is the SYN timeout #9771
  * [x] When other subsequent packets were seen, there is the standard TCP lifetime timeout #9771
  * [x] Once bidirectional close (fin/rst) was seen, there is the FIN timeout #9771
* [x] When looking up a tuple that was not previously connection-tracked, the function should return CT_NEW. #10064
