### ISSUE TITLE
Optimized eBPF trace for forward action logging (datapath)

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#9914]
### Summary

The current datapath supports trace and capture notifications on drops as well as on various entry and exit points. In order to support the understanding of what policy rules are being utilized, a trace message is required which is submitted on first occurrence of a flow.

### Details

The current trace notifications are intended for troubleshooting and debugging. While they offer great visibility, their impact can be high. There is a minimal optimization in place or TCP based on TCP flags but a connection tracker based approach will help further reduce the overhead to gain visibility.

### Tasks

- [ ] Define metadata for trace message
- [ ] Add ability to emit trace message on `CT_NEW`
- [ ] Add datapath option to disable/enable decoupled from existing trace message flag to allow enabling this lower frequency message without requiring to enable any per packet notifications.
- [ ] Add `cilium monitor` parser
