### ISSUE TITLE
Remove dependency on understanding PodCIDR range of node

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#9918]
### Summary

Remove all dependencies on understanding the PodCIDR of the node.

### Details

The dependency on understanding PodCIDR or more generally a per node allocation subnet is a leftover from the initial networking model assumptions. Even though Cilium already supports new IPAM modes which operate on lists of IPs, there are still several corner-cases left which rely on understanding the PodCIDR range.

### Tasks

- [ ] Implement new Kubernetes IPAM mode which depends on v1.Node PodCIDR (@tgraf)
- [ ] Implement new operator-based PodCIDR allocation to replace current legacy fallback (auto alloc in 10.0.0.0/8 space) (@aanm)
- [ ] Deprecate old legacy fallback (@aanm)
- [ ] Fix MASQ/SNAT iptables rules do not depend on understanding the PodCIDR
- [ ] Fix reporting of PodCIDR to still report it if IPAM is using the PodCIDR but indicate the optional status
- [ ] Fix the transparent encryption feature to not depend on PodCIDR (`AllocationCIDR()`)
